// Biblioteca de ícones — reescrita em 01/09/2026 (pedido do Rafael: os
// ícones antigos eram formas geométricas simples demais, "nem dá pra
// entender direito"). Agora são 3 estilos de VERDADE, não uma cor
// reaproveitada em cima do mesmo desenho:
//
// - "Apenas borda" e "Preenchido" — ícones reais e reconhecíveis da
//   biblioteca Heroicons (MIT), variantes outline/solid do MESMO conjunto
//   (mesmo nome em `24/outline` e `24/solid`), com cor livre escolhida numa
//   paleta limitada e tradicional (ver `PALETA_CORES` abaixo) — escolher uma
//   cor muda todos os ícones da grade na hora, porque todos recebem a mesma
//   `cor` via prop.
// - "3D colorido" (nome novo do antigo "Colorido") — biblioteca TOTALMENTE
//   separada: emoji nativo do sistema. Não é um desenho recolorido, é um
//   ícone real, colorido por natureza — por isso não tem escolha de cor (a
//   mesma razão de antes: cor própria e fixa, só que agora com um ícone de
//   verdade em vez de um círculo/retângulo).
import type { CSSProperties } from 'react'
import type { ComponentType, SVGProps } from 'react'
import {
  Squares2X2Icon,
  ShoppingCartIcon,
  CakeIcon,
  HomeIcon,
  TruckIcon,
  BoltIcon,
  PlusCircleIcon,
  AcademicCapIcon,
  FilmIcon,
  MusicalNoteIcon,
  PaperAirplaneIcon,
  TagIcon,
  TrophyIcon,
  GiftIcon,
  ArchiveBoxIcon,
  CreditCardIcon,
  BanknotesIcon,
  ArrowsRightLeftIcon,
  ReceiptPercentIcon,
  ArrowPathIcon,
  DevicePhoneMobileIcon,
  HeartIcon,
  BriefcaseIcon,
  ShieldCheckIcon,
  BeakerIcon,
  BuildingStorefrontIcon,
  ArrowTrendingUpIcon,
  HandRaisedIcon,
  BuildingLibraryIcon,
  WalletIcon,
  // 01/09/2026, rodada seguinte — tripliquei a biblioteca (pedido do
  // Rafael): mais 60 ícones (30 originais → 90), mesma técnica (Heroicons
  // outline/solid + emoji), cobrindo mais categorias comuns de gasto
  // pessoal que não tinham ícone dedicado ainda.
  ShoppingBagIcon,
  BuildingOfficeIcon,
  BuildingOffice2Icon,
  ComputerDesktopIcon,
  DeviceTabletIcon,
  TvIcon,
  WifiIcon,
  PhoneIcon,
  RadioIcon,
  BookOpenIcon,
  PencilSquareIcon,
  CalculatorIcon,
  CameraIcon,
  VideoCameraIcon,
  PhotoIcon,
  PuzzlePieceIcon,
  SparklesIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  FireIcon,
  GlobeAltIcon,
  MapPinIcon,
  MapIcon,
  TicketIcon,
  UserGroupIcon,
  UsersIcon,
  UserCircleIcon,
  FaceSmileIcon,
  HandThumbUpIcon,
  StarIcon,
  FlagIcon,
  LightBulbIcon,
  WrenchScrewdriverIcon,
  WrenchIcon,
  Cog6ToothIcon,
  KeyIcon,
  LockClosedIcon,
  ScaleIcon,
  ClipboardDocumentListIcon,
  ClipboardDocumentCheckIcon,
  DocumentTextIcon,
  FolderIcon,
  InboxIcon,
  EnvelopeIcon,
  ChatBubbleLeftRightIcon,
  MegaphoneIcon,
  SpeakerWaveIcon,
  MicrophoneIcon,
  RocketLaunchIcon,
  CubeIcon,
  GlobeAmericasIcon,
  HomeModernIcon,
  QueueListIcon,
  NewspaperIcon,
  CurrencyDollarIcon,
  ScissorsIcon,
  SwatchIcon,
  PrinterIcon,
  LifebuoyIcon,

  // 01/09/2026, rodada seguinte (mesmo dia) -- tripliquei de novo (pedido
  // do Rafael): mais 184 icones (90 -> 274), mesma tecnica.
  ChartBarIcon,
  ChartPieIcon,
  ChartBarSquareIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  ArrowTrendingDownIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyYenIcon,
  CurrencyRupeeIcon,
  CurrencyBangladeshiIcon,
  ReceiptRefundIcon,
  PercentBadgeIcon,
  DocumentCurrencyDollarIcon,
  DocumentChartBarIcon,
  DocumentCheckIcon,
  DocumentPlusIcon,
  DocumentMinusIcon,
  DocumentMagnifyingGlassIcon,
  DocumentDuplicateIcon,
  DocumentArrowDownIcon,
  DocumentArrowUpIcon,
  DocumentIcon,
  PaperClipIcon,
  ClipboardIcon,
  ClipboardDocumentIcon,
  IdentificationIcon,
  LanguageIcon,
  LinkIcon,
  QrCodeIcon,
  ServerIcon,
  ServerStackIcon,
  CircleStackIcon,
  CpuChipIcon,
  WindowIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  SignalIcon,
  SignalSlashIcon,
  Battery100Icon,
  Battery50Icon,
  Battery0Icon,
  RssIcon,
  BugAntIcon,
  CalendarIcon,
  CalendarDaysIcon,
  CalendarDateRangeIcon,
  ClockIcon,
  BellAlertIcon,
  BellSlashIcon,
  BellSnoozeIcon,
  ChatBubbleLeftIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleBottomCenterIcon,
  ChatBubbleOvalLeftIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  ChatBubbleLeftEllipsisIcon,
  AtSymbolIcon,
  EnvelopeOpenIcon,
  ShareIcon,
  UserIcon,
  UserPlusIcon,
  UserMinusIcon,
  FingerPrintIcon,
  FaceFrownIcon,
  HandThumbDownIcon,
  PaintBrushIcon,
  GiftTopIcon,
  GifIcon,
  BookmarkIcon,
  BookmarkSlashIcon,
  BookmarkSquareIcon,
  GlobeAsiaAustraliaIcon,
  GlobeEuropeAfricaIcon,
  HashtagIcon,
  CheckBadgeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  ShieldExclamationIcon,
  EyeIcon,
  EyeSlashIcon,
  LockOpenIcon,
  NoSymbolIcon,
  CheckCircleIcon,
  CheckIcon,
  XCircleIcon,
  TrashIcon,
  FunnelIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassPlusIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassCircleIcon,
  PauseCircleIcon,
  PauseIcon,
  PlayCircleIcon,
  PlayIcon,
  PlayPauseIcon,
  StopIcon,
  StopCircleIcon,
  ForwardIcon,
  BackwardIcon,
  BackspaceIcon,
  PowerIcon,
  BoltSlashIcon,
  FolderPlusIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderArrowDownIcon,
  InboxArrowDownIcon,
  InboxStackIcon,
  ArchiveBoxArrowDownIcon,
  ArchiveBoxXMarkIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpCircleIcon,
  ArrowDownCircleIcon,
  ArrowLeftCircleIcon,
  ArrowRightCircleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpOnSquareIcon,
  ArrowUpOnSquareStackIcon,
  ArrowDownOnSquareIcon,
  ArrowDownOnSquareStackIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  ArrowUturnDownIcon,
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  ArrowsUpDownIcon,
  ArrowRightOnRectangleIcon,
  ArrowLeftOnRectangleIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowLeftStartOnRectangleIcon,
  ArrowLeftEndOnRectangleIcon,
  PhoneArrowDownLeftIcon,
  PhoneArrowUpRightIcon,
  PhoneXMarkIcon,
  ArrowPathRoundedSquareIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  BellIcon,
  Cog8ToothIcon,
  CogIcon,
  CubeTransparentIcon,
  LinkSlashIcon,
  MinusCircleIcon,
  PencilIcon,
  SpeakerXMarkIcon,
  VideoCameraSlashIcon,
  DocumentCurrencyEuroIcon,
  DocumentCurrencyPoundIcon,
  DocumentCurrencyYenIcon,
  DocumentCurrencyRupeeIcon,
  DocumentCurrencyBangladeshiIcon,
  ChevronDoubleUpIcon,
  ChevronDoubleDownIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  Bars3Icon,
  ListBulletIcon,
  NumberedListIcon,
  TableCellsIcon,
  ViewColumnsIcon,
  SquaresPlusIcon,
  RectangleStackIcon,
  Square3Stack3DIcon,
  CodeBracketIcon,
  CommandLineIcon,
  VariableIcon,

  // 01/09/2026, rodada seguinte (mesmo dia) -- pedido do Rafael: "quadruplique
  // a quantidade de icones". Investigado antes de mexer: o Heroicons v2.2.0
  // (biblioteca usada aqui) só tem 324 icones REAIS e diferentes entre si no
  // conjunto 24px; os 271 acima já usavam quase tudo, sobravam só estes 53.
  // Perguntei pro Rafael se preferia (a) parar aqui com todos únicos, (b)
  // "quadruplicar" de verdade reaproveitando o mesmo desenho em varias
  // entradas diferentes, ou (c) um meio-termo -- ele escolheu (a): manter
  // todo icone da grade visualmente distinto, mesmo não sendo 4x. Com estes
  // 53 a biblioteca chega no teto real de 324 (271 -> 324).
  ArrowLongDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowLongUpIcon,
  ArrowSmallDownIcon,
  ArrowSmallLeftIcon,
  ArrowSmallRightIcon,
  ArrowSmallUpIcon,
  ArrowTurnDownLeftIcon,
  ArrowTurnDownRightIcon,
  ArrowTurnLeftDownIcon,
  ArrowTurnLeftUpIcon,
  ArrowTurnRightDownIcon,
  ArrowTurnRightUpIcon,
  ArrowTurnUpLeftIcon,
  ArrowTurnUpRightIcon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars4Icon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  BoldIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  CodeBracketSquareIcon,
  CursorArrowRaysIcon,
  CursorArrowRippleIcon,
  DivideIcon,
  EllipsisHorizontalCircleIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EqualsIcon,
  EyeDropperIcon,
  H1Icon,
  H2Icon,
  H3Icon,
  ItalicIcon,
  MinusIcon,
  MinusSmallIcon,
  PlusIcon,
  PlusSmallIcon,
  RectangleGroupIcon,
  SlashIcon,
  Square2StackIcon,
  StrikethroughIcon,
  UnderlineIcon,
  ViewfinderCircleIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'
import {
  Squares2X2Icon as Squares2X2IconSolid,
  ShoppingCartIcon as ShoppingCartIconSolid,
  CakeIcon as CakeIconSolid,
  HomeIcon as HomeIconSolid,
  TruckIcon as TruckIconSolid,
  BoltIcon as BoltIconSolid,
  PlusCircleIcon as PlusCircleIconSolid,
  AcademicCapIcon as AcademicCapIconSolid,
  FilmIcon as FilmIconSolid,
  MusicalNoteIcon as MusicalNoteIconSolid,
  PaperAirplaneIcon as PaperAirplaneIconSolid,
  TagIcon as TagIconSolid,
  TrophyIcon as TrophyIconSolid,
  GiftIcon as GiftIconSolid,
  ArchiveBoxIcon as ArchiveBoxIconSolid,
  CreditCardIcon as CreditCardIconSolid,
  BanknotesIcon as BanknotesIconSolid,
  ArrowsRightLeftIcon as ArrowsRightLeftIconSolid,
  ReceiptPercentIcon as ReceiptPercentIconSolid,
  ArrowPathIcon as ArrowPathIconSolid,
  DevicePhoneMobileIcon as DevicePhoneMobileIconSolid,
  HeartIcon as HeartIconSolid,
  BriefcaseIcon as BriefcaseIconSolid,
  ShieldCheckIcon as ShieldCheckIconSolid,
  BeakerIcon as BeakerIconSolid,
  BuildingStorefrontIcon as BuildingStorefrontIconSolid,
  ArrowTrendingUpIcon as ArrowTrendingUpIconSolid,
  HandRaisedIcon as HandRaisedIconSolid,
  BuildingLibraryIcon as BuildingLibraryIconSolid,
  WalletIcon as WalletIconSolid,
  ShoppingBagIcon as ShoppingBagIconSolid,
  BuildingOfficeIcon as BuildingOfficeIconSolid,
  BuildingOffice2Icon as BuildingOffice2IconSolid,
  ComputerDesktopIcon as ComputerDesktopIconSolid,
  DeviceTabletIcon as DeviceTabletIconSolid,
  TvIcon as TvIconSolid,
  WifiIcon as WifiIconSolid,
  PhoneIcon as PhoneIconSolid,
  RadioIcon as RadioIconSolid,
  BookOpenIcon as BookOpenIconSolid,
  PencilSquareIcon as PencilSquareIconSolid,
  CalculatorIcon as CalculatorIconSolid,
  CameraIcon as CameraIconSolid,
  VideoCameraIcon as VideoCameraIconSolid,
  PhotoIcon as PhotoIconSolid,
  PuzzlePieceIcon as PuzzlePieceIconSolid,
  SparklesIcon as SparklesIconSolid,
  SunIcon as SunIconSolid,
  MoonIcon as MoonIconSolid,
  CloudIcon as CloudIconSolid,
  FireIcon as FireIconSolid,
  GlobeAltIcon as GlobeAltIconSolid,
  MapPinIcon as MapPinIconSolid,
  MapIcon as MapIconSolid,
  TicketIcon as TicketIconSolid,
  UserGroupIcon as UserGroupIconSolid,
  UsersIcon as UsersIconSolid,
  UserCircleIcon as UserCircleIconSolid,
  FaceSmileIcon as FaceSmileIconSolid,
  HandThumbUpIcon as HandThumbUpIconSolid,
  StarIcon as StarIconSolid,
  FlagIcon as FlagIconSolid,
  LightBulbIcon as LightBulbIconSolid,
  WrenchScrewdriverIcon as WrenchScrewdriverIconSolid,
  WrenchIcon as WrenchIconSolid,
  Cog6ToothIcon as Cog6ToothIconSolid,
  KeyIcon as KeyIconSolid,
  LockClosedIcon as LockClosedIconSolid,
  ScaleIcon as ScaleIconSolid,
  ClipboardDocumentListIcon as ClipboardDocumentListIconSolid,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckIconSolid,
  DocumentTextIcon as DocumentTextIconSolid,
  FolderIcon as FolderIconSolid,
  InboxIcon as InboxIconSolid,
  EnvelopeIcon as EnvelopeIconSolid,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconSolid,
  MegaphoneIcon as MegaphoneIconSolid,
  SpeakerWaveIcon as SpeakerWaveIconSolid,
  MicrophoneIcon as MicrophoneIconSolid,
  RocketLaunchIcon as RocketLaunchIconSolid,
  CubeIcon as CubeIconSolid,
  GlobeAmericasIcon as GlobeAmericasIconSolid,
  HomeModernIcon as HomeModernIconSolid,
  QueueListIcon as QueueListIconSolid,
  NewspaperIcon as NewspaperIconSolid,
  CurrencyDollarIcon as CurrencyDollarIconSolid,
  ScissorsIcon as ScissorsIconSolid,
  SwatchIcon as SwatchIconSolid,
  PrinterIcon as PrinterIconSolid,
  LifebuoyIcon as LifebuoyIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  ChartPieIcon as ChartPieIconSolid,
  ChartBarSquareIcon as ChartBarSquareIconSolid,
  PresentationChartBarIcon as PresentationChartBarIconSolid,
  PresentationChartLineIcon as PresentationChartLineIconSolid,
  ArrowTrendingDownIcon as ArrowTrendingDownIconSolid,
  CurrencyEuroIcon as CurrencyEuroIconSolid,
  CurrencyPoundIcon as CurrencyPoundIconSolid,
  CurrencyYenIcon as CurrencyYenIconSolid,
  CurrencyRupeeIcon as CurrencyRupeeIconSolid,
  CurrencyBangladeshiIcon as CurrencyBangladeshiIconSolid,
  ReceiptRefundIcon as ReceiptRefundIconSolid,
  PercentBadgeIcon as PercentBadgeIconSolid,
  DocumentCurrencyDollarIcon as DocumentCurrencyDollarIconSolid,
  DocumentChartBarIcon as DocumentChartBarIconSolid,
  DocumentCheckIcon as DocumentCheckIconSolid,
  DocumentPlusIcon as DocumentPlusIconSolid,
  DocumentMinusIcon as DocumentMinusIconSolid,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlassIconSolid,
  DocumentDuplicateIcon as DocumentDuplicateIconSolid,
  DocumentArrowDownIcon as DocumentArrowDownIconSolid,
  DocumentArrowUpIcon as DocumentArrowUpIconSolid,
  DocumentIcon as DocumentIconSolid,
  PaperClipIcon as PaperClipIconSolid,
  ClipboardIcon as ClipboardIconSolid,
  ClipboardDocumentIcon as ClipboardDocumentIconSolid,
  IdentificationIcon as IdentificationIconSolid,
  LanguageIcon as LanguageIconSolid,
  LinkIcon as LinkIconSolid,
  QrCodeIcon as QrCodeIconSolid,
  ServerIcon as ServerIconSolid,
  ServerStackIcon as ServerStackIconSolid,
  CircleStackIcon as CircleStackIconSolid,
  CpuChipIcon as CpuChipIconSolid,
  WindowIcon as WindowIconSolid,
  CloudArrowDownIcon as CloudArrowDownIconSolid,
  CloudArrowUpIcon as CloudArrowUpIconSolid,
  SignalIcon as SignalIconSolid,
  SignalSlashIcon as SignalSlashIconSolid,
  Battery100Icon as Battery100IconSolid,
  Battery50Icon as Battery50IconSolid,
  Battery0Icon as Battery0IconSolid,
  RssIcon as RssIconSolid,
  BugAntIcon as BugAntIconSolid,
  CalendarIcon as CalendarIconSolid,
  CalendarDaysIcon as CalendarDaysIconSolid,
  CalendarDateRangeIcon as CalendarDateRangeIconSolid,
  ClockIcon as ClockIconSolid,
  BellAlertIcon as BellAlertIconSolid,
  BellSlashIcon as BellSlashIconSolid,
  BellSnoozeIcon as BellSnoozeIconSolid,
  ChatBubbleLeftIcon as ChatBubbleLeftIconSolid,
  ChatBubbleBottomCenterTextIcon as ChatBubbleBottomCenterTextIconSolid,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenterIconSolid,
  ChatBubbleOvalLeftIcon as ChatBubbleOvalLeftIconSolid,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsisIconSolid,
  ChatBubbleLeftEllipsisIcon as ChatBubbleLeftEllipsisIconSolid,
  AtSymbolIcon as AtSymbolIconSolid,
  EnvelopeOpenIcon as EnvelopeOpenIconSolid,
  ShareIcon as ShareIconSolid,
  UserIcon as UserIconSolid,
  UserPlusIcon as UserPlusIconSolid,
  UserMinusIcon as UserMinusIconSolid,
  FingerPrintIcon as FingerPrintIconSolid,
  FaceFrownIcon as FaceFrownIconSolid,
  HandThumbDownIcon as HandThumbDownIconSolid,
  PaintBrushIcon as PaintBrushIconSolid,
  GiftTopIcon as GiftTopIconSolid,
  GifIcon as GifIconSolid,
  BookmarkIcon as BookmarkIconSolid,
  BookmarkSlashIcon as BookmarkSlashIconSolid,
  BookmarkSquareIcon as BookmarkSquareIconSolid,
  GlobeAsiaAustraliaIcon as GlobeAsiaAustraliaIconSolid,
  GlobeEuropeAfricaIcon as GlobeEuropeAfricaIconSolid,
  HashtagIcon as HashtagIconSolid,
  CheckBadgeIcon as CheckBadgeIconSolid,
  ExclamationCircleIcon as ExclamationCircleIconSolid,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleIconSolid,
  ShieldExclamationIcon as ShieldExclamationIconSolid,
  EyeIcon as EyeIconSolid,
  EyeSlashIcon as EyeSlashIconSolid,
  LockOpenIcon as LockOpenIconSolid,
  NoSymbolIcon as NoSymbolIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  CheckIcon as CheckIconSolid,
  XCircleIcon as XCircleIconSolid,
  TrashIcon as TrashIconSolid,
  FunnelIcon as FunnelIconSolid,
  MagnifyingGlassIcon as MagnifyingGlassIconSolid,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlusIconSolid,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinusIconSolid,
  MagnifyingGlassCircleIcon as MagnifyingGlassCircleIconSolid,
  PauseCircleIcon as PauseCircleIconSolid,
  PauseIcon as PauseIconSolid,
  PlayCircleIcon as PlayCircleIconSolid,
  PlayIcon as PlayIconSolid,
  PlayPauseIcon as PlayPauseIconSolid,
  StopIcon as StopIconSolid,
  StopCircleIcon as StopCircleIconSolid,
  ForwardIcon as ForwardIconSolid,
  BackwardIcon as BackwardIconSolid,
  BackspaceIcon as BackspaceIconSolid,
  PowerIcon as PowerIconSolid,
  BoltSlashIcon as BoltSlashIconSolid,
  FolderPlusIcon as FolderPlusIconSolid,
  FolderMinusIcon as FolderMinusIconSolid,
  FolderOpenIcon as FolderOpenIconSolid,
  FolderArrowDownIcon as FolderArrowDownIconSolid,
  InboxArrowDownIcon as InboxArrowDownIconSolid,
  InboxStackIcon as InboxStackIconSolid,
  ArchiveBoxArrowDownIcon as ArchiveBoxArrowDownIconSolid,
  ArchiveBoxXMarkIcon as ArchiveBoxXMarkIconSolid,
  ArrowUpIcon as ArrowUpIconSolid,
  ArrowDownIcon as ArrowDownIconSolid,
  ArrowLeftIcon as ArrowLeftIconSolid,
  ArrowRightIcon as ArrowRightIconSolid,
  ArrowUpCircleIcon as ArrowUpCircleIconSolid,
  ArrowDownCircleIcon as ArrowDownCircleIconSolid,
  ArrowLeftCircleIcon as ArrowLeftCircleIconSolid,
  ArrowRightCircleIcon as ArrowRightCircleIconSolid,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareIconSolid,
  ArrowUpOnSquareIcon as ArrowUpOnSquareIconSolid,
  ArrowUpOnSquareStackIcon as ArrowUpOnSquareStackIconSolid,
  ArrowDownOnSquareIcon as ArrowDownOnSquareIconSolid,
  ArrowDownOnSquareStackIcon as ArrowDownOnSquareStackIconSolid,
  ArrowDownTrayIcon as ArrowDownTrayIconSolid,
  ArrowUpTrayIcon as ArrowUpTrayIconSolid,
  ArrowUturnLeftIcon as ArrowUturnLeftIconSolid,
  ArrowUturnRightIcon as ArrowUturnRightIconSolid,
  ArrowUturnUpIcon as ArrowUturnUpIconSolid,
  ArrowUturnDownIcon as ArrowUturnDownIconSolid,
  ArrowsPointingOutIcon as ArrowsPointingOutIconSolid,
  ArrowsPointingInIcon as ArrowsPointingInIconSolid,
  ArrowsUpDownIcon as ArrowsUpDownIconSolid,
  ArrowRightOnRectangleIcon as ArrowRightOnRectangleIconSolid,
  ArrowLeftOnRectangleIcon as ArrowLeftOnRectangleIconSolid,
  ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleIconSolid,
  ArrowRightEndOnRectangleIcon as ArrowRightEndOnRectangleIconSolid,
  ArrowLeftStartOnRectangleIcon as ArrowLeftStartOnRectangleIconSolid,
  ArrowLeftEndOnRectangleIcon as ArrowLeftEndOnRectangleIconSolid,
  PhoneArrowDownLeftIcon as PhoneArrowDownLeftIconSolid,
  PhoneArrowUpRightIcon as PhoneArrowUpRightIconSolid,
  PhoneXMarkIcon as PhoneXMarkIconSolid,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquareIconSolid,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconSolid,
  AdjustmentsVerticalIcon as AdjustmentsVerticalIconSolid,
  ArrowDownLeftIcon as ArrowDownLeftIconSolid,
  ArrowDownRightIcon as ArrowDownRightIconSolid,
  ArrowUpLeftIcon as ArrowUpLeftIconSolid,
  ArrowUpRightIcon as ArrowUpRightIconSolid,
  BellIcon as BellIconSolid,
  Cog8ToothIcon as Cog8ToothIconSolid,
  CogIcon as CogIconSolid,
  CubeTransparentIcon as CubeTransparentIconSolid,
  LinkSlashIcon as LinkSlashIconSolid,
  MinusCircleIcon as MinusCircleIconSolid,
  PencilIcon as PencilIconSolid,
  SpeakerXMarkIcon as SpeakerXMarkIconSolid,
  VideoCameraSlashIcon as VideoCameraSlashIconSolid,
  DocumentCurrencyEuroIcon as DocumentCurrencyEuroIconSolid,
  DocumentCurrencyPoundIcon as DocumentCurrencyPoundIconSolid,
  DocumentCurrencyYenIcon as DocumentCurrencyYenIconSolid,
  DocumentCurrencyRupeeIcon as DocumentCurrencyRupeeIconSolid,
  DocumentCurrencyBangladeshiIcon as DocumentCurrencyBangladeshiIconSolid,
  ChevronDoubleUpIcon as ChevronDoubleUpIconSolid,
  ChevronDoubleDownIcon as ChevronDoubleDownIconSolid,
  ChevronUpIcon as ChevronUpIconSolid,
  ChevronDownIcon as ChevronDownIconSolid,
  Bars3Icon as Bars3IconSolid,
  ListBulletIcon as ListBulletIconSolid,
  NumberedListIcon as NumberedListIconSolid,
  TableCellsIcon as TableCellsIconSolid,
  ViewColumnsIcon as ViewColumnsIconSolid,
  SquaresPlusIcon as SquaresPlusIconSolid,
  RectangleStackIcon as RectangleStackIconSolid,
  Square3Stack3DIcon as Square3Stack3DIconSolid,
  CodeBracketIcon as CodeBracketIconSolid,
  CommandLineIcon as CommandLineIconSolid,
  VariableIcon as VariableIconSolid,

  ArrowLongDownIcon as ArrowLongDownIconSolid,
  ArrowLongLeftIcon as ArrowLongLeftIconSolid,
  ArrowLongRightIcon as ArrowLongRightIconSolid,
  ArrowLongUpIcon as ArrowLongUpIconSolid,
  ArrowSmallDownIcon as ArrowSmallDownIconSolid,
  ArrowSmallLeftIcon as ArrowSmallLeftIconSolid,
  ArrowSmallRightIcon as ArrowSmallRightIconSolid,
  ArrowSmallUpIcon as ArrowSmallUpIconSolid,
  ArrowTurnDownLeftIcon as ArrowTurnDownLeftIconSolid,
  ArrowTurnDownRightIcon as ArrowTurnDownRightIconSolid,
  ArrowTurnLeftDownIcon as ArrowTurnLeftDownIconSolid,
  ArrowTurnLeftUpIcon as ArrowTurnLeftUpIconSolid,
  ArrowTurnRightDownIcon as ArrowTurnRightDownIconSolid,
  ArrowTurnRightUpIcon as ArrowTurnRightUpIconSolid,
  ArrowTurnUpLeftIcon as ArrowTurnUpLeftIconSolid,
  ArrowTurnUpRightIcon as ArrowTurnUpRightIconSolid,
  Bars2Icon as Bars2IconSolid,
  Bars3BottomLeftIcon as Bars3BottomLeftIconSolid,
  Bars3BottomRightIcon as Bars3BottomRightIconSolid,
  Bars3CenterLeftIcon as Bars3CenterLeftIconSolid,
  Bars4Icon as Bars4IconSolid,
  BarsArrowDownIcon as BarsArrowDownIconSolid,
  BarsArrowUpIcon as BarsArrowUpIconSolid,
  BoldIcon as BoldIconSolid,
  ChevronDoubleLeftIcon as ChevronDoubleLeftIconSolid,
  ChevronDoubleRightIcon as ChevronDoubleRightIconSolid,
  ChevronLeftIcon as ChevronLeftIconSolid,
  ChevronRightIcon as ChevronRightIconSolid,
  ChevronUpDownIcon as ChevronUpDownIconSolid,
  CodeBracketSquareIcon as CodeBracketSquareIconSolid,
  CursorArrowRaysIcon as CursorArrowRaysIconSolid,
  CursorArrowRippleIcon as CursorArrowRippleIconSolid,
  DivideIcon as DivideIconSolid,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleIconSolid,
  EllipsisHorizontalIcon as EllipsisHorizontalIconSolid,
  EllipsisVerticalIcon as EllipsisVerticalIconSolid,
  EqualsIcon as EqualsIconSolid,
  EyeDropperIcon as EyeDropperIconSolid,
  H1Icon as H1IconSolid,
  H2Icon as H2IconSolid,
  H3Icon as H3IconSolid,
  ItalicIcon as ItalicIconSolid,
  MinusIcon as MinusIconSolid,
  MinusSmallIcon as MinusSmallIconSolid,
  PlusIcon as PlusIconSolid,
  PlusSmallIcon as PlusSmallIconSolid,
  RectangleGroupIcon as RectangleGroupIconSolid,
  SlashIcon as SlashIconSolid,
  Square2StackIcon as Square2StackIconSolid,
  StrikethroughIcon as StrikethroughIconSolid,
  UnderlineIcon as UnderlineIconSolid,
  ViewfinderCircleIcon as ViewfinderCircleIconSolid,
  XMarkIcon as XMarkIconSolid,
} from '@heroicons/react/24/solid'

// "colorido" é o id histórico salvo no banco (schema não mudou) — exibido
// na UI como "3D colorido" (ver SeletorIcone.tsx).
export type EstiloIcone = 'colorido' | 'preenchido' | 'borda'

type ComponenteSvg = ComponentType<SVGProps<SVGSVGElement>>

interface DefIcone {
  nome: string
  outline: ComponenteSvg
  solid: ComponenteSvg
  emoji: string
  // 01/09/2026 (pedido do Rafael: sub-abas no seletor de ícone) — cada
  // ícone pertence a UMA categoria de agrupamento (não é a categoria
  // financeira do usuário, é só uma "gaveta" pra organizar a grade de
  // ~324 ícones em abas menores e navegáveis). Ver `CATEGORIAS_ICONE`.
  categoria: string
  // 01/09/2026 (pedido do Rafael: busca por nome OU sinônimo) — lista
  // curta de palavras extras que também devem "achar" esse ícone na busca.
  // Só os ícones mais comuns (as categorias de gasto do dia a dia) têm
  // sinônimo cadastrado à mão; os demais (ícones mais genéricos, de
  // interface/símbolos) contam só com o nome e com o próprio id interno
  // pra busca — ver `buscaIcone` no SeletorIcone.tsx.
  sinonimos?: string[]
}

export const ICONES: Record<string, DefIcone> = {
  outros: { nome: 'Outros', outline: Squares2X2Icon, solid: Squares2X2IconSolid, emoji: '📦', categoria: 'simbolos', sinonimos: ['geral', 'diversos', 'variado'] },
  mercado: { nome: 'Mercado/Compras', outline: ShoppingCartIcon, solid: ShoppingCartIconSolid, emoji: '🛒', categoria: 'compras', sinonimos: ['supermercado', 'feira', 'compras do mes', 'mantimentos'] },
  alimentacao: { nome: 'Alimentação', outline: CakeIcon, solid: CakeIconSolid, emoji: '🍽️', categoria: 'alimentacao', sinonimos: ['comida', 'restaurante', 'almoco', 'jantar', 'lanche'] },
  casa: { nome: 'Casa/Moradia', outline: HomeIcon, solid: HomeIconSolid, emoji: '🏠', categoria: 'moradia', sinonimos: ['moradia', 'aluguel', 'residencia', 'lar'] },
  transporte: { nome: 'Transporte/Carro', outline: TruckIcon, solid: TruckIconSolid, emoji: '🚗', categoria: 'transporte', sinonimos: ['carro', 'veiculo', 'uber', 'onibus', 'deslocamento'] },
  combustivel: { nome: 'Combustível', outline: BoltIcon, solid: BoltIconSolid, emoji: '⛽', categoria: 'transporte', sinonimos: ['gasolina', 'alcool', 'diesel', 'posto'] },
  saude: { nome: 'Saúde', outline: PlusCircleIcon, solid: PlusCircleIconSolid, emoji: '🩺', categoria: 'saude', sinonimos: ['medico', 'remedio', 'farmacia', 'plano de saude', 'clinica'] },
  educacao: { nome: 'Educação', outline: AcademicCapIcon, solid: AcademicCapIconSolid, emoji: '🎓', categoria: 'educacao', sinonimos: ['escola', 'faculdade', 'curso', 'ensino'] },
  lazer: { nome: 'Lazer/Cinema', outline: FilmIcon, solid: FilmIconSolid, emoji: '🎬', categoria: 'lazer', sinonimos: ['cinema', 'entretenimento', 'diversao', 'filme'] },
  musica: { nome: 'Música', outline: MusicalNoteIcon, solid: MusicalNoteIconSolid, emoji: '🎵', categoria: 'lazer', sinonimos: ['spotify', 'show', 'instrumento', 'playlist'] },
  viagem: { nome: 'Viagem', outline: PaperAirplaneIcon, solid: PaperAirplaneIconSolid, emoji: '✈️', categoria: 'lazer', sinonimos: ['ferias', 'passagem', 'turismo', 'viajar'] },
  roupas: { nome: 'Roupas', outline: TagIcon, solid: TagIconSolid, emoji: '👕', categoria: 'compras', sinonimos: ['vestuario', 'moda', 'calcado', 'loja de roupa'] },
  academia: { nome: 'Academia/Esporte', outline: TrophyIcon, solid: TrophyIconSolid, emoji: '🏋️', categoria: 'saude', sinonimos: ['esporte', 'ginastica', 'musculacao', 'personal'] },
  presente: { nome: 'Presente', outline: GiftIcon, solid: GiftIconSolid, emoji: '🎁', categoria: 'compras', sinonimos: ['aniversario', 'gift', 'lembranca'] },
  cofrinho: { nome: 'Cofrinho', outline: ArchiveBoxIcon, solid: ArchiveBoxIconSolid, emoji: '🐷', categoria: 'financas', sinonimos: ['poupanca', 'reserva', 'economia'] },
  cartao: { nome: 'Cartão', outline: CreditCardIcon, solid: CreditCardIconSolid, emoji: '💳', categoria: 'financas', sinonimos: ['credito', 'debito', 'fatura do cartao'] },
  salario: { nome: 'Salário/Renda', outline: BanknotesIcon, solid: BanknotesIconSolid, emoji: '💵', categoria: 'financas', sinonimos: ['renda', 'pagamento', 'holerite', 'pro-labore'] },
  transferencia: { nome: 'Transferência', outline: ArrowsRightLeftIcon, solid: ArrowsRightLeftIconSolid, emoji: '🔄', categoria: 'financas', sinonimos: ['pix', 'ted', 'doc', 'envio de dinheiro'] },
  fatura: { nome: 'Fatura/Recibo', outline: ReceiptPercentIcon, solid: ReceiptPercentIconSolid, emoji: '🧾', categoria: 'financas', sinonimos: ['recibo', 'conta', 'boleto'] },
  assinatura: { nome: 'Assinatura/Serviços', outline: ArrowPathIcon, solid: ArrowPathIconSolid, emoji: '🔁', categoria: 'financas', sinonimos: ['mensalidade', 'servico recorrente', 'plano'] },
  celular: { nome: 'Celular', outline: DevicePhoneMobileIcon, solid: DevicePhoneMobileIconSolid, emoji: '📱', categoria: 'tecnologia', sinonimos: ['smartphone', 'telefone movel', 'plano de celular'] },
  pet: { nome: 'Pet', outline: HeartIcon, solid: HeartIconSolid, emoji: '🐶', categoria: 'pessoas', sinonimos: ['cachorro', 'gato', 'animal de estimacao', 'veterinario'] },
  trabalho: { nome: 'Trabalho', outline: BriefcaseIcon, solid: BriefcaseIconSolid, emoji: '💼', categoria: 'trabalho', sinonimos: ['emprego', 'servico', 'profissao'] },
  protecao: { nome: 'Seguro/Proteção', outline: ShieldCheckIcon, solid: ShieldCheckIconSolid, emoji: '🛡️', categoria: 'seguranca', sinonimos: ['seguro', 'apolice', 'protecao veicular'] },
  bar: { nome: 'Bar/Bebida', outline: BeakerIcon, solid: BeakerIconSolid, emoji: '🍺', categoria: 'alimentacao', sinonimos: ['bebida', 'cerveja', 'happy hour'] },
  cafe: { nome: 'Café', outline: BuildingStorefrontIcon, solid: BuildingStorefrontIconSolid, emoji: '☕', categoria: 'alimentacao', sinonimos: ['cafeteria', 'padaria', 'lanchonete'] },
  investimento: { nome: 'Investimento', outline: ArrowTrendingUpIcon, solid: ArrowTrendingUpIconSolid, emoji: '📈', categoria: 'financas', sinonimos: ['aplicacao', 'bolsa', 'renda fixa', 'acoes'] },
  doacao: { nome: 'Doação', outline: HandRaisedIcon, solid: HandRaisedIconSolid, emoji: '🤝', categoria: 'financas', sinonimos: ['caridade', 'contribuicao', 'ajuda'] },
  impostos: { nome: 'Impostos/Governo', outline: BuildingLibraryIcon, solid: BuildingLibraryIconSolid, emoji: '🏛️', categoria: 'financas', sinonimos: ['governo', 'taxas', 'tributos', 'irpf'] },
  carteira: { nome: 'Carteira/Pagamento', outline: WalletIcon, solid: WalletIconSolid, emoji: '👛', categoria: 'financas', sinonimos: ['dinheiro em especie', 'pagamento'] },

  // --- +60 ícones (01/09/2026, rodada seguinte — biblioteca triplicada) ---
  compras: { nome: 'Compras/Shopping', outline: ShoppingBagIcon, solid: ShoppingBagIconSolid, emoji: '🛍️', categoria: 'compras', sinonimos: ['shopping', 'loja', 'e-commerce'] },
  escritorio: { nome: 'Escritório/Coworking', outline: BuildingOfficeIcon, solid: BuildingOfficeIconSolid, emoji: '🏢', categoria: 'trabalho', sinonimos: ['coworking', 'sala comercial'] },
  condominio: { nome: 'Condomínio', outline: BuildingOffice2Icon, solid: BuildingOffice2IconSolid, emoji: '🏬', categoria: 'moradia', sinonimos: ['taxa condominial'] },
  eletronicos: { nome: 'Eletrônicos/Informática', outline: ComputerDesktopIcon, solid: ComputerDesktopIconSolid, emoji: '💻', categoria: 'tecnologia', sinonimos: ['informatica', 'computador', 'notebook'] },
  tablet: { nome: 'Tablet/Dispositivos', outline: DeviceTabletIcon, solid: DeviceTabletIconSolid, emoji: '📲', categoria: 'tecnologia', sinonimos: ['ipad', 'dispositivo movel'] },
  streaming: { nome: 'Streaming/TV', outline: TvIcon, solid: TvIconSolid, emoji: '📺', categoria: 'lazer', sinonimos: ['netflix', 'tv por assinatura'] },
  internet: { nome: 'Internet/Wi-Fi', outline: WifiIcon, solid: WifiIconSolid, emoji: '📶', categoria: 'tecnologia', sinonimos: ['wifi', 'banda larga', 'provedor'] },
  telefone: { nome: 'Telefone Fixo', outline: PhoneIcon, solid: PhoneIconSolid, emoji: '☎️', categoria: 'tecnologia', sinonimos: ['telefone fixo', 'linha fixa'] },
  podcast: { nome: 'Podcast/Rádio', outline: RadioIcon, solid: RadioIconSolid, emoji: '🎙️', categoria: 'lazer', sinonimos: ['radio online'] },
  livros: { nome: 'Livros/Leitura', outline: BookOpenIcon, solid: BookOpenIconSolid, emoji: '📚', categoria: 'educacao', sinonimos: ['leitura', 'livraria', 'ebook'] },
  cursos: { nome: 'Cursos/Aulas', outline: PencilSquareIcon, solid: PencilSquareIconSolid, emoji: '✏️', categoria: 'educacao', sinonimos: ['aula', 'treinamento', 'capacitacao'] },
  contabilidade: { nome: 'Contabilidade', outline: CalculatorIcon, solid: CalculatorIconSolid, emoji: '🧮', categoria: 'financas', sinonimos: ['contador', 'declaracao', 'balanco'] },
  fotografia: { nome: 'Fotografia', outline: CameraIcon, solid: CameraIconSolid, emoji: '📷', categoria: 'lazer', sinonimos: ['camera', 'fotografo'] },
  video: { nome: 'Vídeo/Produção', outline: VideoCameraIcon, solid: VideoCameraIconSolid, emoji: '🎥', categoria: 'lazer', sinonimos: ['producao de video', 'filmagem'] },
  fotos: { nome: 'Fotos/Álbum', outline: PhotoIcon, solid: PhotoIconSolid, emoji: '🖼️', categoria: 'lazer', sinonimos: ['album', 'imagens'] },
  jogos: { nome: 'Jogos/Games', outline: PuzzlePieceIcon, solid: PuzzlePieceIconSolid, emoji: '🎮', categoria: 'lazer', sinonimos: ['videogame', 'game'] },
  beleza: { nome: 'Beleza/Estética', outline: SparklesIcon, solid: SparklesIconSolid, emoji: '💅', categoria: 'saude', sinonimos: ['salao de beleza', 'cosmeticos', 'estetica'] },
  praia: { nome: 'Praia/Verão', outline: SunIcon, solid: SunIconSolid, emoji: '☀️', categoria: 'lazer', sinonimos: ['verao', 'sol'] },
  noite: { nome: 'Vida Noturna', outline: MoonIcon, solid: MoonIconSolid, emoji: '🌙', categoria: 'lazer', sinonimos: ['balada', 'festa'] },
  nuvem: { nome: 'Armazenamento em Nuvem', outline: CloudIcon, solid: CloudIconSolid, emoji: '☁️', categoria: 'tecnologia', sinonimos: ['armazenamento online', 'backup'] },
  churrasco: { nome: 'Churrasco/Grill', outline: FireIcon, solid: FireIconSolid, emoji: '🔥', categoria: 'alimentacao', sinonimos: ['grill', 'carne'] },
  hospedagem: { nome: 'Hospedagem/Domínio', outline: GlobeAltIcon, solid: GlobeAltIconSolid, emoji: '🌐', categoria: 'tecnologia', sinonimos: ['dominio', 'site', 'servidor web'] },
  estacionamento: { nome: 'Estacionamento', outline: MapPinIcon, solid: MapPinIconSolid, emoji: '📍', categoria: 'transporte', sinonimos: ['zona azul', 'vaga'] },
  passeio: { nome: 'Passeio/Turismo', outline: MapIcon, solid: MapIconSolid, emoji: '🗺️', categoria: 'lazer', sinonimos: ['turismo', 'excursao'] },
  ingresso: { nome: 'Ingresso/Evento', outline: TicketIcon, solid: TicketIconSolid, emoji: '🎫', categoria: 'lazer', sinonimos: ['evento', 'show', 'entrada'] },
  familia: { nome: 'Família', outline: UserGroupIcon, solid: UserGroupIconSolid, emoji: '👨‍👩‍👧', categoria: 'pessoas', sinonimos: ['parentes', 'filhos'] },
  amigos: { nome: 'Amigos/Social', outline: UsersIcon, solid: UsersIconSolid, emoji: '👥', categoria: 'pessoas', sinonimos: ['social', 'turma'] },
  pessoal: { nome: 'Pessoal', outline: UserCircleIcon, solid: UserCircleIconSolid, emoji: '🙋', categoria: 'pessoas', sinonimos: ['individual', 'proprio'] },
  diversao: { nome: 'Diversão', outline: FaceSmileIcon, solid: FaceSmileIconSolid, emoji: '😄', categoria: 'lazer', sinonimos: ['entretenimento'] },
  gorjeta: { nome: 'Gorjeta/Serviço', outline: HandThumbUpIcon, solid: HandThumbUpIconSolid, emoji: '👍', categoria: 'financas', sinonimos: ['servico', 'taxa de servico'] },
  premium: { nome: 'Assinatura Premium', outline: StarIcon, solid: StarIconSolid, emoji: '⭐', categoria: 'financas', sinonimos: ['plano pago', 'vip'] },
  meta: { nome: 'Meta/Objetivo', outline: FlagIcon, solid: FlagIconSolid, emoji: '🚩', categoria: 'financas', sinonimos: ['objetivo', 'planejamento'] },
  energia: { nome: 'Energia Elétrica', outline: LightBulbIcon, solid: LightBulbIconSolid, emoji: '💡', categoria: 'moradia', sinonimos: ['luz', 'conta de luz', 'eletricidade'] },
  manutencao: { nome: 'Manutenção/Reparo', outline: WrenchScrewdriverIcon, solid: WrenchScrewdriverIconSolid, emoji: '🔧', categoria: 'moradia', sinonimos: ['reparo', 'conserto'] },
  ferramentas: { nome: 'Ferramentas', outline: WrenchIcon, solid: WrenchIconSolid, emoji: '🛠️', categoria: 'moradia', sinonimos: ['equipamento'] },
  servicosTecnicos: { nome: 'Serviços Técnicos', outline: Cog6ToothIcon, solid: Cog6ToothIconSolid, emoji: '⚙️', categoria: 'trabalho', sinonimos: ['tecnico', 'assistencia tecnica'] },
  seguranca: { nome: 'Segurança/Chaveiro', outline: KeyIcon, solid: KeyIconSolid, emoji: '🔑', categoria: 'seguranca', sinonimos: ['chaveiro', 'alarme'] },
  cofreDigital: { nome: 'Cofre/Segurança Digital', outline: LockClosedIcon, solid: LockClosedIconSolid, emoji: '🔒', categoria: 'seguranca', sinonimos: ['senha', 'protecao de dados'] },
  juridico: { nome: 'Jurídico/Advocacia', outline: ScaleIcon, solid: ScaleIconSolid, emoji: '⚖️', categoria: 'seguranca', sinonimos: ['advogado', 'processo', 'justica'] },
  documentos: { nome: 'Documentos/Cartório', outline: ClipboardDocumentListIcon, solid: ClipboardDocumentListIconSolid, emoji: '📋', categoria: 'documentos', sinonimos: ['cartorio', 'papelada'] },
  contrato: { nome: 'Contrato', outline: ClipboardDocumentCheckIcon, solid: ClipboardDocumentCheckIconSolid, emoji: '📝', categoria: 'documentos', sinonimos: ['acordo'] },
  boleto: { nome: 'Boleto/Conta', outline: DocumentTextIcon, solid: DocumentTextIconSolid, emoji: '📄', categoria: 'financas', sinonimos: ['conta a pagar'] },
  arquivo: { nome: 'Arquivo/Organização', outline: FolderIcon, solid: FolderIconSolid, emoji: '🗂️', categoria: 'documentos', sinonimos: ['organizacao', 'pasta'] },
  correios: { nome: 'Correios/Encomenda', outline: InboxIcon, solid: InboxIconSolid, emoji: '📮', categoria: 'documentos', sinonimos: ['encomenda', 'sedex'] },
  email: { nome: 'E-mail/Correspondência', outline: EnvelopeIcon, solid: EnvelopeIconSolid, emoji: '✉️', categoria: 'documentos', sinonimos: ['correio eletronico'] },
  comunicacao: { nome: 'Comunicação/Chat', outline: ChatBubbleLeftRightIcon, solid: ChatBubbleLeftRightIconSolid, emoji: '💬', categoria: 'documentos', sinonimos: ['chat', 'mensagem'] },
  marketing: { nome: 'Marketing/Publicidade', outline: MegaphoneIcon, solid: MegaphoneIconSolid, emoji: '📣', categoria: 'trabalho', sinonimos: ['publicidade', 'anuncio'] },
  som: { nome: 'Som/Áudio', outline: SpeakerWaveIcon, solid: SpeakerWaveIconSolid, emoji: '🔊', categoria: 'lazer', sinonimos: ['audio', 'caixa de som'] },
  karaoke: { nome: 'Karaokê/Show', outline: MicrophoneIcon, solid: MicrophoneIconSolid, emoji: '🎤', categoria: 'lazer', sinonimos: ['show ao vivo'] },
  negocio: { nome: 'Negócio/Startup', outline: RocketLaunchIcon, solid: RocketLaunchIconSolid, emoji: '🚀', categoria: 'trabalho', sinonimos: ['empresa', 'startup'] },
  produto: { nome: 'Produto/Estoque', outline: CubeIcon, solid: CubeIconSolid, emoji: '🧊', categoria: 'trabalho', sinonimos: ['estoque', 'mercadoria'] },
  viagemInternacional: { nome: 'Viagem Internacional', outline: GlobeAmericasIcon, solid: GlobeAmericasIconSolid, emoji: '🌎', categoria: 'lazer', sinonimos: ['exterior', 'fora do pais'] },
  moveis: { nome: 'Móveis/Decoração', outline: HomeModernIcon, solid: HomeModernIconSolid, emoji: '🛋️', categoria: 'moradia', sinonimos: ['decoracao', 'mobilia'] },
  planejamentoLista: { nome: 'Lista/Planejamento', outline: QueueListIcon, solid: QueueListIconSolid, emoji: '📑', categoria: 'documentos', sinonimos: ['checklist', 'lista de tarefas'] },
  noticias: { nome: 'Jornal/Notícias', outline: NewspaperIcon, solid: NewspaperIconSolid, emoji: '📰', categoria: 'documentos', sinonimos: ['jornal', 'midia'] },
  cambio: { nome: 'Câmbio/Moeda Estrangeira', outline: CurrencyDollarIcon, solid: CurrencyDollarIconSolid, emoji: '💱', categoria: 'financas', sinonimos: ['moeda estrangeira', 'dolar', 'conversao'] },
  cabeleireiro: { nome: 'Cabeleireiro/Barbearia', outline: ScissorsIcon, solid: ScissorsIconSolid, emoji: '💇', categoria: 'saude', sinonimos: ['barbearia', 'corte de cabelo'] },
  design: { nome: 'Design/Decoração', outline: SwatchIcon, solid: SwatchIconSolid, emoji: '🎨', categoria: 'moradia', sinonimos: ['decoracao', 'estilo'] },
  impressao: { nome: 'Impressão/Papelaria', outline: PrinterIcon, solid: PrinterIconSolid, emoji: '🖨️', categoria: 'trabalho', sinonimos: ['papelaria', 'grafica'] },
  suporte: { nome: 'Suporte/Ajuda', outline: LifebuoyIcon, solid: LifebuoyIconSolid, emoji: '🛟', categoria: 'trabalho', sinonimos: ['ajuda', 'atendimento'] },

  // --- +184 icones (01/09/2026, rodada seguinte, mesmo dia -- 2a triplicacao) ---
  relatorioBarras: { nome: 'Relatório/Gráfico', outline: ChartBarIcon, solid: ChartBarIconSolid, emoji: '📊', categoria: 'financas' },
  relatorioPizza: { nome: 'Gráfico de Pizza', outline: ChartPieIcon, solid: ChartPieIconSolid, emoji: '🥧', categoria: 'financas' },
  painelFinanceiro: { nome: 'Painel/Indicadores', outline: ChartBarSquareIcon, solid: ChartBarSquareIconSolid, emoji: '📈', categoria: 'financas' },
  apresentacaoBarras: { nome: 'Apresentação em Barras', outline: PresentationChartBarIcon, solid: PresentationChartBarIconSolid, emoji: '📽️', categoria: 'trabalho' },
  apresentacaoLinha: { nome: 'Apresentação em Linha', outline: PresentationChartLineIcon, solid: PresentationChartLineIconSolid, emoji: '📉', categoria: 'trabalho' },
  quedaInvestimento: { nome: 'Queda/Prejuízo', outline: ArrowTrendingDownIcon, solid: ArrowTrendingDownIconSolid, emoji: '📉', categoria: 'financas' },
  moedaEuro: { nome: 'Euro', outline: CurrencyEuroIcon, solid: CurrencyEuroIconSolid, emoji: '💶', categoria: 'financas' },
  moedaLibra: { nome: 'Libra Esterlina', outline: CurrencyPoundIcon, solid: CurrencyPoundIconSolid, emoji: '💷', categoria: 'financas' },
  moedaIene: { nome: 'Iene', outline: CurrencyYenIcon, solid: CurrencyYenIconSolid, emoji: '💴', categoria: 'financas' },
  moedaRupia: { nome: 'Rupia', outline: CurrencyRupeeIcon, solid: CurrencyRupeeIconSolid, emoji: '🇮🇳', categoria: 'financas' },
  moedaEstrangeira: { nome: 'Moeda Estrangeira', outline: CurrencyBangladeshiIcon, solid: CurrencyBangladeshiIconSolid, emoji: '💱', categoria: 'financas' },
  reembolsoEstorno: { nome: 'Reembolso/Estorno', outline: ReceiptRefundIcon, solid: ReceiptRefundIconSolid, emoji: '🧾', categoria: 'financas' },
  percentualBonus: { nome: 'Percentual/Bônus', outline: PercentBadgeIcon, solid: PercentBadgeIconSolid, emoji: '💯', categoria: 'financas' },
  documentoFinanceiro: { nome: 'Documento Financeiro', outline: DocumentCurrencyDollarIcon, solid: DocumentCurrencyDollarIconSolid, emoji: '💵', categoria: 'financas' },
  documentoGrafico: { nome: 'Relatório em Documento', outline: DocumentChartBarIcon, solid: DocumentChartBarIconSolid, emoji: '📊', categoria: 'documentos' },
  documentoAprovado: { nome: 'Documento Aprovado', outline: DocumentCheckIcon, solid: DocumentCheckIconSolid, emoji: '✅', categoria: 'documentos' },
  documentoNovo: { nome: 'Novo Documento', outline: DocumentPlusIcon, solid: DocumentPlusIconSolid, emoji: '📄', categoria: 'documentos' },
  documentoRemover: { nome: 'Remover Documento', outline: DocumentMinusIcon, solid: DocumentMinusIconSolid, emoji: '🗑️', categoria: 'documentos' },
  documentoConsultar: { nome: 'Consultar Documento', outline: DocumentMagnifyingGlassIcon, solid: DocumentMagnifyingGlassIconSolid, emoji: '🔎', categoria: 'documentos' },
  documentoDuplicar: { nome: 'Duplicar Documento', outline: DocumentDuplicateIcon, solid: DocumentDuplicateIconSolid, emoji: '📑', categoria: 'documentos' },
  documentoBaixar: { nome: 'Baixar Documento', outline: DocumentArrowDownIcon, solid: DocumentArrowDownIconSolid, emoji: '⬇️', categoria: 'documentos' },
  documentoEnviar: { nome: 'Enviar Documento', outline: DocumentArrowUpIcon, solid: DocumentArrowUpIconSolid, emoji: '⬆️', categoria: 'documentos' },
  documentoGenerico: { nome: 'Documento', outline: DocumentIcon, solid: DocumentIconSolid, emoji: '📃', categoria: 'documentos' },
  clipeDocumento: { nome: 'Anexo/Comprovante', outline: PaperClipIcon, solid: PaperClipIconSolid, emoji: '📎', categoria: 'documentos' },
  prancheta: { nome: 'Prancheta/Checklist', outline: ClipboardIcon, solid: ClipboardIconSolid, emoji: '📋', categoria: 'documentos' },
  prancheDocumento: { nome: 'Prancheta com Documento', outline: ClipboardDocumentIcon, solid: ClipboardDocumentIconSolid, emoji: '🗒️', categoria: 'documentos' },
  identificacao: { nome: 'Identificação/RG', outline: IdentificationIcon, solid: IdentificationIconSolid, emoji: '🪪', categoria: 'documentos' },
  linguagem: { nome: 'Idiomas/Tradução', outline: LanguageIcon, solid: LanguageIconSolid, emoji: '🌍', categoria: 'educacao' },
  link: { nome: 'Link/Assinatura Digital', outline: LinkIcon, solid: LinkIconSolid, emoji: '🔗', categoria: 'tecnologia' },
  assinaturaEletronica: { nome: 'QR Code/Pagamento', outline: QrCodeIcon, solid: QrCodeIconSolid, emoji: '📱', categoria: 'financas' },
  servidorDados: { nome: 'Servidor/Hospedagem', outline: ServerIcon, solid: ServerIconSolid, emoji: '🖥️', categoria: 'tecnologia' },
  servidorPilha: { nome: 'Data Center', outline: ServerStackIcon, solid: ServerStackIconSolid, emoji: '🗄️', categoria: 'tecnologia' },
  bancoDeDados: { nome: 'Banco de Dados', outline: CircleStackIcon, solid: CircleStackIconSolid, emoji: '🗃️', categoria: 'tecnologia' },
  chipProcessador: { nome: 'Hardware/Peças', outline: CpuChipIcon, solid: CpuChipIconSolid, emoji: '💾', categoria: 'tecnologia' },
  janelaApp: { nome: 'Software/Aplicativo', outline: WindowIcon, solid: WindowIconSolid, emoji: '🪟', categoria: 'tecnologia' },
  nuvemBaixar: { nome: 'Download/Backup', outline: CloudArrowDownIcon, solid: CloudArrowDownIconSolid, emoji: '☁️', categoria: 'tecnologia' },
  nuvemEnviar: { nome: 'Upload/Sincronização', outline: CloudArrowUpIcon, solid: CloudArrowUpIconSolid, emoji: '🔼', categoria: 'tecnologia' },
  sinalWifi: { nome: 'Sinal/Cobertura', outline: SignalIcon, solid: SignalIconSolid, emoji: '📡', categoria: 'tecnologia' },
  semSinal: { nome: 'Sem Sinal', outline: SignalSlashIcon, solid: SignalSlashIconSolid, emoji: '📵', categoria: 'tecnologia' },
  bateriaCheia: { nome: 'Bateria/Energia', outline: Battery100Icon, solid: Battery100IconSolid, emoji: '🔋', categoria: 'tecnologia' },
  bateriaMedia: { nome: 'Bateria Média', outline: Battery50Icon, solid: Battery50IconSolid, emoji: '🔋', categoria: 'tecnologia' },
  bateriaVazia: { nome: 'Bateria Baixa', outline: Battery0Icon, solid: Battery0IconSolid, emoji: '🪫', categoria: 'tecnologia' },
  sinalRadio: { nome: 'Transmissão/Rádio', outline: RssIcon, solid: RssIconSolid, emoji: '📡', categoria: 'tecnologia' },
  bugManutencao: { nome: 'Suporte Técnico', outline: BugAntIcon, solid: BugAntIconSolid, emoji: '🐛', categoria: 'tecnologia' },
  calendario: { nome: 'Calendário/Vencimento', outline: CalendarIcon, solid: CalendarIconSolid, emoji: '📅', categoria: 'simbolos' },
  calendarioDias: { nome: 'Agenda de Dias', outline: CalendarDaysIcon, solid: CalendarDaysIconSolid, emoji: '🗓️', categoria: 'simbolos' },
  calendarioIntervalo: { nome: 'Período/Intervalo', outline: CalendarDateRangeIcon, solid: CalendarDateRangeIconSolid, emoji: '📆', categoria: 'simbolos' },
  relogio: { nome: 'Horário/Prazo', outline: ClockIcon, solid: ClockIconSolid, emoji: '⏰', categoria: 'simbolos' },
  sinoAlerta: { nome: 'Alerta/Lembrete', outline: BellAlertIcon, solid: BellAlertIconSolid, emoji: '🔔', categoria: 'simbolos' },
  sinoSilenciado: { nome: 'Notificação Desligada', outline: BellSlashIcon, solid: BellSlashIconSolid, emoji: '🔕', categoria: 'simbolos' },
  sinoSoneca: { nome: 'Lembrete Adiado', outline: BellSnoozeIcon, solid: BellSnoozeIconSolid, emoji: '⏲️', categoria: 'simbolos' },
  balaoConversa: { nome: 'Conversa/Mensagem', outline: ChatBubbleLeftIcon, solid: ChatBubbleLeftIconSolid, emoji: '💬', categoria: 'documentos' },
  balaoTexto: { nome: 'Mensagem de Texto', outline: ChatBubbleBottomCenterTextIcon, solid: ChatBubbleBottomCenterTextIconSolid, emoji: '💬', categoria: 'documentos' },
  balaoCentro: { nome: 'Comentário', outline: ChatBubbleBottomCenterIcon, solid: ChatBubbleBottomCenterIconSolid, emoji: '🗨️', categoria: 'documentos' },
  balaoOval: { nome: 'Bate-papo', outline: ChatBubbleOvalLeftIcon, solid: ChatBubbleOvalLeftIconSolid, emoji: '💭', categoria: 'documentos' },
  balaoOvalPontos: { nome: 'Digitando…', outline: ChatBubbleOvalLeftEllipsisIcon, solid: ChatBubbleOvalLeftEllipsisIconSolid, emoji: '💭', categoria: 'documentos' },
  balaoPontos: { nome: 'Aguardando Resposta', outline: ChatBubbleLeftEllipsisIcon, solid: ChatBubbleLeftEllipsisIconSolid, emoji: '💬', categoria: 'documentos' },
  arroba: { nome: 'E-mail/Usuário', outline: AtSymbolIcon, solid: AtSymbolIconSolid, emoji: '📧', categoria: 'documentos' },
  envelopeAberto: { nome: 'E-mail Lido', outline: EnvelopeOpenIcon, solid: EnvelopeOpenIconSolid, emoji: '📬', categoria: 'documentos' },
  compartilhar: { nome: 'Compartilhar', outline: ShareIcon, solid: ShareIconSolid, emoji: '📤', categoria: 'simbolos' },
  usuario: { nome: 'Usuário/Perfil', outline: UserIcon, solid: UserIconSolid, emoji: '🧑', categoria: 'pessoas' },
  adicionarUsuario: { nome: 'Novo Contato', outline: UserPlusIcon, solid: UserPlusIconSolid, emoji: '👤', categoria: 'pessoas' },
  removerUsuario: { nome: 'Remover Contato', outline: UserMinusIcon, solid: UserMinusIconSolid, emoji: '🚫', categoria: 'pessoas' },
  digitalBiometria: { nome: 'Biometria', outline: FingerPrintIcon, solid: FingerPrintIconSolid, emoji: '👆', categoria: 'seguranca' },
  carinhaTriste: { nome: 'Gasto Ruim/Imprevisto', outline: FaceFrownIcon, solid: FaceFrownIconSolid, emoji: '😟', categoria: 'pessoas' },
  polegarBaixo: { nome: 'Reprovado/Cancelado', outline: HandThumbDownIcon, solid: HandThumbDownIconSolid, emoji: '👎', categoria: 'simbolos' },
  pincel: { nome: 'Arte/Pintura', outline: PaintBrushIcon, solid: PaintBrushIconSolid, emoji: '🖌️', categoria: 'lazer' },
  presenteTopo: { nome: 'Presente Especial', outline: GiftTopIcon, solid: GiftTopIconSolid, emoji: '🎀', categoria: 'compras' },
  gifAnimado: { nome: 'Mídia/GIF', outline: GifIcon, solid: GifIconSolid, emoji: '🎞️', categoria: 'lazer' },
  marcador: { nome: 'Favorito/Salvo', outline: BookmarkIcon, solid: BookmarkIconSolid, emoji: '🔖', categoria: 'simbolos' },
  marcadorRemovido: { nome: 'Removido dos Favoritos', outline: BookmarkSlashIcon, solid: BookmarkSlashIconSolid, emoji: '🏷️', categoria: 'simbolos' },
  marcadorQuadrado: { nome: 'Coleção Salva', outline: BookmarkSquareIcon, solid: BookmarkSquareIconSolid, emoji: '📌', categoria: 'simbolos' },
  globoAsia: { nome: 'Ásia/Oceania', outline: GlobeAsiaAustraliaIcon, solid: GlobeAsiaAustraliaIconSolid, emoji: '🌏', categoria: 'lazer' },
  globoEuropa: { nome: 'Europa/África', outline: GlobeEuropeAfricaIcon, solid: GlobeEuropeAfricaIconSolid, emoji: '🌍', categoria: 'lazer' },
  hashtag: { nome: 'Tag/Categoria', outline: HashtagIcon, solid: HashtagIconSolid, emoji: '#️⃣', categoria: 'simbolos' },
  bandeiraMeta: { nome: 'Marco/Conquista', outline: CheckBadgeIcon, solid: CheckBadgeIconSolid, emoji: '🏅', categoria: 'financas' },
  exclamacaoCirculo: { nome: 'Atenção', outline: ExclamationCircleIcon, solid: ExclamationCircleIconSolid, emoji: '❗', categoria: 'simbolos' },
  exclamacaoTriangulo: { nome: 'Alerta Importante', outline: ExclamationTriangleIcon, solid: ExclamationTriangleIconSolid, emoji: '⚠️', categoria: 'simbolos' },
  infoCirculo: { nome: 'Informação', outline: InformationCircleIcon, solid: InformationCircleIconSolid, emoji: 'ℹ️', categoria: 'simbolos' },
  perguntaCirculo: { nome: 'Dúvida/Suporte', outline: QuestionMarkCircleIcon, solid: QuestionMarkCircleIconSolid, emoji: '❓', categoria: 'simbolos' },
  escudoAlerta: { nome: 'Risco/Alerta de Segurança', outline: ShieldExclamationIcon, solid: ShieldExclamationIconSolid, emoji: '🛡️', categoria: 'seguranca' },
  olhoAberto: { nome: 'Visível/Transparência', outline: EyeIcon, solid: EyeIconSolid, emoji: '👁️', categoria: 'seguranca' },
  olhoFechado: { nome: 'Oculto/Privado', outline: EyeSlashIcon, solid: EyeSlashIconSolid, emoji: '🙈', categoria: 'seguranca' },
  cadeadoAberto: { nome: 'Acesso Liberado', outline: LockOpenIcon, solid: LockOpenIconSolid, emoji: '🔓', categoria: 'seguranca' },
  semSimbolo: { nome: 'Bloqueado/Cancelado', outline: NoSymbolIcon, solid: NoSymbolIconSolid, emoji: '🚫', categoria: 'simbolos' },
  checkCirculo: { nome: 'Confirmado/Pago', outline: CheckCircleIcon, solid: CheckCircleIconSolid, emoji: '✅', categoria: 'simbolos' },
  check: { nome: 'Concluído', outline: CheckIcon, solid: CheckIconSolid, emoji: '✔️', categoria: 'simbolos' },
  xCirculo: { nome: 'Cancelado/Recusado', outline: XCircleIcon, solid: XCircleIconSolid, emoji: '❌', categoria: 'simbolos' },
  lixeira: { nome: 'Excluir/Descartar', outline: TrashIcon, solid: TrashIconSolid, emoji: '🗑️', categoria: 'simbolos' },
  funil: { nome: 'Filtro/Triagem', outline: FunnelIcon, solid: FunnelIconSolid, emoji: '🔽', categoria: 'simbolos' },
  lupa: { nome: 'Buscar/Pesquisar', outline: MagnifyingGlassIcon, solid: MagnifyingGlassIconSolid, emoji: '🔍', categoria: 'simbolos' },
  lupaMais: { nome: 'Ampliar Detalhes', outline: MagnifyingGlassPlusIcon, solid: MagnifyingGlassPlusIconSolid, emoji: '🔍', categoria: 'simbolos' },
  lupaMenos: { nome: 'Reduzir Detalhes', outline: MagnifyingGlassMinusIcon, solid: MagnifyingGlassMinusIconSolid, emoji: '🔎', categoria: 'simbolos' },
  lupaCirculo: { nome: 'Investigar/Auditoria', outline: MagnifyingGlassCircleIcon, solid: MagnifyingGlassCircleIconSolid, emoji: '🔍', categoria: 'simbolos' },
  pausaCirculo: { nome: 'Pausado/Suspenso', outline: PauseCircleIcon, solid: PauseCircleIconSolid, emoji: '⏸️', categoria: 'simbolos' },
  pausa: { nome: 'Pausar Recorrência', outline: PauseIcon, solid: PauseIconSolid, emoji: '⏸️', categoria: 'simbolos' },
  playCirculo: { nome: 'Ativo/Em Andamento', outline: PlayCircleIcon, solid: PlayCircleIconSolid, emoji: '▶️', categoria: 'simbolos' },
  play: { nome: 'Iniciar', outline: PlayIcon, solid: PlayIconSolid, emoji: '▶️', categoria: 'simbolos' },
  playPausa: { nome: 'Alternar Status', outline: PlayPauseIcon, solid: PlayPauseIconSolid, emoji: '⏯️', categoria: 'simbolos' },
  parar: { nome: 'Encerrado', outline: StopIcon, solid: StopIconSolid, emoji: '⏹️', categoria: 'simbolos' },
  pararCirculo: { nome: 'Encerrar Assinatura', outline: StopCircleIcon, solid: StopCircleIconSolid, emoji: '⏹️', categoria: 'simbolos' },
  avancar: { nome: 'Próxima Parcela', outline: ForwardIcon, solid: ForwardIconSolid, emoji: '⏩', categoria: 'simbolos' },
  voltar: { nome: 'Parcela Anterior', outline: BackwardIcon, solid: BackwardIconSolid, emoji: '⏪', categoria: 'simbolos' },
  apagarTexto: { nome: 'Correção/Estorno', outline: BackspaceIcon, solid: BackspaceIconSolid, emoji: '⌫', categoria: 'simbolos' },
  energiaDesligada: { nome: 'Fora do Ar/Inativo', outline: PowerIcon, solid: PowerIconSolid, emoji: '🔌', categoria: 'moradia' },
  lampadaDesligada: { nome: 'Economia de Energia', outline: BoltSlashIcon, solid: BoltSlashIconSolid, emoji: '🪫', categoria: 'moradia' },
  pastaMais: { nome: 'Nova Pasta', outline: FolderPlusIcon, solid: FolderPlusIconSolid, emoji: '📁', categoria: 'documentos' },
  pastaMenos: { nome: 'Remover da Pasta', outline: FolderMinusIcon, solid: FolderMinusIconSolid, emoji: '📂', categoria: 'documentos' },
  pastaAberta: { nome: 'Pasta Aberta', outline: FolderOpenIcon, solid: FolderOpenIconSolid, emoji: '🗂️', categoria: 'documentos' },
  pastaBaixar: { nome: 'Baixar Arquivos', outline: FolderArrowDownIcon, solid: FolderArrowDownIconSolid, emoji: '📥', categoria: 'documentos' },
  caixaEntradaBaixar: { nome: 'Recebidos/Entrada', outline: InboxArrowDownIcon, solid: InboxArrowDownIconSolid, emoji: '📥', categoria: 'documentos' },
  caixaEntradaPilha: { nome: 'Pendências Acumuladas', outline: InboxStackIcon, solid: InboxStackIconSolid, emoji: '📬', categoria: 'documentos' },
  arquivoMorto: { nome: 'Arquivo Morto', outline: ArchiveBoxArrowDownIcon, solid: ArchiveBoxArrowDownIconSolid, emoji: '📦', categoria: 'documentos' },
  arquivoRemovido: { nome: 'Item Removido', outline: ArchiveBoxXMarkIcon, solid: ArchiveBoxXMarkIconSolid, emoji: '📦', categoria: 'documentos' },
  setaCima: { nome: 'Entrada/Recebimento', outline: ArrowUpIcon, solid: ArrowUpIconSolid, emoji: '⬆️', categoria: 'financas' },
  setaBaixo: { nome: 'Saída/Pagamento', outline: ArrowDownIcon, solid: ArrowDownIconSolid, emoji: '⬇️', categoria: 'financas' },
  setaEsquerda: { nome: 'Anterior', outline: ArrowLeftIcon, solid: ArrowLeftIconSolid, emoji: '⬅️', categoria: 'simbolos' },
  setaDireita: { nome: 'Próximo', outline: ArrowRightIcon, solid: ArrowRightIconSolid, emoji: '➡️', categoria: 'simbolos' },
  setaCimaCirculo: { nome: 'Aporte/Depósito', outline: ArrowUpCircleIcon, solid: ArrowUpCircleIconSolid, emoji: '🔼', categoria: 'financas' },
  setaBaixoCirculo: { nome: 'Resgate/Saque', outline: ArrowDownCircleIcon, solid: ArrowDownCircleIconSolid, emoji: '🔽', categoria: 'financas' },
  setaEsquerdaCirculo: { nome: 'Estorno Recebido', outline: ArrowLeftCircleIcon, solid: ArrowLeftCircleIconSolid, emoji: '↩️', categoria: 'financas' },
  setaDireitaCirculo: { nome: 'Envio Confirmado', outline: ArrowRightCircleIcon, solid: ArrowRightCircleIconSolid, emoji: '↪️', categoria: 'financas' },
  setaDiagonalCima: { nome: 'Saída Externa', outline: ArrowTopRightOnSquareIcon, solid: ArrowTopRightOnSquareIconSolid, emoji: '↗️', categoria: 'simbolos' },
  exportar: { nome: 'Exportar Dados', outline: ArrowUpOnSquareIcon, solid: ArrowUpOnSquareIconSolid, emoji: '📤', categoria: 'simbolos' },
  exportarPilha: { nome: 'Exportar em Lote', outline: ArrowUpOnSquareStackIcon, solid: ArrowUpOnSquareStackIconSolid, emoji: '📤', categoria: 'simbolos' },
  importar: { nome: 'Importar Extrato', outline: ArrowDownOnSquareIcon, solid: ArrowDownOnSquareIconSolid, emoji: '📥', categoria: 'simbolos' },
  importarPilha: { nome: 'Importar em Lote', outline: ArrowDownOnSquareStackIcon, solid: ArrowDownOnSquareStackIconSolid, emoji: '📥', categoria: 'simbolos' },
  baixarTray: { nome: 'Baixar Comprovante', outline: ArrowDownTrayIcon, solid: ArrowDownTrayIconSolid, emoji: '📥', categoria: 'financas' },
  enviarTray: { nome: 'Enviar Comprovante', outline: ArrowUpTrayIcon, solid: ArrowUpTrayIconSolid, emoji: '📤', categoria: 'financas' },
  desfazer: { nome: 'Desfazer/Estornar', outline: ArrowUturnLeftIcon, solid: ArrowUturnLeftIconSolid, emoji: '↩️', categoria: 'financas' },
  refazer: { nome: 'Refazer', outline: ArrowUturnRightIcon, solid: ArrowUturnRightIconSolid, emoji: '↪️', categoria: 'simbolos' },
  reverterCima: { nome: 'Reverter Lançamento', outline: ArrowUturnUpIcon, solid: ArrowUturnUpIconSolid, emoji: '🔄', categoria: 'financas' },
  reverterBaixo: { nome: 'Devolução', outline: ArrowUturnDownIcon, solid: ArrowUturnDownIconSolid, emoji: '🔄', categoria: 'financas' },
  expandirSeta: { nome: 'Expandir Detalhe', outline: ArrowsPointingOutIcon, solid: ArrowsPointingOutIconSolid, emoji: '↔️', categoria: 'simbolos' },
  recolherSeta: { nome: 'Recolher Detalhe', outline: ArrowsPointingInIcon, solid: ArrowsPointingInIconSolid, emoji: '↕️', categoria: 'simbolos' },
  setasVertical: { nome: 'Ordenar Valores', outline: ArrowsUpDownIcon, solid: ArrowsUpDownIconSolid, emoji: '↕️', categoria: 'simbolos' },
  loginSeta: { nome: 'Entrar na Conta', outline: ArrowRightOnRectangleIcon, solid: ArrowRightOnRectangleIconSolid, emoji: '🔑', categoria: 'seguranca' },
  logoutSeta: { nome: 'Sair da Conta', outline: ArrowLeftOnRectangleIcon, solid: ArrowLeftOnRectangleIconSolid, emoji: '🚪', categoria: 'seguranca' },
  entradaInicio: { nome: 'Início de Sessão', outline: ArrowRightStartOnRectangleIcon, solid: ArrowRightStartOnRectangleIconSolid, emoji: '➡️', categoria: 'simbolos' },
  entradaFim: { nome: 'Encerrar Sessão', outline: ArrowRightEndOnRectangleIcon, solid: ArrowRightEndOnRectangleIconSolid, emoji: '⬅️', categoria: 'simbolos' },
  saidaInicio: { nome: 'Saída Iniciada', outline: ArrowLeftStartOnRectangleIcon, solid: ArrowLeftStartOnRectangleIconSolid, emoji: '↪️', categoria: 'simbolos' },
  saidaFim: { nome: 'Saída Concluída', outline: ArrowLeftEndOnRectangleIcon, solid: ArrowLeftEndOnRectangleIconSolid, emoji: '↩️', categoria: 'simbolos' },
  telefoneEntrada: { nome: 'Ligação Recebida', outline: PhoneArrowDownLeftIcon, solid: PhoneArrowDownLeftIconSolid, emoji: '📞', categoria: 'documentos' },
  telefoneSaida: { nome: 'Ligação Feita', outline: PhoneArrowUpRightIcon, solid: PhoneArrowUpRightIconSolid, emoji: '📞', categoria: 'documentos' },
  telefoneRecusado: { nome: 'Ligação Perdida', outline: PhoneXMarkIcon, solid: PhoneXMarkIconSolid, emoji: '📵', categoria: 'documentos' },
  loop: { nome: 'Recorrência em Loop', outline: ArrowPathRoundedSquareIcon, solid: ArrowPathRoundedSquareIconSolid, emoji: '🔁', categoria: 'financas' },
  ajustesHorizontais: { nome: 'Ajustes/Preferências', outline: AdjustmentsHorizontalIcon, solid: AdjustmentsHorizontalIconSolid, emoji: '🎛️', categoria: 'simbolos' },
  ajustesVerticais: { nome: 'Configuração Fina', outline: AdjustmentsVerticalIcon, solid: AdjustmentsVerticalIconSolid, emoji: '🎚️', categoria: 'simbolos' },
  setaDiagonalRecebido: { nome: 'Recebido de Fora', outline: ArrowDownLeftIcon, solid: ArrowDownLeftIconSolid, emoji: '↙️', categoria: 'financas' },
  setaDiagonalEnviado: { nome: 'Enviado para Fora', outline: ArrowDownRightIcon, solid: ArrowDownRightIconSolid, emoji: '↘️', categoria: 'financas' },
  setaDiagonalRetorno: { nome: 'Retorno/Estorno', outline: ArrowUpLeftIcon, solid: ArrowUpLeftIconSolid, emoji: '↖️', categoria: 'financas' },
  setaDiagonalExterna: { nome: 'Envio Externo', outline: ArrowUpRightIcon, solid: ArrowUpRightIconSolid, emoji: '↗️', categoria: 'simbolos' },
  sino: { nome: 'Notificação/Lembrete', outline: BellIcon, solid: BellIconSolid, emoji: '🔔', categoria: 'simbolos' },
  engrenagemDupla: { nome: 'Configuração Avançada', outline: Cog8ToothIcon, solid: Cog8ToothIconSolid, emoji: '⚙️', categoria: 'simbolos' },
  engrenagem: { nome: 'Ajuste Geral', outline: CogIcon, solid: CogIconSolid, emoji: '⚙️', categoria: 'simbolos' },
  cuboTransparente: { nome: 'Ativo Digital/Cripto', outline: CubeTransparentIcon, solid: CubeTransparentIconSolid, emoji: '🧊', categoria: 'financas' },
  linkQuebrado: { nome: 'Vínculo Desfeito', outline: LinkSlashIcon, solid: LinkSlashIconSolid, emoji: '🔗', categoria: 'tecnologia' },
  menosCirculo: { nome: 'Desconto/Redução', outline: MinusCircleIcon, solid: MinusCircleIconSolid, emoji: '➖', categoria: 'financas' },
  lapis: { nome: 'Editar/Anotação', outline: PencilIcon, solid: PencilIconSolid, emoji: '✏️', categoria: 'simbolos' },
  semSom: { nome: 'Sem Som/Mudo', outline: SpeakerXMarkIcon, solid: SpeakerXMarkIconSolid, emoji: '🔇', categoria: 'tecnologia' },
  chamadaEncerrada: { nome: 'Chamada Encerrada', outline: VideoCameraSlashIcon, solid: VideoCameraSlashIconSolid, emoji: '📵', categoria: 'tecnologia' },
  faturaEuro: { nome: 'Fatura em Euro', outline: DocumentCurrencyEuroIcon, solid: DocumentCurrencyEuroIconSolid, emoji: '📄', categoria: 'financas' },
  faturaLibra: { nome: 'Fatura em Libra', outline: DocumentCurrencyPoundIcon, solid: DocumentCurrencyPoundIconSolid, emoji: '📄', categoria: 'financas' },
  faturaIene: { nome: 'Fatura em Iene', outline: DocumentCurrencyYenIcon, solid: DocumentCurrencyYenIconSolid, emoji: '📄', categoria: 'financas' },
  faturaRupia: { nome: 'Fatura em Rupia', outline: DocumentCurrencyRupeeIcon, solid: DocumentCurrencyRupeeIconSolid, emoji: '📄', categoria: 'financas' },
  faturaOutraMoeda: { nome: 'Fatura em Outra Moeda', outline: DocumentCurrencyBangladeshiIcon, solid: DocumentCurrencyBangladeshiIconSolid, emoji: '📄', categoria: 'financas' },
  altaForte: { nome: 'Alta Acentuada', outline: ChevronDoubleUpIcon, solid: ChevronDoubleUpIconSolid, emoji: '⏫', categoria: 'financas' },
  quedaForte: { nome: 'Queda Acentuada', outline: ChevronDoubleDownIcon, solid: ChevronDoubleDownIconSolid, emoji: '⏬', categoria: 'financas' },
  altaSimples: { nome: 'Aumento', outline: ChevronUpIcon, solid: ChevronUpIconSolid, emoji: '🔼', categoria: 'financas' },
  quedaSimples: { nome: 'Redução', outline: ChevronDownIcon, solid: ChevronDownIconSolid, emoji: '🔽', categoria: 'financas' },
  menuCategorias: { nome: 'Menu/Categorias', outline: Bars3Icon, solid: Bars3IconSolid, emoji: '☰', categoria: 'simbolos' },
  listaItens: { nome: 'Lista de Itens', outline: ListBulletIcon, solid: ListBulletIconSolid, emoji: '📋', categoria: 'simbolos' },
  listaNumerada: { nome: 'Lista Numerada', outline: NumberedListIcon, solid: NumberedListIconSolid, emoji: '🔢', categoria: 'simbolos' },
  planilha: { nome: 'Planilha', outline: TableCellsIcon, solid: TableCellsIconSolid, emoji: '📊', categoria: 'financas' },
  comparativo: { nome: 'Comparativo', outline: ViewColumnsIcon, solid: ViewColumnsIconSolid, emoji: '📊', categoria: 'financas' },
  novaCategoria: { nome: 'Nova Categoria', outline: SquaresPlusIcon, solid: SquaresPlusIconSolid, emoji: '➕', categoria: 'simbolos' },
  pilhaDocumentos: { nome: 'Pilha de Documentos', outline: RectangleStackIcon, solid: RectangleStackIconSolid, emoji: '🗃️', categoria: 'documentos' },
  camadasHistorico: { nome: 'Camadas/Histórico', outline: Square3Stack3DIcon, solid: Square3Stack3DIconSolid, emoji: '🗂️', categoria: 'documentos' },
  tecnologiaCodigo: { nome: 'Tecnologia/TI', outline: CodeBracketIcon, solid: CodeBracketIconSolid, emoji: '💻', categoria: 'tecnologia' },
  terminalAutomacao: { nome: 'Automação', outline: CommandLineIcon, solid: CommandLineIconSolid, emoji: '⌨️', categoria: 'tecnologia' },
  formulaCalculo: { nome: 'Fórmula/Cálculo', outline: VariableIcon, solid: VariableIconSolid, emoji: '🧮', categoria: 'financas' },

  // --- +53 icones (01/09/2026, mesmo dia -- teto real da biblioteca
  // Heroicons: 271 + 53 = 324, ver comentário na importação acima) ---
  setaLongaBaixo: { nome: 'Seta Longa para Baixo', outline: ArrowLongDownIcon, solid: ArrowLongDownIconSolid, emoji: '⬇️', categoria: 'simbolos' },
  setaLongaEsquerda: { nome: 'Seta Longa para Esquerda', outline: ArrowLongLeftIcon, solid: ArrowLongLeftIconSolid, emoji: '⬅️', categoria: 'simbolos' },
  setaLongaDireita: { nome: 'Seta Longa para Direita', outline: ArrowLongRightIcon, solid: ArrowLongRightIconSolid, emoji: '➡️', categoria: 'simbolos' },
  setaLongaCima: { nome: 'Seta Longa para Cima', outline: ArrowLongUpIcon, solid: ArrowLongUpIconSolid, emoji: '⬆️', categoria: 'simbolos' },
  setaPequenaBaixo: { nome: 'Seta Pequena para Baixo', outline: ArrowSmallDownIcon, solid: ArrowSmallDownIconSolid, emoji: '↓', categoria: 'simbolos' },
  setaPequenaEsquerda: { nome: 'Seta Pequena para Esquerda', outline: ArrowSmallLeftIcon, solid: ArrowSmallLeftIconSolid, emoji: '←', categoria: 'simbolos' },
  setaPequenaDireita: { nome: 'Seta Pequena para Direita', outline: ArrowSmallRightIcon, solid: ArrowSmallRightIconSolid, emoji: '→', categoria: 'simbolos' },
  setaPequenaCima: { nome: 'Seta Pequena para Cima', outline: ArrowSmallUpIcon, solid: ArrowSmallUpIconSolid, emoji: '↑', categoria: 'simbolos' },
  setaCurvaBaixoEsquerda: { nome: 'Curva para Baixo-Esquerda', outline: ArrowTurnDownLeftIcon, solid: ArrowTurnDownLeftIconSolid, emoji: '↙️', categoria: 'simbolos' },
  setaCurvaBaixoDireita: { nome: 'Curva para Baixo-Direita', outline: ArrowTurnDownRightIcon, solid: ArrowTurnDownRightIconSolid, emoji: '↘️', categoria: 'simbolos' },
  setaCurvaEsquerdaBaixo: { nome: 'Curva Esquerda para Baixo', outline: ArrowTurnLeftDownIcon, solid: ArrowTurnLeftDownIconSolid, emoji: '↩️', categoria: 'simbolos' },
  setaCurvaEsquerdaCima: { nome: 'Curva Esquerda para Cima', outline: ArrowTurnLeftUpIcon, solid: ArrowTurnLeftUpIconSolid, emoji: '↖️', categoria: 'simbolos' },
  setaCurvaDireitaBaixo: { nome: 'Curva Direita para Baixo', outline: ArrowTurnRightDownIcon, solid: ArrowTurnRightDownIconSolid, emoji: '↪️', categoria: 'simbolos' },
  setaCurvaDireitaCima: { nome: 'Curva Direita para Cima', outline: ArrowTurnRightUpIcon, solid: ArrowTurnRightUpIconSolid, emoji: '↗️', categoria: 'simbolos' },
  setaCurvaCimaEsquerda: { nome: 'Curva para Cima-Esquerda', outline: ArrowTurnUpLeftIcon, solid: ArrowTurnUpLeftIconSolid, emoji: '↖️', categoria: 'simbolos' },
  setaCurvaCimaDireita: { nome: 'Curva para Cima-Direita', outline: ArrowTurnUpRightIcon, solid: ArrowTurnUpRightIconSolid, emoji: '↗️', categoria: 'simbolos' },
  menuDuasLinhas: { nome: 'Menu de Duas Linhas', outline: Bars2Icon, solid: Bars2IconSolid, emoji: '☰', categoria: 'simbolos' },
  menuAlinhadoEsquerda: { nome: 'Menu Alinhado à Esquerda', outline: Bars3BottomLeftIcon, solid: Bars3BottomLeftIconSolid, emoji: '☰', categoria: 'simbolos' },
  menuAlinhadoDireita: { nome: 'Menu Alinhado à Direita', outline: Bars3BottomRightIcon, solid: Bars3BottomRightIconSolid, emoji: '☰', categoria: 'simbolos' },
  menuCentralizado: { nome: 'Menu Centralizado', outline: Bars3CenterLeftIcon, solid: Bars3CenterLeftIconSolid, emoji: '☰', categoria: 'simbolos' },
  menuQuatroLinhas: { nome: 'Menu de Quatro Linhas', outline: Bars4Icon, solid: Bars4IconSolid, emoji: '☰', categoria: 'simbolos' },
  ordenarDecrescente: { nome: 'Ordenar Decrescente', outline: BarsArrowDownIcon, solid: BarsArrowDownIconSolid, emoji: '⬇️', categoria: 'simbolos' },
  ordenarCrescente: { nome: 'Ordenar Crescente', outline: BarsArrowUpIcon, solid: BarsArrowUpIconSolid, emoji: '⬆️', categoria: 'simbolos' },
  textoNegrito: { nome: 'Texto em Negrito', outline: BoldIcon, solid: BoldIconSolid, emoji: '🅱️', categoria: 'documentos' },
  setaDuplaEsquerda: { nome: 'Seta Dupla à Esquerda', outline: ChevronDoubleLeftIcon, solid: ChevronDoubleLeftIconSolid, emoji: '⏪', categoria: 'simbolos' },
  setaDuplaDireita: { nome: 'Seta Dupla à Direita', outline: ChevronDoubleRightIcon, solid: ChevronDoubleRightIconSolid, emoji: '⏩', categoria: 'simbolos' },
  paginaAnterior: { nome: 'Voltar Página', outline: ChevronLeftIcon, solid: ChevronLeftIconSolid, emoji: '◀️', categoria: 'simbolos' },
  paginaSeguinte: { nome: 'Avançar Página', outline: ChevronRightIcon, solid: ChevronRightIconSolid, emoji: '▶️', categoria: 'simbolos' },
  selecionarOpcao: { nome: 'Selecionar Opção', outline: ChevronUpDownIcon, solid: ChevronUpDownIconSolid, emoji: '↕️', categoria: 'simbolos' },
  blocoCodigo: { nome: 'Bloco de Código', outline: CodeBracketSquareIcon, solid: CodeBracketSquareIconSolid, emoji: '🔣', categoria: 'tecnologia' },
  cursorClique: { nome: 'Cursor/Clique', outline: CursorArrowRaysIcon, solid: CursorArrowRaysIconSolid, emoji: '🖱️', categoria: 'tecnologia' },
  cursorInteracao: { nome: 'Interação/Toque', outline: CursorArrowRippleIcon, solid: CursorArrowRippleIconSolid, emoji: '👆', categoria: 'tecnologia' },
  dividirValor: { nome: 'Dividir/Ratear', outline: DivideIcon, solid: DivideIconSolid, emoji: '➗', categoria: 'financas' },
  maisOpcoesCirculo: { nome: 'Mais Opções (círculo)', outline: EllipsisHorizontalCircleIcon, solid: EllipsisHorizontalCircleIconSolid, emoji: '➕', categoria: 'simbolos' },
  maisOpcoes: { nome: 'Mais Opções', outline: EllipsisHorizontalIcon, solid: EllipsisHorizontalIconSolid, emoji: '•••', categoria: 'simbolos' },
  maisOpcoesVertical: { nome: 'Mais Opções (vertical)', outline: EllipsisVerticalIcon, solid: EllipsisVerticalIconSolid, emoji: '⋮', categoria: 'simbolos' },
  igualarValores: { nome: 'Igualar/Balancear', outline: EqualsIcon, solid: EqualsIconSolid, emoji: '🟰', categoria: 'financas' },
  contaGotasCor: { nome: 'Conta-gotas/Cor', outline: EyeDropperIcon, solid: EyeDropperIconSolid, emoji: '🎨', categoria: 'lazer' },
  tituloGrande: { nome: 'Título Grande', outline: H1Icon, solid: H1IconSolid, emoji: '🔠', categoria: 'documentos' },
  tituloMedio: { nome: 'Título Médio', outline: H2Icon, solid: H2IconSolid, emoji: '🔠', categoria: 'documentos' },
  tituloPequeno: { nome: 'Título Pequeno', outline: H3Icon, solid: H3IconSolid, emoji: '🔠', categoria: 'documentos' },
  textoItalico: { nome: 'Texto em Itálico', outline: ItalicIcon, solid: ItalicIconSolid, emoji: '✒️', categoria: 'documentos' },
  subtrairValor: { nome: 'Subtrair Valor', outline: MinusIcon, solid: MinusIconSolid, emoji: '➖', categoria: 'financas' },
  reduzirPequeno: { nome: 'Reduzir (pequeno)', outline: MinusSmallIcon, solid: MinusSmallIconSolid, emoji: '➖', categoria: 'financas' },
  adicionarValor: { nome: 'Adicionar Valor', outline: PlusIcon, solid: PlusIconSolid, emoji: '➕', categoria: 'financas' },
  aumentarPequeno: { nome: 'Aumentar (pequeno)', outline: PlusSmallIcon, solid: PlusSmallIconSolid, emoji: '➕', categoria: 'financas' },
  agruparItens: { nome: 'Agrupar Itens', outline: RectangleGroupIcon, solid: RectangleGroupIconSolid, emoji: '🗂️', categoria: 'simbolos' },
  barraDivisoria: { nome: 'Dividir/Excluir', outline: SlashIcon, solid: SlashIconSolid, emoji: '🚫', categoria: 'simbolos' },
  duplicarItem: { nome: 'Duplicar Item', outline: Square2StackIcon, solid: Square2StackIconSolid, emoji: '📑', categoria: 'documentos' },
  textoTachado: { nome: 'Texto Tachado/Cancelado', outline: StrikethroughIcon, solid: StrikethroughIconSolid, emoji: '❌', categoria: 'documentos' },
  textoSublinhado: { nome: 'Texto Sublinhado', outline: UnderlineIcon, solid: UnderlineIconSolid, emoji: '✏️', categoria: 'documentos' },
  focoMira: { nome: 'Foco/Mira', outline: ViewfinderCircleIcon, solid: ViewfinderCircleIconSolid, emoji: '🎯', categoria: 'tecnologia' },
  fecharCancelar: { nome: 'Fechar/Cancelar', outline: XMarkIcon, solid: XMarkIconSolid, emoji: '✖️', categoria: 'simbolos' },
}

export const LISTA_ICONES: { id: string; nome: string; categoria: string; sinonimos?: string[] }[] = Object.entries(
  ICONES,
).map(([id, def]) => ({
  id,
  nome: def.nome,
  categoria: def.categoria,
  sinonimos: def.sinonimos,
}))

// Sub-abas do seletor de ícone (01/09/2026, pedido do Rafael: "subdivida em
// categorias eles (sub-abas)"). São "gavetas" de organização da grade de
// ~324 ícones — não confundir com as categorias financeiras cadastradas
// pelo usuário. "Todos" (sem id de categoria real) é tratado à parte no
// SeletorIcone.tsx como a aba inicial que mostra tudo.
export const CATEGORIAS_ICONE: { id: string; rotulo: string }[] = [
  { id: 'moradia', rotulo: 'Casa/Moradia' },
  { id: 'transporte', rotulo: 'Transporte' },
  { id: 'alimentacao', rotulo: 'Alimentação' },
  { id: 'compras', rotulo: 'Compras' },
  { id: 'saude', rotulo: 'Saúde' },
  { id: 'educacao', rotulo: 'Educação' },
  { id: 'lazer', rotulo: 'Lazer' },
  { id: 'financas', rotulo: 'Finanças' },
  { id: 'trabalho', rotulo: 'Trabalho' },
  { id: 'tecnologia', rotulo: 'Tecnologia' },
  { id: 'documentos', rotulo: 'Documentos' },
  { id: 'pessoas', rotulo: 'Pessoas' },
  { id: 'seguranca', rotulo: 'Segurança' },
  { id: 'simbolos', rotulo: 'Símbolos' },
]

// Paleta limitada e tradicional (pedido do Rafael: "tipo Paleta Limitada")
// pros 2 estilos monocromáticos — escolher uma dessas cores muda todos os
// ícones da grade na hora, já que todo `<Icone>` visível recebe a mesma
// `cor` via prop/estado.
export const PALETA_CORES: string[] = [
  '#ef4444', // vermelho
  '#f97316', // laranja
  '#f59e0b', // âmbar
  '#eab308', // amarelo
  '#22c55e', // verde
  '#14b8a6', // verde-azulado
  '#06b6d4', // ciano
  '#3b82f6', // azul
  '#6366f1', // índigo
  '#a855f7', // roxo
  '#ec4899', // rosa
  '#64748b', // cinza-azulado
]

export function Icone({
  id,
  estilo = 'colorido',
  cor,
  tamanho = 20,
  style,
}: {
  id?: string
  estilo?: EstiloIcone
  cor?: string
  tamanho?: number | string
  style?: CSSProperties
}) {
  // "Sem ícone" (01/09/2026, rodada seguinte) — sentinela explícita, diferente
  // de `id` ausente/undefined (que sempre caiu no ícone genérico "outros",
  // pra não quebrar categoria/grupo cadastrado antes desta opção existir).
  // "nenhum" é uma ESCOLHA ativa de não mostrar ícone nenhum — só alcançável
  // pelo botão "Sem ícone" no `SeletorIcone`. Centralizado aqui (em vez de só
  // nos call sites) pra garantir que nenhum lugar novo esqueça de tratar.
  if (id === 'nenhum') return null

  const def = (id && ICONES[id]) || ICONES.outros

  if (estilo === 'colorido') {
    // "3D colorido" — emoji nativo, biblioteca própria e já colorida (sem
    // opção de trocar cor, igual antes).
    return (
      <span
        role="img"
        aria-label={def.nome}
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: tamanho,
          lineHeight: 1,
          flexShrink: 0,
          ...style,
        }}
      >
        {def.emoji}
      </span>
    )
  }

  const Componente = estilo === 'preenchido' ? def.solid : def.outline
  const corFinal = cor || 'var(--texto-fraco)'
  return (
    <Componente
      width={tamanho}
      height={tamanho}
      style={{ color: corFinal, flexShrink: 0, ...style }}
      aria-hidden="true"
    />
  )
}
