import { db, type Categoria, type Lancamento } from './db'
import { comIconePadraoCategoria, comIconePadraoGrupo } from './iconesPadrao'
import { GRUPO_RECEITA } from './gruposUtil'

// Categorias e metas REAIS do Rafael — extraídas da planilha
// "Metas vs Real" (Cálculos - Gastos v5, ajustes 30-08-2026), aba de trabalho
// oficial. Aceitável vem direto da coluna D daquela aba; Meta % vem da tabela
// de grupos (J4:M8). Todas começam ativas — a tela Categorias
// permite editar, inativar ou (se não tiver lançamento) excluir.
const CATEGORIAS_PADRAO: Omit<Categoria, 'id'>[] = [
  { nome: 'Casa', grupo: 'Fixo', natureza: 'Consumo', aceitavelMensal: 3250, ativa: true },
  { nome: 'CNPJ', grupo: 'Fixo', natureza: 'Consumo', aceitavelMensal: 1645, ativa: true },
  { nome: 'Mercado', grupo: 'Fixo', natureza: 'Consumo', aceitavelMensal: 1000, ativa: true },
  { nome: 'Carro - Man/Imp/Seg', grupo: 'Fixo', natureza: 'Consumo', aceitavelMensal: 950, ativa: true },
  { nome: 'Saúde - Fixo', grupo: 'Fixo', natureza: 'Consumo', aceitavelMensal: 650, ativa: true },
  { nome: 'Pets', grupo: 'Fixo', natureza: 'Consumo', aceitavelMensal: 350, ativa: true },
  { nome: 'Celular', grupo: 'Fixo', natureza: 'Consumo', aceitavelMensal: 57, ativa: true },
  { nome: 'Alimentação', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 1300, ativa: true },
  { nome: 'Compras', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 1000, ativa: true },
  { nome: 'Carro - Variável', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 1000, ativa: true },
  { nome: 'Fitness', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 800, ativa: true },
  { nome: 'Diversão e Lazer', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 700, ativa: true },
  { nome: 'Saúde - Variável', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 200, ativa: true },
  { nome: 'Família', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 203, ativa: true },
  { nome: 'Assinaturas e serviços', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 120, ativa: true },
  { nome: 'Cigarro', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 150, ativa: true },
  { nome: 'Transporte', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Juros e Taxas', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Impostos e Taxas', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Dívidas e empréstimos', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Emprestimo', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Custos', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Inesperado', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Outros', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Reembolsável', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Diferença', grupo: 'Variável', natureza: 'Consumo', aceitavelMensal: 0, ativa: true },
  { nome: 'Salário', grupo: GRUPO_RECEITA, natureza: 'Receita', aceitavelMensal: 16712, ativa: true },
  { nome: 'Reembolso', grupo: GRUPO_RECEITA, natureza: 'Receita', aceitavelMensal: 0, ativa: true },
  { nome: 'Outras receitas', grupo: GRUPO_RECEITA, natureza: 'Receita', aceitavelMensal: 0, ativa: true },
  { nome: 'Investimentos', grupo: GRUPO_RECEITA, natureza: 'Receita', aceitavelMensal: 0, ativa: true },
  { nome: '# Objetivos', grupo: 'Objetivos', natureza: 'Aporte', aceitavelMensal: 1671.2, ativa: true },
  { nome: '# Segurança', grupo: 'Segurança', natureza: 'Aporte', aceitavelMensal: 1671.2, ativa: true },
  { nome: '$ Objetivos - Metas', grupo: 'Objetivos', natureza: 'Gasto de cofrinho', aceitavelMensal: 0, ativa: true },
  { nome: '$ Segurança - Reserva', grupo: 'Segurança', natureza: 'Gasto de cofrinho', aceitavelMensal: 0, ativa: true },
  { nome: '$ Segurança - Invest', grupo: 'Segurança', natureza: 'Gasto de cofrinho', aceitavelMensal: 0, ativa: true },
  { nome: 'Transferências', grupo: 'Fixo', natureza: 'Neutro', aceitavelMensal: 0, ativa: true },
  { nome: 'Pagamento de fatura', grupo: 'Fixo', natureza: 'Pagamento de fatura', aceitavelMensal: 0, ativa: true },
]

// Lançamentos REAIS e COMPLETOS dos últimos 6 meses fechados na planilha
// (março a agosto/2026 — mês 202603 a 202608 na aba Modelagem), extraídos
// direto do arquivo "Cálculos - Gastos v5 (ajustes 30-08)". Datas absolutas
// (não remapeadas) — é histórico de verdade, pra você caminhar mês a mês
// pelas telas de Resumo e Situação usando o seletor de mês. Conferido contra
// os totais em cache da planilha (Entrou/Saiu/Resultado batendo exatamente
// em todos os 6 meses antes de semear).
interface LancamentoSemente {
  data: string // ISO yyyy-mm-dd
  descricao: string
  categoria: string
  valor: number // com sinal
  conta: 'bradesco' | 'cartao'
}

const LANCAMENTOS_SEMENTE: LancamentoSemente[] = [
  { data: '2026-03-31', descricao: 'Rentabilidade', categoria: 'Reembolso', valor: 0.02, conta: 'bradesco' },
  { data: '2026-03-31', descricao: 'Faxina', categoria: 'Casa', valor: -140.0, conta: 'bradesco' },
  { data: '2026-03-27', descricao: 'Eletrecista', categoria: 'Outros', valor: -150.0, conta: 'bradesco' },
  { data: '2026-03-26', descricao: 'Barba', categoria: 'Diversão e Lazer', valor: -70.0, conta: 'bradesco' },
  { data: '2026-03-25', descricao: 'Minoxidil', categoria: 'Fitness', valor: -77.33, conta: 'bradesco' },
  { data: '2026-03-23', descricao: 'Rentabilidade', categoria: 'Reembolso', valor: 1.06, conta: 'bradesco' },
  { data: '2026-03-23', descricao: 'Energia', categoria: 'Casa', valor: -122.46, conta: 'bradesco' },
  { data: '2026-03-21', descricao: 'Cigarro', categoria: 'Cigarro', valor: -127.5, conta: 'bradesco' },
  { data: '2026-03-20', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -268.8, conta: 'bradesco' },
  { data: '2026-03-20', descricao: 'Venda TV', categoria: 'Reembolso', valor: 250.0, conta: 'bradesco' },
  { data: '2026-03-20', descricao: 'INSS', categoria: 'CNPJ', valor: -178.31, conta: 'bradesco' },
  { data: '2026-03-20', descricao: 'Imposto CNPJ', categoria: 'CNPJ', valor: -953.34, conta: 'bradesco' },
  { data: '2026-03-18', descricao: 'Salário DSF', categoria: 'Salário', valor: 829.0, conta: 'bradesco' },
  { data: '2026-03-17', descricao: 'Paula', categoria: 'Reembolso', valor: 768.0, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -11317.34, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'Dif', categoria: 'Reembolso', valor: 1.51, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'Claro Fibra', categoria: 'Casa', valor: -73.26, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'IPVA 3/5', categoria: 'Carro - Man/Imp/Seg', valor: -595.51, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'Aluguél', categoria: 'Casa', valor: -2489.11, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'Faxina RB', categoria: 'Família', valor: -80.0, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'Contador', categoria: 'CNPJ', valor: -398.8, conta: 'bradesco' },
  { data: '2026-03-16', descricao: 'TIM', categoria: 'Celular', valor: -58.17, conta: 'bradesco' },
  { data: '2026-03-13', descricao: 'Plano de Saúde Pai e Mãe', categoria: 'Família', valor: -122.0, conta: 'bradesco' },
  { data: '2026-03-13', descricao: 'Tim Fibra', categoria: 'Casa', valor: -35.94, conta: 'bradesco' },
  { data: '2026-03-12', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-03-09', descricao: 'Venda Churrasqueira', categoria: 'Reembolso', valor: 150.0, conta: 'bradesco' },
  { data: '2026-03-09', descricao: 'Refinanciamento Carro', categoria: 'Dívidas e empréstimos', valor: -1166.05, conta: 'bradesco' },
  { data: '2026-03-09', descricao: 'Salário DSF', categoria: 'Salário', valor: 15889.0, conta: 'bradesco' },
  { data: '2026-03-05', descricao: 'Juros', categoria: 'Reembolso', valor: 0.11, conta: 'bradesco' },
  { data: '2026-03-05', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -544.08, conta: 'bradesco' },
  { data: '2026-03-04', descricao: 'Juros', categoria: 'Juros e Taxas', valor: -12.45, conta: 'bradesco' },
  { data: '2026-03-03', descricao: 'IOF', categoria: 'Juros e Taxas', valor: -11.44, conta: 'bradesco' },
  { data: '2026-03-02', descricao: 'Murilo Cinema', categoria: 'Reembolso', valor: 68.0, conta: 'bradesco' },
  { data: '2026-03-31', descricao: 'SPG TOP GRILL SOROCABA', categoria: 'Alimentação', valor: -56.98, conta: 'cartao' },
  { data: '2026-03-30', descricao: 'Dif', categoria: 'Compras', valor: -27.44, conta: 'cartao' },
  { data: '2026-03-30', descricao: 'Instal Ar Condic 99Pay  Pix 1/3', categoria: 'Compras', valor: -294.48, conta: 'cartao' },
  { data: '2026-03-30', descricao: 'QUITANDA DIVINA', categoria: 'Mercado', valor: -27.22, conta: 'cartao' },
  { data: '2026-03-30', descricao: '3 Camisas gola padre 1/2', categoria: 'Compras', valor: -82.35, conta: 'cartao' },
  { data: '2026-03-30', descricao: 'Camoseta e cueca 1/2', categoria: 'Compras', valor: -68.91, conta: 'cartao' },
  { data: '2026-03-29', descricao: 'AUTO POSTO 2400', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-03-29', descricao: 'HORSE BBQ', categoria: 'Alimentação', valor: -191.4, conta: 'cartao' },
  { data: '2026-03-28', descricao: 'CAPPTA  TOP GRILL SORO', categoria: 'Alimentação', valor: -135.96, conta: 'cartao' },
  { data: '2026-03-28', descricao: 'PAYGO RAPOSAO MATERIAI', categoria: 'Compras', valor: -7.5, conta: 'cartao' },
  { data: '2026-03-28', descricao: 'ValttatiArtsEmMdf', categoria: 'Compras', valor: -61.5, conta: 'cartao' },
  { data: '2026-03-28', descricao: 'AMERICO SHIGUEO KOSIMA', categoria: 'Alimentação', valor: -44.0, conta: 'cartao' },
  { data: '2026-03-28', descricao: 'COBASI Coleira', categoria: 'Pets', valor: -128.5, conta: 'cartao' },
  { data: '2026-03-28', descricao: 'JOAO SOUZA LEITE', categoria: 'Alimentação', valor: -30.0, conta: 'cartao' },
  { data: '2026-03-27', descricao: 'ELETROMILE', categoria: 'Compras', valor: -100.0, conta: 'cartao' },
  { data: '2026-03-27', descricao: 'IFD TOTEM RR LANCHES -', categoria: 'Alimentação', valor: -101.0, conta: 'cartao' },
  { data: '2026-03-27', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -32.1, conta: 'cartao' },
  { data: '2026-03-27', descricao: 'SulAuto Modulo ABS 5/6', categoria: 'Carro - Man/Imp/Seg', valor: -650.0, conta: 'cartao' },
  { data: '2026-03-26', descricao: 'Google Bumble Dating', categoria: 'Diversão e Lazer', valor: -99.9, conta: 'cartao' },
  { data: '2026-03-26', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -23.3, conta: 'cartao' },
  { data: '2026-03-25', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -45.16, conta: 'cartao' },
  { data: '2026-03-25', descricao: 'Quitanda', categoria: 'Mercado', valor: -11.43, conta: 'cartao' },
  { data: '2026-03-25', descricao: 'Google Organizze Fina', categoria: 'Assinaturas e serviços', valor: -199.9, conta: 'cartao' },
  { data: '2026-03-25', descricao: 'Drogaria_SP drogariasp', categoria: 'Saúde - Variável', valor: -104.34, conta: 'cartao' },
  { data: '2026-03-24', descricao: 'LOJAS G 2/2', categoria: 'Reembolsável', valor: -88.96, conta: 'cartao' },
  { data: '2026-03-23', descricao: 'RANCHO DO CUPIM SOROC', categoria: 'Alimentação', valor: -78.7, conta: 'cartao' },
  { data: '2026-03-23', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -126.7, conta: 'cartao' },
  { data: '2026-03-23', descricao: 'CachoBrasil', categoria: 'Alimentação', valor: -9.9, conta: 'cartao' },
  { data: '2026-03-23', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Saúde - Variável', valor: -48.97, conta: 'cartao' },
  { data: '2026-03-23', descricao: 'AUTO POSTO 2400', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-03-22', descricao: 'VARANDA CAMPOLIM', categoria: 'Alimentação', valor: -115.22, conta: 'cartao' },
  { data: '2026-03-22', descricao: 'MP  SORVETERIATROPICAL', categoria: 'Alimentação', valor: -22.0, conta: 'cartao' },
  { data: '2026-03-22', descricao: '58397403Marcus', categoria: 'Diversão e Lazer', valor: -18.0, conta: 'cartao' },
  { data: '2026-03-22', descricao: '58397403Marcus', categoria: 'Diversão e Lazer', valor: -18.0, conta: 'cartao' },
  { data: '2026-03-22', descricao: 'PUB SOROCABA', categoria: 'Diversão e Lazer', valor: -184.0, conta: 'cartao' },
  { data: '2026-03-22', descricao: 'Drogaria_SP drogariasa 6/6', categoria: 'Saúde - Variável', valor: -166.5, conta: 'cartao' },
  { data: '2026-03-22', descricao: 'Drogaria_SP drogariasa 6/6', categoria: 'Saúde - Variável', valor: -173.49, conta: 'cartao' },
  { data: '2026-03-21', descricao: 'VARANDA CAMPOLIM', categoria: 'Alimentação', valor: -112.97, conta: 'cartao' },
  { data: '2026-03-21', descricao: 'CATEDRAL CAFE BISTRO', categoria: 'Alimentação', valor: -18.0, conta: 'cartao' },
  { data: '2026-03-21', descricao: 'Cabo celular', categoria: 'Compras', valor: -25.0, conta: 'cartao' },
  { data: '2026-03-21', descricao: 'LABI EXAMES SA 1/3', categoria: 'Saúde - Variável', valor: -137.34, conta: 'cartao' },
  { data: '2026-03-21', descricao: 'LOJAS G 2/2', categoria: 'Compras', valor: -101.45, conta: 'cartao' },
  { data: '2026-03-20', descricao: 'Essencias', categoria: 'Compras', valor: -40.9, conta: 'cartao' },
  { data: '2026-03-20', descricao: 'SHOPEE  FUTONMAX', categoria: 'Compras', valor: -136.4, conta: 'cartao' },
  { data: '2026-03-20', descricao: 'CARREFOUR SON 237', categoria: 'Mercado', valor: -332.21, conta: 'cartao' },
  { data: '2026-03-20', descricao: 'POSTO LUSITANO', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-03-20', descricao: 'ESKALA 304 2/2', categoria: 'Compras', valor: -99.97, conta: 'cartao' },
  { data: '2026-03-19', descricao: '99', categoria: 'Compras', valor: -1.04, conta: 'cartao' },
  { data: '2026-03-19', descricao: 'SANTA TEREZA MATERIAIS', categoria: 'Compras', valor: -10.5, conta: 'cartao' },
  { data: '2026-03-19', descricao: 'Google Tinder Dating', categoria: 'Diversão e Lazer', valor: -21.99, conta: 'cartao' },
  { data: '2026-03-18', descricao: 'PG  DAISO BRASIL COMER', categoria: 'Compras', valor: -59.67, conta: 'cartao' },
  { data: '2026-03-18', descricao: 'COSTA BARROS SOLEDADE', categoria: 'Cigarro', valor: -25.5, conta: 'cartao' },
  { data: '2026-03-18', descricao: 'NUTRIFRESH COMERCIO DE', categoria: 'Alimentação', valor: -31.9, conta: 'cartao' },
  { data: '2026-03-18', descricao: 'DAISO BRASIL COMERCIO', categoria: 'Compras', valor: -77.93, conta: 'cartao' },
  { data: '2026-03-18', descricao: 'RODRIGO VINICIUS ALARC', categoria: 'Alimentação', valor: -29.88, conta: 'cartao' },
  { data: '2026-03-18', descricao: 'Ar condicionado 1/10', categoria: 'Compras', valor: -223.14, conta: 'cartao' },
  { data: '2026-03-17', descricao: 'Cigarro Conveniência', categoria: 'Cigarro', valor: -13.75, conta: 'cartao' },
  { data: '2026-03-17', descricao: 'Panicenter', categoria: 'Alimentação', valor: -32.1, conta: 'cartao' },
  { data: '2026-03-16', descricao: 'Shopee', categoria: 'Compras', valor: -63.0, conta: 'cartao' },
  { data: '2026-03-15', descricao: 'LOJAS G', categoria: 'Compras', valor: -81.97, conta: 'cartao' },
  { data: '2026-03-15', descricao: 'Japonês', categoria: 'Alimentação', valor: -154.83, conta: 'cartao' },
  { data: '2026-03-15', descricao: 'NIGHT DOG BAR', categoria: 'Alimentação', valor: -90.0, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -209.28, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'Pastel', categoria: 'Alimentação', valor: -34.0, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'DAISO BRASIL', categoria: 'Compras', valor: -24.99, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'Estacionamento', categoria: 'Carro - Variável', valor: -15.0, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'Ref', categoria: 'Alimentação', valor: -23.0, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'Açai', categoria: 'Alimentação', valor: -16.9, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'Gasolina', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-03-14', descricao: 'ESKALA 304', categoria: 'Compras', valor: -41.99, conta: 'cartao' },
  { data: '2026-03-13', descricao: 'Burger King', categoria: 'Alimentação', valor: -50.8, conta: 'cartao' },
  { data: '2026-03-13', descricao: 'SHOPEE  MILLOWSTORE 2/2', categoria: 'Reembolsável', valor: -111.93, conta: 'cartao' },
  { data: '2026-03-12', descricao: 'Emporio Carmona', categoria: 'Alimentação', valor: -65.7, conta: 'cartao' },
  { data: '2026-03-12', descricao: 'Tauste', categoria: 'Mercado', valor: -115.51, conta: 'cartao' },
  { data: '2026-03-12', descricao: 'Google Tinder Dating', categoria: 'Diversão e Lazer', valor: -21.99, conta: 'cartao' },
  { data: '2026-03-11', descricao: 'Arabe', categoria: 'Alimentação', valor: -53.27, conta: 'cartao' },
  { data: '2026-03-11', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.3, conta: 'cartao' },
  { data: '2026-03-11', descricao: 'Ajuste Seguro 1/2', categoria: 'Carro - Man/Imp/Seg', valor: -56.47, conta: 'cartao' },
  { data: '2026-03-10', descricao: 'Devolução', categoria: 'Reembolso', valor: 3.66, conta: 'cartao' },
  { data: '2026-03-10', descricao: 'SHOPEE  SHPSTECNOLOGIA 1/2', categoria: 'Compras', valor: -111.99, conta: 'cartao' },
  { data: '2026-03-10', descricao: 'Vassoura, mangueira, faca, banco 2/4', categoria: 'Reembolsável', valor: -63.16, conta: 'cartao' },
  { data: '2026-03-10', descricao: 'Mesa e Cadeiras 2/2', categoria: 'Reembolsável', valor: -583.14, conta: 'cartao' },
  { data: '2026-03-10', descricao: 'Globo Globoplay 7/12', categoria: 'Assinaturas e serviços', valor: -19.9, conta: 'cartao' },
  { data: '2026-03-09', descricao: 'ML', categoria: 'Compras', valor: -71.98, conta: 'cartao' },
  { data: '2026-03-09', descricao: 'ML', categoria: 'Compras', valor: -106.34, conta: 'cartao' },
  { data: '2026-03-09', descricao: 'Drogaria São Paulo - Testo 3/3', categoria: 'Fitness', valor: -220.45, conta: 'cartao' },
  { data: '2026-03-09', descricao: 'Wellhub Gympass BR Gym', categoria: 'Fitness', valor: -69.99, conta: 'cartao' },
  { data: '2026-03-08', descricao: 'Dif', categoria: 'Reembolso', valor: 12.57, conta: 'cartao' },
  { data: '2026-03-08', descricao: 'IOF', categoria: 'Juros e Taxas', valor: -3.66, conta: 'cartao' },
  { data: '2026-03-08', descricao: 'MANIA DE CHURRASCO PRI', categoria: 'Alimentação', valor: -76.6, conta: 'cartao' },
  { data: '2026-03-08', descricao: 'NUTTY BAVARIAN', categoria: 'Alimentação', valor: -26.0, conta: 'cartao' },
  { data: '2026-03-07', descricao: 'AUTO POSTO 2400', categoria: 'Carro - Variável', valor: -50.0, conta: 'cartao' },
  { data: '2026-03-07', descricao: 'CATEDRAL CAFE BISTRO', categoria: 'Alimentação', valor: -21.0, conta: 'cartao' },
  { data: '2026-03-07', descricao: 'Google YouTube', categoria: 'Assinaturas e serviços', valor: -26.9, conta: 'cartao' },
  { data: '2026-03-06', descricao: 'MERCADOLIVRE PERFUMER', categoria: 'Compras', valor: -62.94, conta: 'cartao' },
  { data: '2026-03-06', descricao: 'MERCADOLIVRE 3PRODUTO', categoria: 'Compras', valor: -95.41, conta: 'cartao' },
  { data: '2026-03-06', descricao: 'REST IRMAOS', categoria: 'Mercado', valor: -17.16, conta: 'cartao' },
  { data: '2026-03-06', descricao: 'SUPER SHOPPING DA UTIL', categoria: 'Compras', valor: -54.98, conta: 'cartao' },
  { data: '2026-03-06', descricao: 'CAFE PIMENTA', categoria: 'Cigarro', valor: -63.75, conta: 'cartao' },
  { data: '2026-03-06', descricao: 'PATELLI PAES LTDA', categoria: 'Alimentação', valor: -38.71, conta: 'cartao' },
  { data: '2026-03-06', descricao: 'Google Tinder Dating', categoria: 'Diversão e Lazer', valor: -21.99, conta: 'cartao' },
  { data: '2026-03-05', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -19.0, conta: 'cartao' },
  { data: '2026-03-05', descricao: 'CachoBrasil', categoria: 'Alimentação', valor: -19.8, conta: 'cartao' },
  { data: '2026-03-05', descricao: 'GRASIFICO PET SHOP', categoria: 'Pets', valor: -120.0, conta: 'cartao' },
  { data: '2026-03-05', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -104.66, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Saúde - Variável', valor: -63.16, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'RAIA2115', categoria: 'Saúde - Variável', valor: -26.99, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'BANCA PATRIA', categoria: 'Alimentação', valor: -5.5, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'BELA CINTRA', categoria: 'Alimentação', valor: -44.33, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -44.83, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'Seguro Carro 5/12', categoria: 'Carro - Man/Imp/Seg', valor: -387.76, conta: 'cartao' },
  { data: '2026-03-04', descricao: 'NETFLIX ENTRETENIMENTO', categoria: 'Assinaturas e serviços', valor: -44.9, conta: 'cartao' },
  { data: '2026-03-03', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.0, conta: 'cartao' },
  { data: '2026-03-03', descricao: 'DIVINO CARNES', categoria: 'Mercado', valor: -71.73, conta: 'cartao' },
  { data: '2026-03-03', descricao: 'ConectCar', categoria: 'Carro - Variável', valor: -243.7, conta: 'cartao' },
  { data: '2026-03-02', descricao: 'Brinquedo Fred', categoria: 'Compras', valor: -101.31, conta: 'cartao' },
  { data: '2026-03-01', descricao: 'COBASI SOROCABA PANNUN', categoria: 'Pets', valor: -29.9, conta: 'cartao' },
  { data: '2026-03-01', descricao: 'NUTRIFRESH COMERCIO D', categoria: 'Alimentação', valor: -26.8, conta: 'cartao' },
  { data: '2026-03-01', descricao: 'FRUTTA E CIA', categoria: 'Alimentação', valor: -13.26, conta: 'cartao' },
  { data: '2026-03-01', descricao: 'MULTIPLEX PATIO CIANE', categoria: 'Diversão e Lazer', valor: -89.0, conta: 'cartao' },
  { data: '2026-03-01', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -59.0, conta: 'cartao' },
  { data: '2026-03-01', descricao: 'LOCAWEB', categoria: '$ Objetivos - Metas', valor: -74.7, conta: 'cartao' },
  { data: '2026-03-01', descricao: 'Sami Plano de Saúde', categoria: 'Saúde - Fixo', valor: -431.24, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'Barba', categoria: 'Diversão e Lazer', valor: -70.0, conta: 'bradesco' },
  { data: '2026-04-28', descricao: 'Rentabilidade', categoria: 'Reembolso', valor: 0.05, conta: 'bradesco' },
  { data: '2026-04-28', descricao: 'Energia', categoria: 'Casa', valor: -116.03, conta: 'bradesco' },
  { data: '2026-04-24', descricao: '2° via Certidão Casamento', categoria: 'Compras', valor: -46.74, conta: 'bradesco' },
  { data: '2026-04-23', descricao: 'Faxina', categoria: 'Casa', valor: -140.0, conta: 'bradesco' },
  { data: '2026-04-22', descricao: 'Reembolso Quinto Andar', categoria: 'Reembolso', valor: 179.49, conta: 'bradesco' },
  { data: '2026-04-20', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -268.8, conta: 'bradesco' },
  { data: '2026-04-20', descricao: 'INSS', categoria: 'CNPJ', valor: -178.31, conta: 'bradesco' },
  { data: '2026-04-20', descricao: 'Imposto CNPJ', categoria: 'CNPJ', valor: -1051.32, conta: 'bradesco' },
  { data: '2026-04-16', descricao: 'Rentabilidade', categoria: 'Reembolso', valor: 0.17, conta: 'bradesco' },
  { data: '2026-04-15', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -10920.62, conta: 'bradesco' },
  { data: '2026-04-15', descricao: 'IPVA 4/5', categoria: 'Carro - Man/Imp/Seg', valor: -595.51, conta: 'bradesco' },
  { data: '2026-04-15', descricao: 'Aluguél', categoria: 'Casa', valor: -2521.95, conta: 'bradesco' },
  { data: '2026-04-15', descricao: 'Faxina RB', categoria: 'Família', valor: -80.0, conta: 'bradesco' },
  { data: '2026-04-15', descricao: 'Contador', categoria: 'CNPJ', valor: -398.8, conta: 'bradesco' },
  { data: '2026-04-15', descricao: 'Claro Fibra', categoria: 'Casa', valor: -99.9, conta: 'bradesco' },
  { data: '2026-04-15', descricao: 'TIM', categoria: 'Celular', valor: -56.99, conta: 'bradesco' },
  { data: '2026-04-14', descricao: 'Paula', categoria: 'Reembolso', valor: 270.0, conta: 'bradesco' },
  { data: '2026-04-13', descricao: 'Plano de Saúde Pai e Mãe', categoria: 'Família', valor: -122.0, conta: 'bradesco' },
  { data: '2026-04-12', descricao: 'Estacionamento', categoria: 'Carro - Variável', valor: -20.0, conta: 'bradesco' },
  { data: '2026-04-10', descricao: 'Moldura', categoria: 'Compras', valor: -12.58, conta: 'bradesco' },
  { data: '2026-04-10', descricao: 'Faxina', categoria: 'Casa', valor: -140.0, conta: 'bradesco' },
  { data: '2026-04-10', descricao: 'Salário DSF', categoria: 'Salário', valor: 16712.0, conta: 'bradesco' },
  { data: '2026-04-06', descricao: 'Mounjaro', categoria: 'Fitness', valor: -300.0, conta: 'bradesco' },
  { data: '2026-04-06', descricao: 'Pod', categoria: 'Diversão e Lazer', valor: -100.0, conta: 'bradesco' },
  { data: '2026-04-30', descricao: 'Frango', categoria: 'Alimentação', valor: -21.0, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'Chopp', categoria: 'Alimentação', valor: -13.0, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'Cinema Re', categoria: 'Reembolsável', valor: -149.12, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -143.74, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'Liquido Arrefecimento radiador', categoria: 'Compras', valor: -68.45, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'CachoBrasil', categoria: 'Alimentação', valor: -9.9, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'Instal Ar Condic 99Pay  Pix 2/3', categoria: 'Compras', valor: -294.47, conta: 'cartao' },
  { data: '2026-04-30', descricao: '3 Camisas gola padre 2/2', categoria: 'Compras', valor: -82.35, conta: 'cartao' },
  { data: '2026-04-30', descricao: 'Camoseta e cueca 2/2', categoria: 'Compras', valor: -68.9, conta: 'cartao' },
  { data: '2026-04-27', descricao: 'SulAuto Modulo ABS 6/6', categoria: 'Carro - Man/Imp/Seg', valor: -650.0, conta: 'cartao' },
  { data: '2026-04-26', descricao: 'Fralda e Limpadores', categoria: 'Compras', valor: -111.68, conta: 'cartao' },
  { data: '2026-04-25', descricao: 'IFD FORNEIRO PIZZARIA', categoria: 'Alimentação', valor: -90.98, conta: 'cartao' },
  { data: '2026-04-23', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -26.8, conta: 'cartao' },
  { data: '2026-04-23', descricao: 'Lava Rápido', categoria: 'Carro - Variável', valor: -40.0, conta: 'cartao' },
  { data: '2026-04-23', descricao: 'GRASIFICO PET SHOP', categoria: 'Pets', valor: -220.0, conta: 'cartao' },
  { data: '2026-04-22', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -195.1, conta: 'cartao' },
  { data: '2026-04-22', descricao: 'REST IRMAOS', categoria: 'Mercado', valor: -7.94, conta: 'cartao' },
  { data: '2026-04-22', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -26.8, conta: 'cartao' },
  { data: '2026-04-22', descricao: 'DL UberRides', categoria: 'Transporte', valor: -15.94, conta: 'cartao' },
  { data: '2026-04-22', descricao: 'MERCADO MARIO PRIMARA', categoria: 'Mercado', valor: -16.95, conta: 'cartao' },
  { data: '2026-04-21', descricao: 'Banqueta e pato', categoria: 'Compras', valor: -86.55, conta: 'cartao' },
  { data: '2026-04-21', descricao: 'LEROY MERLIN Almofadas', categoria: 'Compras', valor: -195.32, conta: 'cartao' },
  { data: '2026-04-21', descricao: 'VILA VERDE CAFE', categoria: 'Alimentação', valor: -123.0, conta: 'cartao' },
  { data: '2026-04-21', descricao: 'POSTO LUSITANO', categoria: 'Carro - Variável', valor: -182.49, conta: 'cartao' },
  { data: '2026-04-21', descricao: 'LABI EXAMES SA 2/3', categoria: 'Saúde - Variável', valor: -137.33, conta: 'cartao' },
  { data: '2026-04-20', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -23.3, conta: 'cartao' },
  { data: '2026-04-19', descricao: 'CRISAFULLI AMP RIBEIRO', categoria: 'Cigarro', valor: -127.5, conta: 'cartao' },
  { data: '2026-04-19', descricao: 'HORSE BBQ', categoria: 'Alimentação', valor: -146.85, conta: 'cartao' },
  { data: '2026-04-18', descricao: 'CarneadaBarY', categoria: 'Alimentação', valor: -85.8, conta: 'cartao' },
  { data: '2026-04-18', descricao: 'Ar condicionado 2/10', categoria: 'Compras', valor: -223.1, conta: 'cartao' },
  { data: '2026-04-17', descricao: 'Comida italiana Azuir', categoria: 'Alimentação', valor: -31.0, conta: 'cartao' },
  { data: '2026-04-17', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -26.8, conta: 'cartao' },
  { data: '2026-04-16', descricao: 'Google Tinder Dating', categoria: 'Diversão e Lazer', valor: -35.99, conta: 'cartao' },
  { data: '2026-04-16', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -343.82, conta: 'cartao' },
  { data: '2026-04-16', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Mercado', valor: -91.21, conta: 'cartao' },
  { data: '2026-04-16', descricao: 'GRASIFICO PET SHOP', categoria: 'Pets', valor: -30.0, conta: 'cartao' },
  { data: '2026-04-16', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -32.1, conta: 'cartao' },
  { data: '2026-04-15', descricao: 'Quadro de Azulejo 3', categoria: 'Compras', valor: -55.47, conta: 'cartao' },
  { data: '2026-04-15', descricao: 'Cabo celular', categoria: 'Compras', valor: -44.99, conta: 'cartao' },
  { data: '2026-04-15', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -88.2, conta: 'cartao' },
  { data: '2026-04-14', descricao: 'Garrafa', categoria: 'Compras', valor: -49.89, conta: 'cartao' },
  { data: '2026-04-13', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -26.8, conta: 'cartao' },
  { data: '2026-04-12', descricao: 'IFD GSA LANCHES ARMAND', categoria: 'Alimentação', valor: -10.9, conta: 'cartao' },
  { data: '2026-04-12', descricao: 'PUB SOROCABA', categoria: 'Diversão e Lazer', valor: -96.0, conta: 'cartao' },
  { data: '2026-04-12', descricao: 'AUTO POSTO SOLEDADE', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-04-11', descricao: 'Imperatriz', categoria: 'Diversão e Lazer', valor: -135.0, conta: 'cartao' },
  { data: '2026-04-11', descricao: 'Imperatriz', categoria: 'Diversão e Lazer', valor: -30.0, conta: 'cartao' },
  { data: '2026-04-11', descricao: 'Imperatriz', categoria: 'Diversão e Lazer', valor: -90.0, conta: 'cartao' },
  { data: '2026-04-11', descricao: 'CRISTIANO TEODORO LOPE', categoria: 'Mercado', valor: -21.53, conta: 'cartao' },
  { data: '2026-04-11', descricao: 'Ajuste Seguro 2/2', categoria: 'Carro - Man/Imp/Seg', valor: -56.47, conta: 'cartao' },
  { data: '2026-04-10', descricao: 'Café', categoria: 'Alimentação', valor: -18.3, conta: 'cartao' },
  { data: '2026-04-10', descricao: 'DOCES ARTESANAIS', categoria: 'Alimentação', valor: -20.0, conta: 'cartao' },
  { data: '2026-04-10', descricao: 'Japa', categoria: 'Alimentação', valor: -283.36, conta: 'cartao' },
  { data: '2026-04-10', descricao: 'GROWTH 1/3', categoria: 'Fitness', valor: -125.99, conta: 'cartao' },
  { data: '2026-04-10', descricao: 'SHOPEE  SHPSTECNOLOGIA 2/2', categoria: 'Compras', valor: -111.99, conta: 'cartao' },
  { data: '2026-04-10', descricao: 'Vassoura, mangueira, faca, banco 3/4', categoria: 'Reembolsável', valor: -63.16, conta: 'cartao' },
  { data: '2026-04-10', descricao: 'Globo Globoplay 8/12', categoria: 'Assinaturas e serviços', valor: -19.9, conta: 'cartao' },
  { data: '2026-04-09', descricao: 'Quadro de Azulejo 2', categoria: 'Compras', valor: -45.48, conta: 'cartao' },
  { data: '2026-04-09', descricao: 'Wellhub Gympass BR Gym', categoria: 'Fitness', valor: -69.99, conta: 'cartao' },
  { data: '2026-04-07', descricao: 'Café', categoria: 'Alimentação', valor: -21.0, conta: 'cartao' },
  { data: '2026-04-07', descricao: 'Gasolina', categoria: 'Carro - Variável', valor: -50.0, conta: 'cartao' },
  { data: '2026-04-07', descricao: 'Dif', categoria: 'Reembolsável', valor: -17.53, conta: 'cartao' },
  { data: '2026-04-07', descricao: 'Quadro de Azulejo', categoria: 'Compras', valor: -45.48, conta: 'cartao' },
  { data: '2026-04-07', descricao: 'Testo 1/3', categoria: 'Fitness', valor: -92.33, conta: 'cartao' },
  { data: '2026-04-07', descricao: 'Google YouTube', categoria: 'Assinaturas e serviços', valor: -26.9, conta: 'cartao' },
  { data: '2026-04-06', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -353.65, conta: 'cartao' },
  { data: '2026-04-06', descricao: 'Copo', categoria: 'Compras', valor: -32.9, conta: 'cartao' },
  { data: '2026-04-05', descricao: 'AUTO POSTO TREVO', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-04-05', descricao: 'IFD TOTEM RR LANCHES -', categoria: 'Alimentação', valor: -37.5, conta: 'cartao' },
  { data: '2026-04-05', descricao: 'PostoEstrela', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-04-04', descricao: 'DonaLeliPadaria', categoria: 'Alimentação', valor: -29.0, conta: 'cartao' },
  { data: '2026-04-04', descricao: 'KORFIT ACADEMIA', categoria: 'Fitness', valor: -30.0, conta: 'cartao' },
  { data: '2026-04-04', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -103.79, conta: 'cartao' },
  { data: '2026-04-04', descricao: 'Seguro Carro 6/12', categoria: 'Carro - Man/Imp/Seg', valor: -387.76, conta: 'cartao' },
  { data: '2026-04-04', descricao: 'NETFLIX', categoria: 'Assinaturas e serviços', valor: -44.9, conta: 'cartao' },
  { data: '2026-04-03', descricao: 'Finger tape', categoria: 'Compras', valor: -20.99, conta: 'cartao' },
  { data: '2026-04-02', descricao: 'CAPPTA  TOP GRILL SORO', categoria: 'Alimentação', valor: -149.05, conta: 'cartao' },
  { data: '2026-04-02', descricao: 'SUPERMERCADO MARCELAO', categoria: 'Mercado', valor: -13.9, conta: 'cartao' },
  { data: '2026-04-02', descricao: 'SALUX CLINICA DE MEDIC 1/2', categoria: 'Saúde - Variável', valor: -150.0, conta: 'cartao' },
  { data: '2026-04-02', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -123.64, conta: 'cartao' },
  { data: '2026-04-02', descricao: 'GRASIFICO PET SHOP', categoria: 'Pets', valor: -120.0, conta: 'cartao' },
  { data: '2026-04-02', descricao: 'PADARIA E MERCADO SABO', categoria: 'Alimentação', valor: -29.97, conta: 'cartao' },
  { data: '2026-04-02', descricao: 'ConectCar', categoria: 'Carro - Variável', valor: -131.24, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'Carrefour Alameda Santos', categoria: 'Alimentação', valor: -12.75, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'CARREFOUR ALAMEDA SAN', categoria: 'Alimentação', valor: -24.18, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'RESTAURANTE TASTY GRIL', categoria: 'Alimentação', valor: -39.8, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'Peso de porta', categoria: 'Compras', valor: -36.74, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'BAR E RESTAURANTE MATO', categoria: 'Alimentação', valor: -12.4, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'Livro Kaori', categoria: 'Compras', valor: -81.36, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -59.0, conta: 'cartao' },
  { data: '2026-04-01', descricao: 'Sami Plano de Saúde', categoria: 'Saúde - Fixo', valor: -345.19, conta: 'cartao' },
  { data: '2026-05-29', descricao: 'Dif', categoria: 'Reembolsável', valor: -0.06, conta: 'bradesco' },
  { data: '2026-05-29', descricao: 'Presente DSF', categoria: 'Reembolso', valor: 200.0, conta: 'bradesco' },
  { data: '2026-05-29', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-05-25', descricao: 'Hotel Fred', categoria: 'Diversão e Lazer', valor: -160.0, conta: 'bradesco' },
  { data: '2026-05-21', descricao: 'Rentabilidade', categoria: 'Reembolso', valor: 0.05, conta: 'bradesco' },
  { data: '2026-05-20', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -268.8, conta: 'bradesco' },
  { data: '2026-05-20', descricao: 'Presente Mãe', categoria: 'Reembolsável', valor: -260.0, conta: 'bradesco' },
  { data: '2026-05-20', descricao: 'Re do cinema', categoria: 'Reembolso', valor: 40.0, conta: 'bradesco' },
  { data: '2026-05-20', descricao: 'Presente Mãe', categoria: 'Reembolsável', valor: -100.0, conta: 'bradesco' },
  { data: '2026-05-20', descricao: 'Presente Mãe', categoria: 'Reembolso', valor: 300.0, conta: 'bradesco' },
  { data: '2026-05-20', descricao: 'INSS', categoria: 'CNPJ', valor: -178.31, conta: 'bradesco' },
  { data: '2026-05-20', descricao: 'Imposto CNPJ', categoria: 'CNPJ', valor: -1054.86, conta: 'bradesco' },
  { data: '2026-05-19', descricao: 'Barba', categoria: 'Diversão e Lazer', valor: -70.0, conta: 'bradesco' },
  { data: '2026-05-18', descricao: 'Mesa Varanda', categoria: 'Compras', valor: -490.0, conta: 'bradesco' },
  { data: '2026-05-18', descricao: 'TIM', categoria: 'Celular', valor: -56.99, conta: 'bradesco' },
  { data: '2026-05-17', descricao: 'Mounjaro', categoria: 'Fitness', valor: -300.0, conta: 'bradesco' },
  { data: '2026-05-15', descricao: 'Dif', categoria: 'Reembolso', valor: 0.14, conta: 'bradesco' },
  { data: '2026-05-15', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -8201.26, conta: 'bradesco' },
  { data: '2026-05-15', descricao: 'IPVA 5/5', categoria: 'Carro - Man/Imp/Seg', valor: -595.51, conta: 'bradesco' },
  { data: '2026-05-15', descricao: 'Aluguél', categoria: 'Casa', valor: -2622.64, conta: 'bradesco' },
  { data: '2026-05-15', descricao: 'Faxina RB', categoria: 'Família', valor: -80.0, conta: 'bradesco' },
  { data: '2026-05-15', descricao: 'Contador', categoria: 'CNPJ', valor: -398.8, conta: 'bradesco' },
  { data: '2026-05-14', descricao: 'Camisa Pomba do Mato', categoria: 'Compras', valor: -56.0, conta: 'bradesco' },
  { data: '2026-05-14', descricao: 'Cofrinho Formatura Lari', categoria: '$ Objetivos - Metas', valor: -100.0, conta: 'bradesco' },
  { data: '2026-05-13', descricao: 'Plano de Saúde Pai e Mãe', categoria: 'Família', valor: -122.0, conta: 'bradesco' },
  { data: '2026-05-12', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-05-12', descricao: 'Gas', categoria: 'Casa', valor: -57.55, conta: 'bradesco' },
  { data: '2026-05-11', descricao: 'Dif', categoria: 'Reembolsável', valor: -2.62, conta: 'bradesco' },
  { data: '2026-05-11', descricao: 'Reembolso Cartório Online', categoria: 'Reembolso', valor: 46.74, conta: 'bradesco' },
  { data: '2026-05-11', descricao: 'Divorcio', categoria: '$ Segurança - Reserva', valor: -908.74, conta: 'bradesco' },
  { data: '2026-05-11', descricao: 'Ubatuba Gui 1/2', categoria: 'Diversão e Lazer', valor: -162.75, conta: 'bradesco' },
  { data: '2026-05-11', descricao: 'Claro Fibra', categoria: 'Casa', valor: -99.9, conta: 'bradesco' },
  { data: '2026-05-11', descricao: 'Salário DSF', categoria: 'Salário', valor: 16712.0, conta: 'bradesco' },
  { data: '2026-05-07', descricao: 'Paula', categoria: 'Reembolso', valor: 1769.0, conta: 'bradesco' },
  { data: '2026-05-06', descricao: 'Cartorio - Certidão União', categoria: 'Compras', valor: -93.61, conta: 'bradesco' },
  { data: '2026-05-31', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -56.55, conta: 'cartao' },
  { data: '2026-05-31', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -7.34, conta: 'cartao' },
  { data: '2026-05-31', descricao: 'RAIA2115', categoria: 'Saúde - Variável', valor: -16.98, conta: 'cartao' },
  { data: '2026-05-31', descricao: 'MERCADOLIVRE MERCADOL', categoria: 'Compras', valor: -66.4, conta: 'cartao' },
  { data: '2026-05-30', descricao: 'Estacionamento Imperatriz', categoria: 'Carro - Variável', valor: -30.0, conta: 'cartao' },
  { data: '2026-05-30', descricao: 'Porção Imperatriz', categoria: 'Diversão e Lazer', valor: -93.0, conta: 'cartao' },
  { data: '2026-05-30', descricao: 'QUINTAL DA IMPERATRIZ', categoria: 'Diversão e Lazer', valor: -122.0, conta: 'cartao' },
  { data: '2026-05-30', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-05-30', descricao: 'EduardoLuiz', categoria: 'Carro - Variável', valor: -70.0, conta: 'cartao' },
  { data: '2026-05-30', descricao: 'MP  NATUFEIRA', categoria: 'Alimentação', valor: -26.0, conta: 'cartao' },
  { data: '2026-05-30', descricao: 'Instal Ar Condic 99Pay  Pix 3/3', categoria: 'Compras', valor: -294.47, conta: 'cartao' },
  { data: '2026-05-29', descricao: 'DI PAOLO SOROCABA', categoria: 'Alimentação', valor: -133.9, conta: 'cartao' },
  { data: '2026-05-29', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -14.1, conta: 'cartao' },
  { data: '2026-05-29', descricao: 'PAYGO RAPOSAO MATERIAI', categoria: 'Compras', valor: -7.8, conta: 'cartao' },
  { data: '2026-05-28', descricao: 'PAYGO RAPOSAO MATERIAI', categoria: 'Compras', valor: -34.7, conta: 'cartao' },
  { data: '2026-05-28', descricao: 'PATELLI ALIMENTOS', categoria: 'Alimentação', valor: -23.8, conta: 'cartao' },
  { data: '2026-05-27', descricao: 'Tenis DSF', categoria: 'Reembolsável', valor: -359.99, conta: 'cartao' },
  { data: '2026-05-27', descricao: 'Calças 1/2', categoria: 'Compras', valor: -114.99, conta: 'cartao' },
  { data: '2026-05-27', descricao: 'NUTRIFRESH COMERCIO DE', categoria: 'Alimentação', valor: -34.9, conta: 'cartao' },
  { data: '2026-05-27', descricao: 'KELLY PARK ESTACIONAME', categoria: 'Carro - Variável', valor: -12.0, conta: 'cartao' },
  { data: '2026-05-26', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -121.52, conta: 'cartao' },
  { data: '2026-05-25', descricao: 'Ranchinho', categoria: 'Diversão e Lazer', valor: -91.5, conta: 'cartao' },
  { data: '2026-05-25', descricao: 'AUTO P ITAGUA UB LTD', categoria: 'Carro - Variável', valor: -149.61, conta: 'cartao' },
  { data: '2026-05-24', descricao: 'Escada Fred 1/2', categoria: 'Compras', valor: -103.85, conta: 'cartao' },
  { data: '2026-05-24', descricao: 'QUIOSQUE CANTINHO DA L', categoria: 'Diversão e Lazer', valor: -35.28, conta: 'cartao' },
  { data: '2026-05-24', descricao: 'MercadoSerraVerde', categoria: 'Diversão e Lazer', valor: -16.0, conta: 'cartao' },
  { data: '2026-05-24', descricao: 'Tapete e outros', categoria: 'Compras', valor: -183.78, conta: 'cartao' },
  { data: '2026-05-23', descricao: 'JARDIM', categoria: 'Diversão e Lazer', valor: -123.85, conta: 'cartao' },
  { data: '2026-05-23', descricao: 'CASINHA DA VOVO', categoria: 'Diversão e Lazer', valor: -55.72, conta: 'cartao' },
  { data: '2026-05-22', descricao: 'Gelo', categoria: 'Diversão e Lazer', valor: -16.0, conta: 'cartao' },
  { data: '2026-05-22', descricao: 'KUTZLEBEN E GONZALEZ A', categoria: 'Diversão e Lazer', valor: -23.1, conta: 'cartao' },
  { data: '2026-05-22', descricao: 'PARODI COSTA LTDA', categoria: 'Diversão e Lazer', valor: -23.87, conta: 'cartao' },
  { data: '2026-05-22', descricao: 'DROGARIA SAO PAULO SA', categoria: 'Saúde - Variável', valor: -9.99, conta: 'cartao' },
  { data: '2026-05-22', descricao: 'RestauranteCaju', categoria: 'Diversão e Lazer', valor: -51.0, conta: 'cartao' },
  { data: '2026-05-21', descricao: 'CARREFOUR ALAMEDA SAN', categoria: 'Alimentação', valor: -68.69, conta: 'cartao' },
  { data: '2026-05-21', descricao: 'Carrefour DSF - Ubatuba', categoria: 'Mercado', valor: -247.34, conta: 'cartao' },
  { data: '2026-05-21', descricao: 'BAR E RESTAURANTE MAT', categoria: 'Alimentação', valor: -12.4, conta: 'cartao' },
  { data: '2026-05-21', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -94.67, conta: 'cartao' },
  { data: '2026-05-21', descricao: 'LABI EXAMES SA 3/3', categoria: 'Saúde - Variável', valor: -137.33, conta: 'cartao' },
  { data: '2026-05-20', descricao: 'GRASIFICO PET SHOP', categoria: 'Pets', valor: -220.0, conta: 'cartao' },
  { data: '2026-05-19', descricao: 'IFD GENERAL CARNEIRO P', categoria: 'Alimentação', valor: -28.68, conta: 'cartao' },
  { data: '2026-05-19', descricao: 'Minoxidil e ioimbina 1/2', categoria: 'Fitness', valor: -76.17, conta: 'cartao' },
  { data: '2026-05-19', descricao: 'Google One', categoria: 'Assinaturas e serviços', valor: -149.9, conta: 'cartao' },
  { data: '2026-05-18', descricao: 'Ar condicionado 3/10', categoria: 'Compras', valor: -223.1, conta: 'cartao' },
  { data: '2026-05-16', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -114.27, conta: 'cartao' },
  { data: '2026-05-16', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Saúde - Variável', valor: -105.84, conta: 'cartao' },
  { data: '2026-05-16', descricao: 'Google Tinder Dating', categoria: 'Diversão e Lazer', valor: -35.99, conta: 'cartao' },
  { data: '2026-05-15', descricao: 'GRAFIKA EXPRESS SOROCA', categoria: 'Compras', valor: -70.0, conta: 'cartao' },
  { data: '2026-05-15', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.3, conta: 'cartao' },
  { data: '2026-05-14', descricao: 'Kibe', categoria: 'Alimentação', valor: -9.9, conta: 'cartao' },
  { data: '2026-05-14', descricao: 'Cheiros', categoria: 'Mercado', valor: -95.17, conta: 'cartao' },
  { data: '2026-05-14', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -28.27, conta: 'cartao' },
  { data: '2026-05-13', descricao: 'Acessorios mesa', categoria: 'Compras', valor: -124.0, conta: 'cartao' },
  { data: '2026-05-13', descricao: 'RESTAURANTE E PETISCA', categoria: 'Alimentação', valor: -110.55, conta: 'cartao' },
  { data: '2026-05-13', descricao: 'Álcool', categoria: 'Carro - Variável', valor: -160.22, conta: 'cartao' },
  { data: '2026-05-13', descricao: 'Troca de óleo', categoria: 'Carro - Man/Imp/Seg', valor: -477.8, conta: 'cartao' },
  { data: '2026-05-12', descricao: 'Vape', categoria: 'Cigarro', valor: -140.0, conta: 'cartao' },
  { data: '2026-05-12', descricao: 'Tinta e essência', categoria: 'Compras', valor: -167.63, conta: 'cartao' },
  { data: '2026-05-12', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -41.3, conta: 'cartao' },
  { data: '2026-05-11', descricao: 'Cinepolis', categoria: 'Diversão e Lazer', valor: -82.0, conta: 'cartao' },
  { data: '2026-05-11', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -206.94, conta: 'cartao' },
  { data: '2026-05-11', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -23.3, conta: 'cartao' },
  { data: '2026-05-10', descricao: 'GROWTH 2/3', categoria: 'Fitness', valor: -125.99, conta: 'cartao' },
  { data: '2026-05-10', descricao: 'Vassoura, mangueira, faca, banco 4/4', categoria: 'Reembolsável', valor: -63.16, conta: 'cartao' },
  { data: '2026-05-10', descricao: 'Globo Globoplay 9/12', categoria: 'Assinaturas e serviços', valor: -19.9, conta: 'cartao' },
  { data: '2026-05-09', descricao: 'Wellhub Gympass BR Gym', categoria: 'Fitness', valor: -69.99, conta: 'cartao' },
  { data: '2026-05-08', descricao: 'ESPETINHO DO MINEIRO', categoria: 'Diversão e Lazer', valor: -28.0, conta: 'cartao' },
  { data: '2026-05-08', descricao: 'MP  RIBEIRAOCHOPP', categoria: 'Diversão e Lazer', valor: -10.0, conta: 'cartao' },
  { data: '2026-05-08', descricao: 'VASTI VIEIRA SANTOS RI', categoria: 'Diversão e Lazer', valor: -7.0, conta: 'cartao' },
  { data: '2026-05-08', descricao: 'Presente Mãe 1/2', categoria: 'Compras', valor: -119.95, conta: 'cartao' },
  { data: '2026-05-07', descricao: 'PauloRafaelFerraz', categoria: 'Alimentação', valor: -15.0, conta: 'cartao' },
  { data: '2026-05-07', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -146.42, conta: 'cartao' },
  { data: '2026-05-07', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -32.1, conta: 'cartao' },
  { data: '2026-05-07', descricao: 'Testo 2/3', categoria: 'Fitness', valor: -92.31, conta: 'cartao' },
  { data: '2026-05-06', descricao: 'Led moldura', categoria: 'Compras', valor: -24.98, conta: 'cartao' },
  { data: '2026-05-06', descricao: 'Moldura', categoria: 'Compras', valor: -78.14, conta: 'cartao' },
  { data: '2026-05-06', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.3, conta: 'cartao' },
  { data: '2026-05-06', descricao: 'Google YouTube', categoria: 'Assinaturas e serviços', valor: -26.9, conta: 'cartao' },
  { data: '2026-05-05', descricao: 'AUTO ELETRICO KATEC L', categoria: 'Carro - Man/Imp/Seg', valor: -60.0, conta: 'cartao' },
  { data: '2026-05-04', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -100.23, conta: 'cartao' },
  { data: '2026-05-04', descricao: 'Seguro Carro 7/12', categoria: 'Carro - Man/Imp/Seg', valor: -387.76, conta: 'cartao' },
  { data: '2026-05-04', descricao: 'NETFLIX', categoria: 'Assinaturas e serviços', valor: -44.9, conta: 'cartao' },
  { data: '2026-05-03', descricao: 'Conveniência', categoria: 'Diversão e Lazer', valor: -37.0, conta: 'cartao' },
  { data: '2026-05-03', descricao: 'Conveniência', categoria: 'Diversão e Lazer', valor: -41.0, conta: 'cartao' },
  { data: '2026-05-03', descricao: 'Conveniência', categoria: 'Diversão e Lazer', valor: -14.8, conta: 'cartao' },
  { data: '2026-05-03', descricao: 'HORSE BBQ', categoria: 'Diversão e Lazer', valor: -389.4, conta: 'cartao' },
  { data: '2026-05-03', descricao: 'DROGASIL3549', categoria: 'Saúde - Variável', valor: -76.48, conta: 'cartao' },
  { data: '2026-05-03', descricao: 'FarmaPonteD21', categoria: 'Saúde - Variável', valor: -21.0, conta: 'cartao' },
  { data: '2026-05-03', descricao: 'ConectCar', categoria: 'Carro - Variável', valor: -117.95, conta: 'cartao' },
  { data: '2026-05-02', descricao: 'Casarão da Comida', categoria: 'Alimentação', valor: -67.89, conta: 'cartao' },
  { data: '2026-05-02', descricao: 'SALUX CLINICA DE MEDIC 2/2', categoria: 'Saúde - Variável', valor: -150.0, conta: 'cartao' },
  { data: '2026-05-01', descricao: 'Difusor Casa', categoria: 'Compras', valor: -115.81, conta: 'cartao' },
  { data: '2026-05-01', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -59.0, conta: 'cartao' },
  { data: '2026-05-01', descricao: 'Sami Plano de Saúde', categoria: 'Saúde - Fixo', valor: -345.19, conta: 'cartao' },
  { data: '2026-06-28', descricao: 'Rifa Lari', categoria: 'Compras', valor: -10.0, conta: 'bradesco' },
  { data: '2026-06-22', descricao: 'Resgate PicPay - Obj/Evol', categoria: 'Reembolso', valor: 1873.0, conta: 'bradesco' },
  { data: '2026-06-22', descricao: 'Transferência', categoria: 'Transferências', valor: 52.0, conta: 'bradesco' },
  { data: '2026-06-20', descricao: 'Unimed', categoria: 'Saúde - Fixo', valor: -609.41, conta: 'bradesco' },
  { data: '2026-06-20', descricao: 'Imposto CNPJ', categoria: 'CNPJ', valor: -1058.36, conta: 'bradesco' },
  { data: '2026-06-19', descricao: 'Estacionamento', categoria: 'Carro - Variável', valor: -18.0, conta: 'bradesco' },
  { data: '2026-06-19', descricao: 'INSS', categoria: 'CNPJ', valor: -178.31, conta: 'bradesco' },
  { data: '2026-06-17', descricao: 'Pão Moisés na rua', categoria: 'Mercado', valor: -20.0, conta: 'bradesco' },
  { data: '2026-06-16', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-06-16', descricao: 'TIM', categoria: 'Celular', valor: -56.99, conta: 'bradesco' },
  { data: '2026-06-15', descricao: 'Rentabilidade', categoria: 'Reembolso', valor: 0.32, conta: 'bradesco' },
  { data: '2026-06-15', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -8829.75, conta: 'bradesco' },
  { data: '2026-06-15', descricao: 'Aluguél', categoria: 'Casa', valor: -2836.73, conta: 'bradesco' },
  { data: '2026-06-15', descricao: 'Faxina RB', categoria: 'Família', valor: -80.0, conta: 'bradesco' },
  { data: '2026-06-15', descricao: 'Contador', categoria: 'CNPJ', valor: -398.8, conta: 'bradesco' },
  { data: '2026-06-14', descricao: 'Formatura Lari', categoria: '$ Objetivos - Metas', valor: -100.0, conta: 'bradesco' },
  { data: '2026-06-13', descricao: 'Objetivos', categoria: '# Objetivos', valor: -835.6, conta: 'bradesco' },
  { data: '2026-06-13', descricao: 'Objetivos', categoria: '# Objetivos', valor: -835.6, conta: 'bradesco' },
  { data: '2026-06-13', descricao: 'Segurança - Reserva', categoria: '# Segurança', valor: -835.6, conta: 'bradesco' },
  { data: '2026-06-13', descricao: 'Segurança - Investimento', categoria: '# Segurança', valor: -835.6, conta: 'bradesco' },
  { data: '2026-06-13', descricao: 'Plano de Saúde Pai e Mãe', categoria: 'Família', valor: -122.0, conta: 'bradesco' },
  { data: '2026-06-12', descricao: 'Barba', categoria: 'Diversão e Lazer', valor: -70.0, conta: 'bradesco' },
  { data: '2026-06-12', descricao: 'Gas', categoria: 'Casa', valor: -64.13, conta: 'bradesco' },
  { data: '2026-06-12', descricao: 'Claro Fibra', categoria: 'Casa', valor: -99.9, conta: 'bradesco' },
  { data: '2026-06-11', descricao: 'Transferência', categoria: 'Transferências', valor: -1350.0, conta: 'bradesco' },
  { data: '2026-06-10', descricao: 'Dif', categoria: 'Outras receitas', valor: 0.1, conta: 'bradesco' },
  { data: '2026-06-10', descricao: 'Esquema Wellhub', categoria: 'Fitness', valor: -100.0, conta: 'bradesco' },
  { data: '2026-06-10', descricao: 'Dado de jogo', categoria: 'Compras', valor: -2.3, conta: 'bradesco' },
  { data: '2026-06-10', descricao: 'Salário DSF', categoria: 'Salário', valor: 16712.0, conta: 'bradesco' },
  { data: '2026-06-05', descricao: 'Ubatuba Gui 2/2', categoria: 'Diversão e Lazer', valor: -162.75, conta: 'bradesco' },
  { data: '2026-06-02', descricao: 'Unimed', categoria: 'Saúde - Fixo', valor: -622.99, conta: 'bradesco' },
  { data: '2026-06-01', descricao: 'Energia', categoria: 'Casa', valor: -315.53, conta: 'bradesco' },
  { data: '2026-06-22', descricao: 'Transferência', categoria: 'Transferências', valor: -52.0, conta: 'bradesco' },
  { data: '2026-06-30', descricao: 'Quadro', categoria: 'Compras', valor: -90.18, conta: 'cartao' },
  { data: '2026-06-30', descricao: 'PADARIA REAL', categoria: 'Alimentação', valor: -49.6, conta: 'cartao' },
  { data: '2026-06-30', descricao: 'AutoParkEstaciona', categoria: 'Carro - Variável', valor: -4.0, conta: 'cartao' },
  { data: '2026-06-30', descricao: 'Pelicula', categoria: 'Compras', valor: -32.89, conta: 'cartao' },
  { data: '2026-06-29', descricao: 'MP  VILLACUSTOM', categoria: 'Diversão e Lazer', valor: -199.0, conta: 'cartao' },
  { data: '2026-06-29', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -32.1, conta: 'cartao' },
  { data: '2026-06-28', descricao: 'DROGARIA SAO PAULO 521 1/2', categoria: 'Saúde - Variável', valor: -119.05, conta: 'cartao' },
  { data: '2026-06-27', descricao: 'Pudim', categoria: 'Alimentação', valor: -45.7, conta: 'cartao' },
  { data: '2026-06-27', descricao: 'CAPPTA  TP GRILL SORO', categoria: 'Alimentação', valor: -76.89, conta: 'cartao' },
  { data: '2026-06-27', descricao: '2 calças Sport', categoria: 'Compras', valor: -120.0, conta: 'cartao' },
  { data: '2026-06-27', descricao: 'Calças 2/2', categoria: 'Compras', valor: -114.99, conta: 'cartao' },
  { data: '2026-06-26', descricao: 'REVOLUCAO MODAS E ACES', categoria: 'Cigarro', valor: -120.0, conta: 'cartao' },
  { data: '2026-06-25', descricao: 'COBASI SOROCABA PANNUN', categoria: 'Pets', valor: -124.89, conta: 'cartao' },
  { data: '2026-06-25', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -290.47, conta: 'cartao' },
  { data: '2026-06-25', descricao: 'CACHO BRASIL - DISTRIB', categoria: 'Alimentação', valor: -9.9, conta: 'cartao' },
  { data: '2026-06-24', descricao: 'IFD GSA LANCHES ARMAND', categoria: 'Alimentação', valor: -38.99, conta: 'cartao' },
  { data: '2026-06-24', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Saúde - Variável', valor: -32.99, conta: 'cartao' },
  { data: '2026-06-24', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Saúde - Variável', valor: -56.99, conta: 'cartao' },
  { data: '2026-06-24', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -33.6, conta: 'cartao' },
  { data: '2026-06-24', descricao: 'Escada Fred 2/2', categoria: 'Compras', valor: -103.84, conta: 'cartao' },
  { data: '2026-06-23', descricao: 'XODO PAULISTA', categoria: 'Alimentação', valor: -60.1, conta: 'cartao' },
  { data: '2026-06-23', descricao: 'TABACARIA ROMA', categoria: 'Alimentação', valor: -12.1, conta: 'cartao' },
  { data: '2026-06-23', descricao: 'SAVANA', categoria: 'Alimentação', valor: -43.9, conta: 'cartao' },
  { data: '2026-06-22', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -25.3, conta: 'cartao' },
  { data: '2026-06-22', descricao: 'AUTO POSTO CORREA NETO', categoria: 'Carro - Variável', valor: -130.89, conta: 'cartao' },
  { data: '2026-06-21', descricao: 'Festa Junina Votorantim', categoria: 'Diversão e Lazer', valor: -69.0, conta: 'cartao' },
  { data: '2026-06-21', descricao: 'Festa Junina Votorantim', categoria: 'Diversão e Lazer', valor: -100.0, conta: 'cartao' },
  { data: '2026-06-21', descricao: 'RAIA2115', categoria: 'Saúde - Variável', valor: -44.08, conta: 'cartao' },
  { data: '2026-06-21', descricao: 'Magnésio', categoria: 'Fitness', valor: -28.99, conta: 'cartao' },
  { data: '2026-06-20', descricao: 'Calça e Short', categoria: 'Compras', valor: -96.78, conta: 'cartao' },
  { data: '2026-06-20', descricao: 'EC           MELIMAIS', categoria: 'Assinaturas e serviços', valor: -9.9, conta: 'cartao' },
  { data: '2026-06-20', descricao: 'IFD MARCOS PAULO DE AL', categoria: 'Alimentação', valor: -76.79, conta: 'cartao' },
  { data: '2026-06-19', descricao: 'VILLA CUSTOM', categoria: 'Diversão e Lazer', valor: -110.8, conta: 'cartao' },
  { data: '2026-06-19', descricao: 'VILLA CUSTOM', categoria: 'Diversão e Lazer', valor: -78.8, conta: 'cartao' },
  { data: '2026-06-19', descricao: 'Banho Fred', categoria: 'Pets', valor: -220.0, conta: 'cartao' },
  { data: '2026-06-19', descricao: 'RESTAURANTE TOKYOYA', categoria: 'Alimentação', valor: -97.05, conta: 'cartao' },
  { data: '2026-06-19', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.3, conta: 'cartao' },
  { data: '2026-06-19', descricao: 'Minoxidil e ioimbina 2/2', categoria: 'Fitness', valor: -76.17, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'IFD MORAES COMERCIO DE', categoria: 'Alimentação', valor: -36.41, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'RODOSNACK GeG LANCHONE', categoria: 'Alimentação', valor: -13.5, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'BAR E RESTAURANTE MAT', categoria: 'Alimentação', valor: -39.38, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'TABACARIA ROMA', categoria: 'Alimentação', valor: -12.1, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'ALECRIM RESTAURANTE', categoria: 'Alimentação', valor: -47.6, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'MUNDO PAO', categoria: 'Alimentação', valor: -33.56, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'CAFE PIMENTA', categoria: 'Alimentação', valor: -16.7, conta: 'cartao' },
  { data: '2026-06-18', descricao: 'Ar condicionado 4/10', categoria: 'Compras', valor: -223.1, conta: 'cartao' },
  { data: '2026-06-17', descricao: 'POSTO LUSITANO', categoria: 'Carro - Variável', valor: -151.0, conta: 'cartao' },
  { data: '2026-06-17', descricao: 'Palha p/ caixa madeira', categoria: 'Compras', valor: -10.0, conta: 'cartao' },
  { data: '2026-06-17', descricao: 'Fita Laço', categoria: 'Compras', valor: -23.5, conta: 'cartao' },
  { data: '2026-06-17', descricao: 'Caixa Madeira', categoria: 'Compras', valor: -28.4, conta: 'cartao' },
  { data: '2026-06-17', descricao: 'Kafta', categoria: 'Alimentação', valor: -15.0, conta: 'cartao' },
  { data: '2026-06-17', descricao: 'Wellhub Basic', categoria: 'Fitness', valor: -69.99, conta: 'cartao' },
  { data: '2026-06-17', descricao: 'Manteiga de cacau', categoria: 'Compras', valor: -14.99, conta: 'cartao' },
  { data: '2026-06-16', descricao: 'Potes temperos', categoria: 'Compras', valor: -35.9, conta: 'cartao' },
  { data: '2026-06-16', descricao: 'MERCADO MARIO PRIMARA', categoria: 'Mercado', valor: -106.35, conta: 'cartao' },
  { data: '2026-06-16', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -22.3, conta: 'cartao' },
  { data: '2026-06-16', descricao: 'Adesivos', categoria: 'Compras', valor: -57.25, conta: 'cartao' },
  { data: '2026-06-16', descricao: 'BURGER KING', categoria: 'Alimentação', valor: -42.7, conta: 'cartao' },
  { data: '2026-06-15', descricao: 'Cinema', categoria: 'Diversão e Lazer', valor: -61.0, conta: 'cartao' },
  { data: '2026-06-15', descricao: 'Sunga', categoria: 'Compras', valor: -59.99, conta: 'cartao' },
  { data: '2026-06-15', descricao: 'DIF', categoria: 'Compras', valor: -0.01, conta: 'cartao' },
  { data: '2026-06-15', descricao: 'FarmaPonteD21', categoria: 'Saúde - Variável', valor: -9.98, conta: 'cartao' },
  { data: '2026-06-15', descricao: 'Horus', categoria: 'Fitness', valor: -78.9, conta: 'cartao' },
  { data: '2026-06-15', descricao: 'MP  GROWTHSUPPLEMENTS 1/3', categoria: 'Fitness', valor: -112.23, conta: 'cartao' },
  { data: '2026-06-15', descricao: 'Balança', categoria: 'Compras', valor: -19.05, conta: 'cartao' },
  { data: '2026-06-14', descricao: 'Google Tinder Dating', categoria: 'Diversão e Lazer', valor: -35.99, conta: 'cartao' },
  { data: '2026-06-13', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -340.71, conta: 'cartao' },
  { data: '2026-06-13', descricao: 'DROGASIL3549', categoria: 'Saúde - Variável', valor: -50.98, conta: 'cartao' },
  { data: '2026-06-12', descricao: 'Fotos Fred 1/6', categoria: '$ Objetivos - Metas', valor: -334.0, conta: 'cartao' },
  { data: '2026-06-12', descricao: 'BURGER KING', categoria: 'Alimentação', valor: -41.9, conta: 'cartao' },
  { data: '2026-06-12', descricao: 'Cabos celular', categoria: 'Compras', valor: -79.58, conta: 'cartao' },
  { data: '2026-06-11', descricao: 'Palhetas', categoria: 'Carro - Variável', valor: -120.5, conta: 'cartao' },
  { data: '2026-06-11', descricao: 'CAFE PIMENTA', categoria: 'Alimentação', valor: -4.5, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'RESTAURANTE E PETISCA', categoria: 'Alimentação', valor: -35.5, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'Testo 1/3', categoria: 'Fitness', valor: -109.52, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'PP ESTACIONAMENTOS', categoria: 'Carro - Variável', valor: -10.0, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'Calça e camiseta fitness', categoria: 'Compras', valor: -154.98, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'Ração 1/3', categoria: 'Pets', valor: -83.3, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'DECATHLON', categoria: 'Compras', valor: -209.97, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'R8COFFEE', categoria: 'Alimentação', valor: -16.4, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'Bioimpedância', categoria: 'Fitness', valor: -100.0, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'GROWTH 3/3', categoria: 'Fitness', valor: -125.99, conta: 'cartao' },
  { data: '2026-06-10', descricao: 'Globo Globoplay 10/12', categoria: 'Assinaturas e serviços', valor: -19.9, conta: 'cartao' },
  { data: '2026-06-09', descricao: 'Presente Azuir', categoria: 'Compras', valor: -148.0, conta: 'cartao' },
  { data: '2026-06-09', descricao: 'Wellhub', categoria: 'Fitness', valor: -312.24, conta: 'cartao' },
  { data: '2026-06-09', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -37.1, conta: 'cartao' },
  { data: '2026-06-09', descricao: 'POSTO LUSITANO', categoria: 'Carro - Variável', valor: -154.25, conta: 'cartao' },
  { data: '2026-06-09', descricao: 'Wellhub Gold', categoria: 'Fitness', valor: -69.99, conta: 'cartao' },
  { data: '2026-06-08', descricao: 'Dif', categoria: 'Reembolso', valor: 0.03, conta: 'cartao' },
  { data: '2026-06-08', descricao: 'Fita silicone', categoria: 'Compras', valor: -25.43, conta: 'cartao' },
  { data: '2026-06-08', descricao: 'Presente Mãe 2/2', categoria: 'Compras', valor: -119.95, conta: 'cartao' },
  { data: '2026-06-07', descricao: 'LEROY MERLIN', categoria: 'Compras', valor: -7.22, conta: 'cartao' },
  { data: '2026-06-07', descricao: 'CINEPOLIS OPERADORA DE', categoria: 'Diversão e Lazer', valor: -90.22, conta: 'cartao' },
  { data: '2026-06-07', descricao: 'Testo 3/3', categoria: 'Fitness', valor: -92.33, conta: 'cartao' },
  { data: '2026-06-07', descricao: 'Google YouTube', categoria: 'Assinaturas e serviços', valor: -26.9, conta: 'cartao' },
  { data: '2026-06-06', descricao: 'Ascendedor', categoria: 'Compras', valor: -19.0, conta: 'cartao' },
  { data: '2026-06-06', descricao: 'CRISTIANO TEODORO LOPE', categoria: 'Mercado', valor: -14.07, conta: 'cartao' },
  { data: '2026-06-05', descricao: 'MERCADO MARIO PRIMARA', categoria: 'Mercado', valor: -47.85, conta: 'cartao' },
  { data: '2026-06-05', descricao: 'Fire TV e Controles', categoria: 'Compras', valor: -684.88, conta: 'cartao' },
  { data: '2026-06-04', descricao: 'Microsoft Store', categoria: 'Assinaturas e serviços', valor: -76.9, conta: 'cartao' },
  { data: '2026-06-04', descricao: 'Seguro Carro 8/12', categoria: 'Carro - Man/Imp/Seg', valor: -387.76, conta: 'cartao' },
  { data: '2026-06-04', descricao: 'NETFLIX', categoria: 'Assinaturas e serviços', valor: -44.9, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'PriscilaDaSilva', categoria: 'Carro - Variável', valor: -16.0, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'CONFECCOES CAEDU', categoria: 'Compras', valor: -59.99, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'Lentes 1/2', categoria: 'Saúde - Variável', valor: -120.0, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -91.37, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'Tênis Adidas Amarelo 1/2', categoria: 'Compras', valor: -200.0, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'CACHO BRASIL', categoria: 'Alimentação', valor: -9.9, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -100.78, conta: 'cartao' },
  { data: '2026-06-03', descricao: 'Velcro', categoria: 'Compras', valor: -14.99, conta: 'cartao' },
  { data: '2026-06-01', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -59.0, conta: 'cartao' },
  { data: '2026-06-01', descricao: 'CHURROS CIA SOROCABA BRA', categoria: 'Alimentação', valor: -7.0, conta: 'cartao' },
  { data: '2026-06-01', descricao: 'Varal', categoria: 'Compras', valor: -79.23, conta: 'cartao' },
  { data: '2026-06-01', descricao: 'ConectCar', categoria: 'Carro - Variável', valor: -241.75, conta: 'cartao' },
  { data: '2026-07-31', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-07-31', descricao: 'Energia', categoria: 'Casa', valor: -154.76, conta: 'bradesco' },
  { data: '2026-07-23', descricao: 'Carla', categoria: 'Reembolso', valor: 43.0, conta: 'bradesco' },
  { data: '2026-07-21', descricao: 'Renda', categoria: 'Investimentos', valor: 0.02, conta: 'bradesco' },
  { data: '2026-07-21', descricao: 'Costureira', categoria: 'Compras', valor: -15.0, conta: 'bradesco' },
  { data: '2026-07-20', descricao: 'Unimed', categoria: 'Saúde - Fixo', valor: -609.41, conta: 'bradesco' },
  { data: '2026-07-20', descricao: 'INSS', categoria: 'CNPJ', valor: -178.31, conta: 'bradesco' },
  { data: '2026-07-20', descricao: 'Imposto CNPJ', categoria: 'CNPJ', valor: -1061.83, conta: 'bradesco' },
  { data: '2026-07-19', descricao: 'Guara Viton Tafa', categoria: 'Reembolso', valor: 40.0, conta: 'bradesco' },
  { data: '2026-07-17', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-07-16', descricao: 'Resgate 99 - Investimento', categoria: 'Transferências', valor: 922.0, conta: 'bradesco' },
  { data: '2026-07-16', descricao: 'Resgate PicPay - Obj/Evol', categoria: 'Transferências', valor: 1676.2, conta: 'bradesco' },
  { data: '2026-07-16', descricao: 'Taxa Fiscalização', categoria: 'CNPJ', valor: -250.54, conta: 'bradesco' },
  { data: '2026-07-16', descricao: 'Dif', categoria: 'Diferença', valor: -5.0, conta: 'bradesco' },
  { data: '2026-07-16', descricao: 'TIM', categoria: 'Celular', valor: -56.99, conta: 'bradesco' },
  { data: '2026-07-15', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -9981.26, conta: 'bradesco' },
  { data: '2026-07-15', descricao: 'Aluguél', categoria: 'Casa', valor: -2789.22, conta: 'bradesco' },
  { data: '2026-07-15', descricao: 'Faxina RB', categoria: 'Família', valor: -80.0, conta: 'bradesco' },
  { data: '2026-07-15', descricao: 'Contador', categoria: 'CNPJ', valor: -398.8, conta: 'bradesco' },
  { data: '2026-07-13', descricao: 'Segurança', categoria: 'Transferências', valor: -1671.2, conta: 'bradesco' },
  { data: '2026-07-13', descricao: 'Objetivos', categoria: 'Transferências', valor: -1671.2, conta: 'bradesco' },
  { data: '2026-07-13', descricao: 'Multa', categoria: 'Carro - Variável', valor: -156.18, conta: 'bradesco' },
  { data: '2026-07-13', descricao: 'Plano de Saúde Pai e Mãe', categoria: 'Família', valor: -122.0, conta: 'bradesco' },
  { data: '2026-07-13', descricao: 'Salário DSF', categoria: 'Salário', valor: 16712.0, conta: 'bradesco' },
  { data: '2026-07-12', descricao: 'Bolão Re', categoria: 'Diversão e Lazer', valor: -10.0, conta: 'bradesco' },
  { data: '2026-07-12', descricao: 'Gas', categoria: 'Casa', valor: -70.89, conta: 'bradesco' },
  { data: '2026-07-10', descricao: 'Claro Fibra', categoria: 'Casa', valor: -99.9, conta: 'bradesco' },
  { data: '2026-07-09', descricao: 'Renda Brad', categoria: 'Investimentos', valor: 0.1, conta: 'bradesco' },
  { data: '2026-07-07', descricao: 'Bolão', categoria: 'Diversão e Lazer', valor: -20.0, conta: 'bradesco' },
  { data: '2026-07-03', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-07-01', descricao: 'Flá Festa Votorantim', categoria: 'Reembolso', valor: 50.0, conta: 'bradesco' },
  { data: '2026-07-30', descricao: 'YatesComercioDe', categoria: 'Alimentação', valor: -17.99, conta: 'cartao' },
  { data: '2026-07-29', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -49.54, conta: 'cartao' },
  { data: '2026-07-28', descricao: 'IFD GSA LANCHES ARMAND', categoria: 'Alimentação', valor: -37.99, conta: 'cartao' },
  { data: '2026-07-28', descricao: 'Cinta', categoria: 'Compras', valor: -26.09, conta: 'cartao' },
  { data: '2026-07-28', descricao: 'DROGARIA SAO PAULO 521 2/2', categoria: 'Saúde - Variável', valor: -119.05, conta: 'cartao' },
  { data: '2026-07-26', descricao: 'AUTO POSTO PAVAO 91 LT', categoria: 'Carro - Variável', valor: -100.0, conta: 'cartao' },
  { data: '2026-07-25', descricao: 'KLAAS FLORES E PLANTA', categoria: 'Diversão e Lazer', valor: -78.0, conta: 'cartao' },
  { data: '2026-07-24', descricao: 'HOLAMBIER', categoria: 'Diversão e Lazer', valor: -83.6, conta: 'cartao' },
  { data: '2026-07-24', descricao: 'Estacionamento Formatura', categoria: 'Diversão e Lazer', valor: -78.0, conta: 'cartao' },
  { data: '2026-07-24', descricao: 'CASA DE PAES AGUIA DOU', categoria: 'Alimentação', valor: -55.88, conta: 'cartao' },
  { data: '2026-07-23', descricao: 'Google Claude by Anth', categoria: '$ Objetivos - Metas', valor: -110.0, conta: 'cartao' },
  { data: '2026-07-23', descricao: 'PATRON ALIMENTOS MEXIC', categoria: 'Alimentação', valor: -93.5, conta: 'cartao' },
  { data: '2026-07-23', descricao: 'CARREFOUR ALAMEDA SAN', categoria: 'Alimentação', valor: -11.89, conta: 'cartao' },
  { data: '2026-07-23', descricao: 'Agulhas', categoria: 'Saúde - Variável', valor: -87.18, conta: 'cartao' },
  { data: '2026-07-23', descricao: 'DIVINO FOGAO', categoria: 'Alimentação', valor: -47.9, conta: 'cartao' },
  { data: '2026-07-22', descricao: 'G4SpRestaurante', categoria: 'Alimentação', valor: -243.93, conta: 'cartao' },
  { data: '2026-07-22', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -71.13, conta: 'cartao' },
  { data: '2026-07-22', descricao: 'Barba', categoria: 'Diversão e Lazer', valor: -55.0, conta: 'cartao' },
  { data: '2026-07-22', descricao: 'DROGASIL3549', categoria: 'Saúde - Variável', valor: -13.58, conta: 'cartao' },
  { data: '2026-07-22', descricao: 'CACHO BRASIL', categoria: 'Alimentação', valor: -26.8, conta: 'cartao' },
  { data: '2026-07-22', descricao: 'Banho Fred', categoria: 'Pets', valor: -220.0, conta: 'cartao' },
  { data: '2026-07-21', descricao: 'Finger Tape', categoria: 'Compras', valor: -18.07, conta: 'cartao' },
  { data: '2026-07-21', descricao: 'Flor de Sal', categoria: 'Alimentação', valor: -49.4, conta: 'cartao' },
  { data: '2026-07-21', descricao: 'Testo 1/3', categoria: 'Fitness', valor: -114.94, conta: 'cartao' },
  { data: '2026-07-20', descricao: 'Mounjaro 6meses 1/4', categoria: 'Fitness', valor: -352.93, conta: 'cartao' },
  { data: '2026-07-20', descricao: 'EC           MELIMAIS', categoria: 'Assinaturas e serviços', valor: -9.9, conta: 'cartao' },
  { data: '2026-07-19', descricao: 'Comedouro', categoria: 'Compras', valor: -12.99, conta: 'cartao' },
  { data: '2026-07-19', descricao: 'DAISO BRASIL', categoria: 'Compras', valor: -21.98, conta: 'cartao' },
  { data: '2026-07-19', descricao: 'RANCHO DO CUPIM SOROC', categoria: 'Alimentação', valor: -87.8, conta: 'cartao' },
  { data: '2026-07-19', descricao: 'Utensílios cozinha', categoria: 'Compras', valor: -59.72, conta: 'cartao' },
  { data: '2026-07-18', descricao: 'Guara Viton Rafa', categoria: 'Reembolsável', valor: -40.0, conta: 'cartao' },
  { data: '2026-07-18', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -751.85, conta: 'cartao' },
  { data: '2026-07-18', descricao: 'DonAguirre', categoria: 'Alimentação', valor: -145.78, conta: 'cartao' },
  { data: '2026-07-18', descricao: 'Ar condicionado 5/10', categoria: 'Compras', valor: -223.1, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Alcool', categoria: 'Carro - Variável', valor: -150.84, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Sunga', categoria: 'Compras', valor: -79.9, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Meias e Cuecas Skala', categoria: 'Compras', valor: -151.95, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Esfiha', categoria: 'Alimentação', valor: -33.7, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Pastelaria', categoria: 'Alimentação', valor: -14.5, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Estacionamento', categoria: 'Carro - Variável', valor: -18.0, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Aluguel Terno 1/2', categoria: 'Diversão e Lazer', valor: -200.0, conta: 'cartao' },
  { data: '2026-07-17', descricao: 'Wellhub Basic', categoria: 'Fitness', valor: -54.9, conta: 'cartao' },
  { data: '2026-07-15', descricao: 'Ifood', categoria: 'Alimentação', valor: -50.88, conta: 'cartao' },
  { data: '2026-07-15', descricao: 'Imã e Peso Porta', categoria: 'Compras', valor: -43.82, conta: 'cartao' },
  { data: '2026-07-15', descricao: 'Ioimbina', categoria: 'Fitness', valor: -60.79, conta: 'cartao' },
  { data: '2026-07-15', descricao: 'Magnésio', categoria: 'Fitness', valor: -56.24, conta: 'cartao' },
  { data: '2026-07-15', descricao: 'MP  GROWTHSUPPLEMENTS 2/3', categoria: 'Fitness', valor: -112.22, conta: 'cartao' },
  { data: '2026-07-14', descricao: 'Lanche', categoria: 'Alimentação', valor: -38.0, conta: 'cartao' },
  { data: '2026-07-14', descricao: 'Quitanda', categoria: 'Mercado', valor: -11.95, conta: 'cartao' },
  { data: '2026-07-14', descricao: 'Ifood', categoria: 'Alimentação', valor: -31.99, conta: 'cartao' },
  { data: '2026-07-14', descricao: 'Carro - Bieleta e Buchas 1/4', categoria: 'Carro - Man/Imp/Seg', valor: -487.5, conta: 'cartao' },
  { data: '2026-07-13', descricao: 'CHUR E LANC SIQUELERO', categoria: 'Alimentação', valor: -16.0, conta: 'cartao' },
  { data: '2026-07-12', descricao: 'Projetor 1/2', categoria: 'Compras', valor: -201.08, conta: 'cartao' },
  { data: '2026-07-12', descricao: 'Fotos Fred 2/6', categoria: '$ Objetivos - Metas', valor: -334.0, conta: 'cartao' },
  { data: '2026-07-11', descricao: 'MINI MERCADO IDEAL', categoria: 'Diversão e Lazer', valor: -18.69, conta: 'cartao' },
  { data: '2026-07-10', descricao: 'CINELANDIA LANCHES', categoria: 'Alimentação', valor: -21.0, conta: 'cartao' },
  { data: '2026-07-10', descricao: 'AUTO POSTO AMERICANO', categoria: 'Carro - Variável', valor: -207.7, conta: 'cartao' },
  { data: '2026-07-10', descricao: 'Fralda', categoria: 'Pets', valor: -25.0, conta: 'cartao' },
  { data: '2026-07-10', descricao: 'Testo 2/3', categoria: 'Fitness', valor: -109.51, conta: 'cartao' },
  { data: '2026-07-10', descricao: 'Ração 2/3', categoria: 'Pets', valor: -83.3, conta: 'cartao' },
  { data: '2026-07-10', descricao: 'Globo Globoplay 11/12', categoria: 'Assinaturas e serviços', valor: -19.9, conta: 'cartao' },
  { data: '2026-07-09', descricao: 'Dif', categoria: 'Reembolso', valor: 3.65, conta: 'cartao' },
  { data: '2026-07-09', descricao: 'Inove Life', categoria: 'Diversão e Lazer', valor: -75.0, conta: 'cartao' },
  { data: '2026-07-09', descricao: 'Wellhub Gympass BR Gym', categoria: 'Fitness', valor: -379.9, conta: 'cartao' },
  { data: '2026-07-08', descricao: 'IOF', categoria: 'Juros e Taxas', valor: -3.63, conta: 'cartao' },
  { data: '2026-07-08', descricao: 'Clareamento + Dentista 1/2', categoria: '$ Objetivos - Metas', valor: -1041.58, conta: 'cartao' },
  { data: '2026-07-08', descricao: 'Camisetas', categoria: 'Compras', valor: -49.98, conta: 'cartao' },
  { data: '2026-07-08', descricao: 'VO LENITA', categoria: 'Alimentação', valor: -115.8, conta: 'cartao' },
  { data: '2026-07-07', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -115.28, conta: 'cartao' },
  { data: '2026-07-07', descricao: 'SUPER GRILL EXPRESS', categoria: 'Alimentação', valor: -47.88, conta: 'cartao' },
  { data: '2026-07-07', descricao: 'Havaiana', categoria: 'Compras', valor: -74.99, conta: 'cartao' },
  { data: '2026-07-07', descricao: 'CARREFOUR ALAMEDA SAN', categoria: 'Alimentação', valor: -10.43, conta: 'cartao' },
  { data: '2026-07-07', descricao: 'Google YouTube', categoria: 'Assinaturas e serviços', valor: -26.9, conta: 'cartao' },
  { data: '2026-07-06', descricao: 'LEROY MERLIN', categoria: 'Compras', valor: -14.44, conta: 'cartao' },
  { data: '2026-07-06', descricao: 'SUPER SHOPPING DA UTIL', categoria: 'Compras', valor: -69.97, conta: 'cartao' },
  { data: '2026-07-06', descricao: 'REVOLUCAO MODAS E ACES', categoria: 'Cigarro', valor: -110.0, conta: 'cartao' },
  { data: '2026-07-05', descricao: 'U C E N S', categoria: 'Alimentação', valor: -43.0, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'HABIBS  APP', categoria: 'Alimentação', valor: -70.7, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'MC DONALDS ISO', categoria: 'Alimentação', valor: -9.8, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'SHOWCOLATE', categoria: 'Alimentação', valor: -34.0, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'FILIAL PLK IGUATEMI ES', categoria: 'Alimentação', valor: -35.8, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -37.2, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'ANIMALE LANCHERIA', categoria: 'Alimentação', valor: -35.0, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'Microsoft Store', categoria: 'Assinaturas e serviços', valor: -76.9, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'Seguro Carro 9/12', categoria: 'Carro - Man/Imp/Seg', valor: -387.76, conta: 'cartao' },
  { data: '2026-07-04', descricao: 'NETFLIX', categoria: 'Assinaturas e serviços', valor: -44.9, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -104.37, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'CINEPOLIS', categoria: 'Diversão e Lazer', valor: -47.0, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'CINEPOLIS', categoria: 'Diversão e Lazer', valor: -130.0, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'IGUATEMI ESPLANADA SOR', categoria: 'Alimentação', valor: -22.9, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -150.05, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -41.4, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'Lentes 2/2', categoria: 'Saúde - Variável', valor: -120.0, conta: 'cartao' },
  { data: '2026-07-03', descricao: 'Tênis Adidas Amarelo 2/2', categoria: 'Compras', valor: -200.0, conta: 'cartao' },
  { data: '2026-07-02', descricao: 'Barba', categoria: 'Diversão e Lazer', valor: -110.0, conta: 'cartao' },
  { data: '2026-07-02', descricao: 'FRAN S CAFE', categoria: 'Alimentação', valor: -24.0, conta: 'cartao' },
  { data: '2026-07-02', descricao: 'RemedioPopular', categoria: 'Saúde - Variável', valor: -13.49, conta: 'cartao' },
  { data: '2026-07-02', descricao: 'ConectCar', categoria: 'Carro - Variável', valor: -221.29, conta: 'cartao' },
  { data: '2026-07-01', descricao: 'Macacão Kaori', categoria: 'Compras', valor: -99.9, conta: 'cartao' },
  { data: '2026-07-01', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -293.99, conta: 'cartao' },
  { data: '2026-07-01', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.7, conta: 'cartao' },
  { data: '2026-07-01', descricao: 'IG*Empreender', categoria: '$ Objetivos - Metas', valor: -59.0, conta: 'cartao' },
  { data: '2026-08-28', descricao: 'Energia', categoria: 'Casa', valor: -127.82, conta: 'bradesco' },
  { data: '2026-08-28', descricao: 'Faxina', categoria: 'Casa', valor: -150.0, conta: 'bradesco' },
  { data: '2026-08-22', descricao: 'Gravata Gusta', categoria: 'Diversão e Lazer', valor: -50.0, conta: 'bradesco' },
  { data: '2026-08-20', descricao: 'Unimed', categoria: 'Saúde - Fixo', valor: -644.41, conta: 'bradesco' },
  { data: '2026-08-20', descricao: 'INSS', categoria: 'CNPJ', valor: -178.31, conta: 'bradesco' },
  { data: '2026-08-20', descricao: 'Imposto CNPJ', categoria: 'CNPJ', valor: -1065.25, conta: 'bradesco' },
  { data: '2026-08-17', descricao: 'Renda', categoria: 'Investimentos', valor: 0.2, conta: 'bradesco' },
  { data: '2026-08-17', descricao: 'Pagamento de fatura', categoria: 'Pagamento de fatura', valor: -8859.99, conta: 'bradesco' },
  { data: '2026-08-17', descricao: 'Aluguél', categoria: 'Casa', valor: -2564.42, conta: 'bradesco' },
  { data: '2026-08-17', descricao: 'Faxina RB', categoria: 'Família', valor: -80.0, conta: 'bradesco' },
  { data: '2026-08-17', descricao: 'Contador', categoria: 'CNPJ', valor: -398.8, conta: 'bradesco' },
  { data: '2026-08-17', descricao: 'TIM', categoria: 'Celular', valor: -56.99, conta: 'bradesco' },
  { data: '2026-08-13', descricao: 'Plano de Saúde Pai e Mãe', categoria: 'Família', valor: -122.0, conta: 'bradesco' },
  { data: '2026-08-12', descricao: 'Gas', categoria: 'Casa', valor: -129.68, conta: 'bradesco' },
  { data: '2026-08-12', descricao: 'Claro Fibra', categoria: 'Casa', valor: -99.9, conta: 'bradesco' },
  { data: '2026-08-12', descricao: 'Energia', categoria: 'Casa', valor: -127.82, conta: 'bradesco' },
  { data: '2026-08-10', descricao: 'Salário DSF', categoria: 'Salário', valor: 16712.0, conta: 'bradesco' },
  { data: '2026-08-04', descricao: 'Juros', categoria: 'Juros e Taxas', valor: -0.2, conta: 'bradesco' },
  { data: '2026-08-02', descricao: 'Pod', categoria: 'Cigarro', valor: -154.0, conta: 'bradesco' },
  { data: '2026-08-29', descricao: 'RESTAURANTE DRKOY', categoria: 'Alimentação', valor: -133.0, conta: 'cartao' },
  { data: '2026-08-27', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Saúde - Variável', valor: -38.0, conta: 'cartao' },
  { data: '2026-08-27', descricao: 'CACHO BRASIL', categoria: 'Alimentação', valor: -18.8, conta: 'cartao' },
  { data: '2026-08-27', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -141.86, conta: 'cartao' },
  { data: '2026-08-25', descricao: 'SUPER SHOPPING DA UTIL', categoria: 'Compras', valor: -169.97, conta: 'cartao' },
  { data: '2026-08-24', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -196.81, conta: 'cartao' },
  { data: '2026-08-24', descricao: 'EstoqueCar', categoria: 'Carro - Variável', valor: -18.0, conta: 'cartao' },
  { data: '2026-08-24', descricao: 'HAVAN SOROCABA', categoria: 'Compras', valor: -34.98, conta: 'cartao' },
  { data: '2026-08-24', descricao: 'TAMMY PASTELARIA', categoria: 'Alimentação', valor: -42.8, conta: 'cartao' },
  { data: '2026-08-24', descricao: 'JIM', categoria: 'Cigarro', valor: -180.84, conta: 'cartao' },
  { data: '2026-08-23', descricao: 'NOVO PORTO AUTO POSTO', categoria: 'Carro - Variável', valor: -173.73, conta: 'cartao' },
  { data: '2026-08-23', descricao: 'BURGER KING', categoria: 'Alimentação', valor: -34.7, conta: 'cartao' },
  { data: '2026-08-22', descricao: 'RESTAURANTE HANGAR', categoria: 'Alimentação', valor: -139.15, conta: 'cartao' },
  { data: '2026-08-21', descricao: 'CARREFOUR ALAMEDA SAN', categoria: 'Alimentação', valor: -21.98, conta: 'cartao' },
  { data: '2026-08-21', descricao: 'BOOZ REATAURANTE', categoria: 'Alimentação', valor: -33.9, conta: 'cartao' },
  { data: '2026-08-21', descricao: 'Testo 2/3', categoria: 'Fitness', valor: -114.94, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'EDNA LIMA DOCES', categoria: 'Alimentação', valor: -8.0, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'SulaNovaes', categoria: 'Alimentação', valor: -26.0, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'YAKISSOBA FAST', categoria: 'Alimentação', valor: -21.0, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'EstoqueCar', categoria: 'Carro - Variável', valor: -6.0, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'YatesComercioDe', categoria: 'Alimentação', valor: -25.98, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'Mounjaro 6meses 2/4', categoria: 'Fitness', valor: -352.93, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'EC           MELIMAIS', categoria: 'Assinaturas e serviços', valor: -9.9, conta: 'cartao' },
  { data: '2026-08-20', descricao: 'Banho Fred', categoria: 'Pets', valor: -220.0, conta: 'cartao' },
  { data: '2026-08-19', descricao: 'Barba', categoria: 'Diversão e Lazer', valor: -80.0, conta: 'cartao' },
  { data: '2026-08-19', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.3, conta: 'cartao' },
  { data: '2026-08-18', descricao: 'Fralda e Tinta', categoria: 'Compras', valor: -102.42, conta: 'cartao' },
  { data: '2026-08-18', descricao: 'Ar condicionado 6/10', categoria: 'Compras', valor: -223.14, conta: 'cartao' },
  { data: '2026-08-17', descricao: 'Aluguel Terno 2/2', categoria: 'Diversão e Lazer', valor: -200.0, conta: 'cartao' },
  { data: '2026-08-17', descricao: 'Wellhub Basic', categoria: 'Fitness', valor: -54.9, conta: 'cartao' },
  { data: '2026-08-16', descricao: 'Presente Gusta 1/2', categoria: 'Diversão e Lazer', valor: -199.56, conta: 'cartao' },
  { data: '2026-08-16', descricao: 'Hostel Guarujá', categoria: 'Diversão e Lazer', valor: -229.52, conta: 'cartao' },
  { data: '2026-08-16', descricao: 'IFD ZAMP S', categoria: 'Alimentação', valor: -50.11, conta: 'cartao' },
  { data: '2026-08-15', descricao: 'MP  GROWTHSUPPLEMENTS 3/3', categoria: 'Fitness', valor: -112.23, conta: 'cartao' },
  { data: '2026-08-14', descricao: 'Carro - Bieleta e Buchas 2/4', categoria: 'Carro - Man/Imp/Seg', valor: -487.5, conta: 'cartao' },
  { data: '2026-08-13', descricao: 'CAFE VIOLETA', categoria: 'Alimentação', valor: -77.0, conta: 'cartao' },
  { data: '2026-08-13', descricao: 'SAVANA', categoria: 'Alimentação', valor: -23.5, conta: 'cartao' },
  { data: '2026-08-13', descricao: 'ConectCar', categoria: 'Carro - Variável', valor: -344.5, conta: 'cartao' },
  { data: '2026-08-12', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -165.52, conta: 'cartao' },
  { data: '2026-08-12', descricao: 'YatesComercioDe', categoria: 'Alimentação', valor: -16.99, conta: 'cartao' },
  { data: '2026-08-12', descricao: 'Projetor 2/2', categoria: 'Compras', valor: -201.07, conta: 'cartao' },
  { data: '2026-08-12', descricao: 'Fotos Fred 3/6', categoria: '$ Objetivos - Metas', valor: -334.0, conta: 'cartao' },
  { data: '2026-08-11', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -124.17, conta: 'cartao' },
  { data: '2026-08-11', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -28.1, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'IOF', categoria: 'Juros e Taxas', valor: -3.57, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'IFD GSA LANCHES ARMAND', categoria: 'Alimentação', valor: -76.97, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'PANIFICADORA PANICENTE', categoria: 'Alimentação', valor: -18.3, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'Google Claude by Anth', categoria: '$ Objetivos - Metas', valor: -687.5, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'Testo 3/3', categoria: 'Fitness', valor: -109.52, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'Ração 3/3', categoria: 'Pets', valor: -83.3, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'Wellhub Gympass BR Gym', categoria: 'Fitness', valor: -379.9, conta: 'cartao' },
  { data: '2026-08-10', descricao: 'Globo Globoplay 12/12', categoria: 'Assinaturas e serviços', valor: -19.9, conta: 'cartao' },
  { data: '2026-08-08', descricao: 'MERCADO DODA', categoria: 'Mercado', valor: -114.32, conta: 'cartao' },
  { data: '2026-08-08', descricao: 'Clareamento + Dentista 2/2', categoria: '$ Objetivos - Metas', valor: -1041.58, conta: 'cartao' },
  { data: '2026-08-07', descricao: 'IFD GSA LANCHES ARMAND', categoria: 'Alimentação', valor: -100.97, conta: 'cartao' },
  { data: '2026-08-06', descricao: 'CONFIANCA SOROCABA', categoria: 'Mercado', valor: -147.67, conta: 'cartao' },
  { data: '2026-08-06', descricao: 'ALECRIM RESTAURANTE', categoria: 'Alimentação', valor: -42.3, conta: 'cartao' },
  { data: '2026-08-06', descricao: 'TABACARIA LEE', categoria: 'Alimentação', valor: -12.1, conta: 'cartao' },
  { data: '2026-08-06', descricao: 'Google YouTube', categoria: 'Assinaturas e serviços', valor: -26.9, conta: 'cartao' },
  { data: '2026-08-05', descricao: 'Cashback', categoria: 'Outras receitas', valor: 508.0, conta: 'cartao' },
  { data: '2026-08-05', descricao: 'Dif', categoria: 'Reembolso', valor: 3.57, conta: 'cartao' },
  { data: '2026-08-05', descricao: 'IFD GSA LANCHES ARMAND', categoria: 'Alimentação', valor: -56.48, conta: 'cartao' },
  { data: '2026-08-04', descricao: 'DROGARIA SAO PAULO 521', categoria: 'Saúde - Variável', valor: -70.24, conta: 'cartao' },
  { data: '2026-08-04', descricao: 'POSTO PANNUNZIO', categoria: 'Carro - Variável', valor: -157.47, conta: 'cartao' },
  { data: '2026-08-04', descricao: 'SUPERMERCADO TAUSTE', categoria: 'Mercado', valor: -51.49, conta: 'cartao' },
  { data: '2026-08-04', descricao: 'REAL ENTAUSTE LTDA', categoria: 'Alimentação', valor: -27.4, conta: 'cartao' },
  { data: '2026-08-04', descricao: 'MED PARKING', categoria: 'Carro - Variável', valor: -8.0, conta: 'cartao' },
  { data: '2026-08-04', descricao: 'Seguro Carro 10/12', categoria: 'Carro - Man/Imp/Seg', valor: -387.76, conta: 'cartao' },
  { data: '2026-08-04', descricao: 'NETFLIX', categoria: 'Assinaturas e serviços', valor: -44.9, conta: 'cartao' },
  { data: '2026-08-03', descricao: 'Shopify', categoria: '$ Objetivos - Metas', valor: -102.01, conta: 'cartao' },
  { data: '2026-08-02', descricao: 'CINEPOLIS OPERADORA DE', categoria: 'Diversão e Lazer', valor: -151.5, conta: 'cartao' },
  { data: '2026-08-01', descricao: 'IG*Empreender', categoria: '$ Objetivos - Metas', valor: -59.0, conta: 'cartao' },
]

export async function seedIfEmpty() {
  const jaTemCategoria = await db.categorias.count()
  if (jaTemCategoria === 0) {
    await seedCategoriasContasELancamentos()
  }

  // Semente de `planos` (08/09/2026, G59 — "Gerenciar Planos" migrou de
  // array TS fixo pra tabela Dexie). Guard PRÓPRIO, separado do de
  // categoria acima, de propósito: um banco que já tinha categorias
  // semeadas antes desta rodada (ou seja, já passou pelo `if` acima em
  // rodadas anteriores) também precisa ganhar os 2 planos placeholder ao
  // abrir esta build pela 1ª vez — se o guard fosse só o de categoria, essa
  // instalação nunca entraria aqui e a tabela `planos` ficaria vazia pra
  // sempre. BUG REAL que isto substitui: a 1ª versão desta migração
  // semeava os planos dentro do `.upgrade()` da v7 do schema Dexie
  // (`db.ts`) — funciona só pra quem já tinha um banco na v6 subindo pra
  // v7; um banco criado do zero nunca roda `.upgrade()` nenhum (Dexie
  // aplica o schema final direto, sem "migrar"), então toda instalação
  // NOVA nascia com `planos` vazia. Achado por Playwright antes de
  // entregar (ver Decisões.md do Project).
  const jaTemPlano = await db.planos.count()
  if (jaTemPlano === 0) {
    await db.planos.bulkAdd([
      {
        nome: 'Essencial (placeholder)',
        valorMensal: 0,
        ativo: true,
        funcionalidades: ['Resumo, Situação, Lançamentos, Carteira, Planejamento', 'Categorias e contas ilimitadas'],
      },
      {
        nome: 'Completo (placeholder)',
        valorMensal: 0,
        ativo: true,
        destaque: true,
        funcionalidades: [
          'Tudo do Essencial',
          'Layout do rodapé personalizável',
          'Suporte prioritário (quando existir canal de suporte de verdade)',
        ],
      },
    ])
  }
}

async function seedCategoriasContasELancamentos() {
  await db.transaction('rw', db.categorias, db.grupos, db.contas, db.metas, db.lancamentos, async () => {
    // 04/09/2026: novo banco (fresh install/demo) já nasce com os ícones que
    // o Rafael definiu como padrão do sistema (ver `iconesPadrao.ts`) — sem
    // isso, cairia tudo no ícone genérico "outros" até alguém configurar de
    // novo na mão.
    // 11/09/2026: cada grupo nasce já com o tipo (entrada × saída) e o grupo
    // "Receita" passa a ser padrão do app, não mais fruto da migração — foi o
    // pedido do Rafael ao escolher o destino das categorias de receita ("já
    // aproveita e salva isso tudo como padrão no app pra gerar as próximas
    // versões com eles"). Ver `src/gruposUtil.ts`.
    await db.grupos.bulkAdd(
      [
        { nome: 'Fixo', ativo: true, tipo: 'saida' as const },
        { nome: 'Variável', ativo: true, tipo: 'saida' as const },
        { nome: 'Objetivos', ativo: true, tipo: 'saida' as const },
        { nome: 'Segurança', ativo: true, tipo: 'saida' as const },
        { nome: GRUPO_RECEITA, ativo: true, tipo: 'entrada' as const },
      ].map(comIconePadraoGrupo),
    )
    await db.categorias.bulkAdd(CATEGORIAS_PADRAO.map(comIconePadraoCategoria))
    const categorias = await db.categorias.toArray()
    const idPorNome = new Map(categorias.map((c) => [c.nome, c.id!]))

    const contaBradescoId = (await db.contas.add({
      nome: 'Bradesco',
      tipo: 'corrente',
      instituicao: 'Bradesco',
      saldoInicial: 0,
      dataSaldoInicial: new Date().toISOString().slice(0, 10),
      importavel: true,
      ativa: true,
    })) as number
    const contaCartaoId = (await db.contas.add({
      nome: 'Porto Seguro',
      tipo: 'cartao',
      instituicao: 'Porto Seguro',
      saldoInicial: 0,
      dataSaldoInicial: new Date().toISOString().slice(0, 10),
      importavel: true,
      ativa: true,
      diaFechamento: 9,
      diaVencimento: 15,
      contaPagamentoPadraoId: contaBradescoId,
    })) as number

    // Meta é cadastro único por grupo — vale pra frente (não muda
    // histórico mês a mês). mesVigencia aqui é só informativo.
    const mesVigencia = new Date().toISOString().slice(0, 7).replace('-', '')
    await db.metas.bulkAdd([
      { grupo: 'Fixo', percentual: 47, base: 'receita_real', mesVigencia },
      { grupo: 'Variável', percentual: 33, base: 'receita_real', mesVigencia },
      { grupo: 'Objetivos', percentual: 10, base: 'receita_real', mesVigencia },
      { grupo: 'Segurança', percentual: 10, base: 'receita_real', mesVigencia },
    ])

    const lancamentos: Omit<Lancamento, 'id'>[] = LANCAMENTOS_SEMENTE.map((l) => {
      const categoriaId = idPorNome.get(l.categoria)
      if (!categoriaId) throw new Error(`Categoria não encontrada no seed: ${l.categoria}`)
      return {
        dataCompetencia: l.data,
        dataCaixa: l.data,
        descricao: l.descricao,
        valor: l.valor,
        contaId: l.conta === 'cartao' ? contaCartaoId : contaBradescoId,
        pagoPor: l.conta === 'cartao' ? 'cartao' : 'conta',
        categoriaId,
        status: 'importado',
        pago: true, // histórico real extraído da planilha — já liquidado
      }
    })
    await db.lancamentos.bulkAdd(lancamentos)
  })
}
